// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controlplane.proto

package cloud

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControlPlaneState int32

const (
	ControlPlaneState_Unknown ControlPlaneState = 0
	ControlPlaneState_Active  ControlPlaneState = 1
	ControlPlaneState_Leader  ControlPlaneState = 2
)

var ControlPlaneState_name = map[int32]string{
	0: "Unknown",
	1: "Active",
	2: "Leader",
}

var ControlPlaneState_value = map[string]int32{
	"Unknown": 0,
	"Active":  1,
	"Leader":  2,
}

func (x ControlPlaneState) String() string {
	return proto.EnumName(ControlPlaneState_name, int32(x))
}

func (ControlPlaneState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5f0814968a0baa7, []int{0}
}

type ControlPlaneRequest struct {
	ControlPlanes        []*ControlPlane  `protobuf:"bytes,1,rep,name=ControlPlanes,proto3" json:"ControlPlanes,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ControlPlaneRequest) Reset()         { *m = ControlPlaneRequest{} }
func (m *ControlPlaneRequest) String() string { return proto.CompactTextString(m) }
func (*ControlPlaneRequest) ProtoMessage()    {}
func (*ControlPlaneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5f0814968a0baa7, []int{0}
}

func (m *ControlPlaneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlaneRequest.Unmarshal(m, b)
}
func (m *ControlPlaneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlaneRequest.Marshal(b, m, deterministic)
}
func (m *ControlPlaneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlaneRequest.Merge(m, src)
}
func (m *ControlPlaneRequest) XXX_Size() int {
	return xxx_messageInfo_ControlPlaneRequest.Size(m)
}
func (m *ControlPlaneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlaneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlaneRequest proto.InternalMessageInfo

func (m *ControlPlaneRequest) GetControlPlanes() []*ControlPlane {
	if m != nil {
		return m.ControlPlanes
	}
	return nil
}

func (m *ControlPlaneRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type ControlPlaneResponse struct {
	ControlPlanes        []*ControlPlane     `protobuf:"bytes,1,rep,name=ControlPlanes,proto3" json:"ControlPlanes,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ControlPlaneResponse) Reset()         { *m = ControlPlaneResponse{} }
func (m *ControlPlaneResponse) String() string { return proto.CompactTextString(m) }
func (*ControlPlaneResponse) ProtoMessage()    {}
func (*ControlPlaneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5f0814968a0baa7, []int{1}
}

func (m *ControlPlaneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlaneResponse.Unmarshal(m, b)
}
func (m *ControlPlaneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlaneResponse.Marshal(b, m, deterministic)
}
func (m *ControlPlaneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlaneResponse.Merge(m, src)
}
func (m *ControlPlaneResponse) XXX_Size() int {
	return xxx_messageInfo_ControlPlaneResponse.Size(m)
}
func (m *ControlPlaneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlaneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlaneResponse proto.InternalMessageInfo

func (m *ControlPlaneResponse) GetControlPlanes() []*ControlPlane {
	if m != nil {
		return m.ControlPlanes
	}
	return nil
}

func (m *ControlPlaneResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ControlPlaneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ControlPlane struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LocationName         string            `protobuf:"bytes,3,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Fqdn                 string            `protobuf:"bytes,4,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Port                 int32             `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Status               *common.Status    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	State                ControlPlaneState `protobuf:"varint,7,opt,name=state,proto3,enum=moc.cloudagent.controlplane.ControlPlaneState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ControlPlane) Reset()         { *m = ControlPlane{} }
func (m *ControlPlane) String() string { return proto.CompactTextString(m) }
func (*ControlPlane) ProtoMessage()    {}
func (*ControlPlane) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5f0814968a0baa7, []int{2}
}

func (m *ControlPlane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlPlane.Unmarshal(m, b)
}
func (m *ControlPlane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlPlane.Marshal(b, m, deterministic)
}
func (m *ControlPlane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlPlane.Merge(m, src)
}
func (m *ControlPlane) XXX_Size() int {
	return xxx_messageInfo_ControlPlane.Size(m)
}
func (m *ControlPlane) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlPlane.DiscardUnknown(m)
}

var xxx_messageInfo_ControlPlane proto.InternalMessageInfo

func (m *ControlPlane) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ControlPlane) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ControlPlane) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *ControlPlane) GetFqdn() string {
	if m != nil {
		return m.Fqdn
	}
	return ""
}

func (m *ControlPlane) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ControlPlane) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ControlPlane) GetState() ControlPlaneState {
	if m != nil {
		return m.State
	}
	return ControlPlaneState_Unknown
}

func init() {
	proto.RegisterEnum("moc.cloudagent.controlplane.ControlPlaneState", ControlPlaneState_name, ControlPlaneState_value)
	proto.RegisterType((*ControlPlaneRequest)(nil), "moc.cloudagent.controlplane.ControlPlaneRequest")
	proto.RegisterType((*ControlPlaneResponse)(nil), "moc.cloudagent.controlplane.ControlPlaneResponse")
	proto.RegisterType((*ControlPlane)(nil), "moc.cloudagent.controlplane.ControlPlane")
}

func init() { proto.RegisterFile("controlplane.proto", fileDescriptor_e5f0814968a0baa7) }

var fileDescriptor_e5f0814968a0baa7 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0xad, 0xb7, 0xdd, 0x54, 0x9d, 0xdd, 0xae, 0x16, 0xd3, 0x43, 0xb4, 0x48, 0x68, 0x15, 0x2e,
	0x0b, 0x12, 0x0e, 0x04, 0x0e, 0x5c, 0x5b, 0xe0, 0x80, 0x84, 0x28, 0x32, 0x1f, 0x07, 0x6e, 0x59,
	0xc7, 0x1b, 0xa2, 0x26, 0x1e, 0xd7, 0x76, 0x5a, 0x71, 0xe7, 0x67, 0xf0, 0x27, 0xf8, 0x59, 0xfc,
	0x0b, 0x64, 0xbb, 0xc0, 0x46, 0x48, 0xa8, 0x48, 0xbd, 0x3d, 0xcf, 0xbc, 0xf7, 0x3c, 0x7e, 0x1e,
	0xa0, 0x02, 0x95, 0x33, 0xd8, 0xea, 0xb6, 0x54, 0x92, 0x69, 0x83, 0x0e, 0xe9, 0x9d, 0x0e, 0x05,
	0x13, 0x2d, 0xf6, 0x55, 0x59, 0x4b, 0xe5, 0xd8, 0x36, 0x65, 0x71, 0xb7, 0x46, 0xac, 0x5b, 0x99,
	0x07, 0xea, 0xba, 0xdf, 0xe4, 0x97, 0xa6, 0xd4, 0x5a, 0x1a, 0x1b, 0xc5, 0x8b, 0xa9, 0xc0, 0xae,
	0x43, 0x15, 0x4f, 0xd9, 0x37, 0x02, 0xb7, 0x9f, 0x47, 0xf9, 0x5b, 0x2f, 0xe7, 0xf2, 0xbc, 0x97,
	0xd6, 0xd1, 0x53, 0x38, 0xdc, 0x2e, 0xdb, 0x94, 0x2c, 0x77, 0x57, 0x93, 0xe2, 0x3e, 0xfb, 0xc7,
	0xd5, 0x6c, 0x60, 0x34, 0xd4, 0xd3, 0xa7, 0x70, 0x78, 0xaa, 0xa5, 0x29, 0x5d, 0x83, 0xea, 0xfd,
	0x17, 0x2d, 0xd3, 0xd1, 0x92, 0xac, 0x66, 0xc5, 0x2c, 0x18, 0xfe, 0xee, 0xf0, 0x21, 0x29, 0xfb,
	0x4e, 0xe0, 0x68, 0x38, 0x9e, 0xd5, 0xa8, 0xac, 0xbc, 0xf9, 0xf9, 0x0a, 0x48, 0xb8, 0xb4, 0x7d,
	0xeb, 0xc2, 0x60, 0x93, 0x62, 0xc1, 0x62, 0x8e, 0xec, 0x57, 0x8e, 0xec, 0x04, 0xb1, 0xfd, 0x58,
	0xb6, 0xbd, 0xe4, 0x57, 0x4c, 0x7a, 0x04, 0xe3, 0x97, 0xc6, 0xa0, 0x49, 0x77, 0x97, 0x64, 0x75,
	0xc0, 0xe3, 0x21, 0xfb, 0x41, 0x60, 0xba, 0xed, 0x4d, 0x67, 0x30, 0x6a, 0xaa, 0x94, 0x04, 0xce,
	0xa8, 0xa9, 0x28, 0x85, 0x3d, 0x55, 0x76, 0x31, 0x81, 0x03, 0x1e, 0x30, 0xcd, 0x60, 0xda, 0xa2,
	0x08, 0x0f, 0x7f, 0xe3, 0x7b, 0xd1, 0x71, 0x50, 0xf3, 0xba, 0xcd, 0x79, 0xa5, 0xd2, 0xbd, 0xa8,
	0xf3, 0xd8, 0xd7, 0x34, 0x1a, 0x97, 0x8e, 0x97, 0x64, 0x35, 0xe6, 0x01, 0xd3, 0x7b, 0x90, 0x58,
	0x57, 0xba, 0xde, 0xa6, 0x49, 0x78, 0xca, 0x24, 0x84, 0xf2, 0x2e, 0x94, 0xf8, 0x55, 0x8b, 0xbe,
	0x80, 0xb1, 0x47, 0x32, 0xdd, 0x0f, 0xff, 0xc0, 0xae, 0x1d, 0x9c, 0xf7, 0x91, 0x3c, 0x8a, 0x1f,
	0x3c, 0x83, 0x5b, 0x7f, 0xf5, 0xe8, 0x04, 0xf6, 0x3f, 0xa8, 0x33, 0x85, 0x97, 0x6a, 0xbe, 0x43,
	0x01, 0x92, 0x63, 0xe1, 0x9a, 0x0b, 0x39, 0x27, 0x1e, 0xbf, 0x96, 0x65, 0x25, 0xcd, 0x7c, 0x54,
	0x7c, 0x25, 0x43, 0xe9, 0xb1, 0xbf, 0x95, 0x22, 0x24, 0xaf, 0xd4, 0x05, 0x9e, 0x49, 0xfa, 0xe8,
	0xfa, 0x3f, 0x19, 0x57, 0x76, 0xf1, 0xf8, 0x3f, 0x14, 0x71, 0x8b, 0xb2, 0x9d, 0x93, 0xfc, 0xd3,
	0xc3, 0xba, 0x71, 0x9f, 0xfb, 0x35, 0x13, 0xd8, 0xe5, 0x5d, 0x23, 0x0c, 0x5a, 0xdc, 0xb8, 0xbc,
	0x43, 0x91, 0x1b, 0x2d, 0xf2, 0x3f, 0x76, 0x11, 0xae, 0x93, 0xb0, 0x0f, 0x4f, 0x7e, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xf2, 0x27, 0xb5, 0x01, 0x98, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlPlaneAgentClient is the client API for ControlPlaneAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlPlaneAgentClient interface {
	Invoke(ctx context.Context, in *ControlPlaneRequest, opts ...grpc.CallOption) (*ControlPlaneResponse, error)
}

type controlPlaneAgentClient struct {
	cc *grpc.ClientConn
}

func NewControlPlaneAgentClient(cc *grpc.ClientConn) ControlPlaneAgentClient {
	return &controlPlaneAgentClient{cc}
}

func (c *controlPlaneAgentClient) Invoke(ctx context.Context, in *ControlPlaneRequest, opts ...grpc.CallOption) (*ControlPlaneResponse, error) {
	out := new(ControlPlaneResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.controlplane.ControlPlaneAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneAgentServer is the server API for ControlPlaneAgent service.
type ControlPlaneAgentServer interface {
	Invoke(context.Context, *ControlPlaneRequest) (*ControlPlaneResponse, error)
}

// UnimplementedControlPlaneAgentServer can be embedded to have forward compatible implementations.
type UnimplementedControlPlaneAgentServer struct {
}

func (*UnimplementedControlPlaneAgentServer) Invoke(ctx context.Context, req *ControlPlaneRequest) (*ControlPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterControlPlaneAgentServer(s *grpc.Server, srv ControlPlaneAgentServer) {
	s.RegisterService(&_ControlPlaneAgent_serviceDesc, srv)
}

func _ControlPlaneAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.controlplane.ControlPlaneAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneAgentServer).Invoke(ctx, req.(*ControlPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlPlaneAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.cloudagent.controlplane.ControlPlaneAgent",
	HandlerType: (*ControlPlaneAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _ControlPlaneAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane.proto",
}
