// Code generated by protoc-gen-go. DO NOT EDIT.
// source: computecommon.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserType int32

const (
	UserType_ROOT UserType = 0
	UserType_USER UserType = 1
)

var UserType_name = map[int32]string{
	0: "ROOT",
	1: "USER",
}

var UserType_value = map[string]int32{
	"ROOT": 0,
	"USER": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f09f9f48a46aad09, []int{0}
}

type ProcessorType int32

const (
	ProcessorType_None    ProcessorType = 0
	ProcessorType_Intel   ProcessorType = 1
	ProcessorType_Intel64 ProcessorType = 2
	ProcessorType_AMD     ProcessorType = 3
	ProcessorType_AMD64   ProcessorType = 4
	ProcessorType_ARM     ProcessorType = 5
	ProcessorType_ARM64   ProcessorType = 6
)

var ProcessorType_name = map[int32]string{
	0: "None",
	1: "Intel",
	2: "Intel64",
	3: "AMD",
	4: "AMD64",
	5: "ARM",
	6: "ARM64",
}

var ProcessorType_value = map[string]int32{
	"None":    0,
	"Intel":   1,
	"Intel64": 2,
	"AMD":     3,
	"AMD64":   4,
	"ARM":     5,
	"ARM64":   6,
}

func (x ProcessorType) String() string {
	return proto.EnumName(ProcessorType_name, int32(x))
}

func (ProcessorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f09f9f48a46aad09, []int{1}
}

type OperatingSystemType int32

const (
	OperatingSystemType_WINDOWS OperatingSystemType = 0
	OperatingSystemType_LINUX   OperatingSystemType = 1
)

var OperatingSystemType_name = map[int32]string{
	0: "WINDOWS",
	1: "LINUX",
}

var OperatingSystemType_value = map[string]int32{
	"WINDOWS": 0,
	"LINUX":   1,
}

func (x OperatingSystemType) String() string {
	return proto.EnumName(OperatingSystemType_name, int32(x))
}

func (OperatingSystemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f09f9f48a46aad09, []int{2}
}

type VirtualMachineSizeType int32

const (
	VirtualMachineSizeType_Default          VirtualMachineSizeType = 0
	VirtualMachineSizeType_Standard_A2_v2   VirtualMachineSizeType = 2
	VirtualMachineSizeType_Standard_A4_v2   VirtualMachineSizeType = 3
	VirtualMachineSizeType_Standard_D2s_v3  VirtualMachineSizeType = 4
	VirtualMachineSizeType_Standard_D4s_v3  VirtualMachineSizeType = 5
	VirtualMachineSizeType_Standard_D8s_v3  VirtualMachineSizeType = 6
	VirtualMachineSizeType_Standard_D16s_v3 VirtualMachineSizeType = 7
	VirtualMachineSizeType_Standard_D32s_v3 VirtualMachineSizeType = 8
	VirtualMachineSizeType_Standard_DS2_v2  VirtualMachineSizeType = 9
	VirtualMachineSizeType_Standard_DS3_v2  VirtualMachineSizeType = 10
	VirtualMachineSizeType_Standard_DS4_v2  VirtualMachineSizeType = 11
	VirtualMachineSizeType_Standard_DS5_v2  VirtualMachineSizeType = 12
	VirtualMachineSizeType_Standard_DS13_v2 VirtualMachineSizeType = 13
	VirtualMachineSizeType_Standard_K8S_v1  VirtualMachineSizeType = 14
	VirtualMachineSizeType_Standard_K8S2_v1 VirtualMachineSizeType = 15
	VirtualMachineSizeType_Standard_K8S3_v1 VirtualMachineSizeType = 16
	VirtualMachineSizeType_Standard_K8S4_v1 VirtualMachineSizeType = 17
	VirtualMachineSizeType_Standard_NK6     VirtualMachineSizeType = 18
	VirtualMachineSizeType_Standard_NK12    VirtualMachineSizeType = 19
	VirtualMachineSizeType_Standard_NV6     VirtualMachineSizeType = 20
	VirtualMachineSizeType_Standard_NV12    VirtualMachineSizeType = 21
	VirtualMachineSizeType_Unsupported      VirtualMachineSizeType = 99
)

var VirtualMachineSizeType_name = map[int32]string{
	0:  "Default",
	2:  "Standard_A2_v2",
	3:  "Standard_A4_v2",
	4:  "Standard_D2s_v3",
	5:  "Standard_D4s_v3",
	6:  "Standard_D8s_v3",
	7:  "Standard_D16s_v3",
	8:  "Standard_D32s_v3",
	9:  "Standard_DS2_v2",
	10: "Standard_DS3_v2",
	11: "Standard_DS4_v2",
	12: "Standard_DS5_v2",
	13: "Standard_DS13_v2",
	14: "Standard_K8S_v1",
	15: "Standard_K8S2_v1",
	16: "Standard_K8S3_v1",
	17: "Standard_K8S4_v1",
	18: "Standard_NK6",
	19: "Standard_NK12",
	20: "Standard_NV6",
	21: "Standard_NV12",
	99: "Unsupported",
}

var VirtualMachineSizeType_value = map[string]int32{
	"Default":          0,
	"Standard_A2_v2":   2,
	"Standard_A4_v2":   3,
	"Standard_D2s_v3":  4,
	"Standard_D4s_v3":  5,
	"Standard_D8s_v3":  6,
	"Standard_D16s_v3": 7,
	"Standard_D32s_v3": 8,
	"Standard_DS2_v2":  9,
	"Standard_DS3_v2":  10,
	"Standard_DS4_v2":  11,
	"Standard_DS5_v2":  12,
	"Standard_DS13_v2": 13,
	"Standard_K8S_v1":  14,
	"Standard_K8S2_v1": 15,
	"Standard_K8S3_v1": 16,
	"Standard_K8S4_v1": 17,
	"Standard_NK6":     18,
	"Standard_NK12":    19,
	"Standard_NV6":     20,
	"Standard_NV12":    21,
	"Unsupported":      99,
}

func (x VirtualMachineSizeType) String() string {
	return proto.EnumName(VirtualMachineSizeType_name, int32(x))
}

func (VirtualMachineSizeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f09f9f48a46aad09, []int{3}
}

type PowerState int32

const (
	PowerState_Unknown  PowerState = 0
	PowerState_Running  PowerState = 1
	PowerState_Off      PowerState = 2
	PowerState_Paused   PowerState = 3
	PowerState_Critical PowerState = 4
)

var PowerState_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Off",
	3: "Paused",
	4: "Critical",
}

var PowerState_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Off":      2,
	"Paused":   3,
	"Critical": 4,
}

func (x PowerState) String() string {
	return proto.EnumName(PowerState_name, int32(x))
}

func (PowerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f09f9f48a46aad09, []int{4}
}

type VirtualMachineOperation int32

const (
	VirtualMachineOperation_START VirtualMachineOperation = 0
	VirtualMachineOperation_STOP  VirtualMachineOperation = 1
	VirtualMachineOperation_RESET VirtualMachineOperation = 2
)

var VirtualMachineOperation_name = map[int32]string{
	0: "START",
	1: "STOP",
	2: "RESET",
}

var VirtualMachineOperation_value = map[string]int32{
	"START": 0,
	"STOP":  1,
	"RESET": 2,
}

func (x VirtualMachineOperation) String() string {
	return proto.EnumName(VirtualMachineOperation_name, int32(x))
}

func (VirtualMachineOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f09f9f48a46aad09, []int{5}
}

func init() {
	proto.RegisterEnum("moc.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("moc.ProcessorType", ProcessorType_name, ProcessorType_value)
	proto.RegisterEnum("moc.OperatingSystemType", OperatingSystemType_name, OperatingSystemType_value)
	proto.RegisterEnum("moc.VirtualMachineSizeType", VirtualMachineSizeType_name, VirtualMachineSizeType_value)
	proto.RegisterEnum("moc.PowerState", PowerState_name, PowerState_value)
	proto.RegisterEnum("moc.VirtualMachineOperation", VirtualMachineOperation_name, VirtualMachineOperation_value)
}

func init() { proto.RegisterFile("computecommon.proto", fileDescriptor_f09f9f48a46aad09) }

var fileDescriptor_f09f9f48a46aad09 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd3, 0x5f, 0x6f, 0xda, 0x3c,
	0x14, 0x06, 0x70, 0x20, 0xfc, 0xeb, 0x01, 0xca, 0xa9, 0xe9, 0xfb, 0xee, 0x6e, 0xf7, 0xcb, 0xd4,
	0xa2, 0x40, 0x16, 0xb1, 0x4b, 0x36, 0xb8, 0x40, 0x0c, 0x82, 0x62, 0xa0, 0xdb, 0x6e, 0x50, 0x1a,
	0x0c, 0x8d, 0x46, 0xec, 0x28, 0x71, 0xa8, 0xba, 0xcf, 0xb9, 0x0f, 0x34, 0xd9, 0x74, 0x6c, 0xe1,
	0xce, 0xf9, 0xe9, 0xb1, 0x8f, 0xa5, 0x3c, 0x86, 0x4e, 0x20, 0xa2, 0x38, 0x93, 0x2c, 0x10, 0x51,
	0x24, 0xf8, 0x7d, 0x9c, 0x08, 0x29, 0x88, 0x11, 0x89, 0xc0, 0x7c, 0x0b, 0xf5, 0x55, 0xca, 0x92,
	0xe5, 0x4b, 0xcc, 0x48, 0x1d, 0xca, 0x9e, 0xeb, 0x2e, 0xb1, 0xa0, 0x56, 0x2b, 0x3a, 0xf6, 0xb0,
	0x68, 0x7e, 0x83, 0xd6, 0x22, 0x11, 0x01, 0x4b, 0x53, 0x71, 0x0e, 0xcd, 0x05, 0x67, 0x58, 0x20,
	0x57, 0x50, 0x99, 0x70, 0xc9, 0x0e, 0x58, 0x24, 0x0d, 0xa8, 0xe9, 0xa5, 0x63, 0x63, 0x89, 0xd4,
	0xc0, 0x18, 0xce, 0x46, 0x68, 0xa8, 0xc0, 0x70, 0x36, 0x72, 0x6c, 0x2c, 0x6b, 0xf3, 0x66, 0x58,
	0xd1, 0xe6, 0xcd, 0x1c, 0x1b, 0xab, 0xe6, 0x1d, 0x74, 0xdc, 0x98, 0x25, 0xbe, 0x0c, 0xf9, 0x9e,
	0xbe, 0xa4, 0x92, 0x45, 0x7a, 0x40, 0x03, 0x6a, 0x0f, 0x93, 0xf9, 0xc8, 0x7d, 0xa0, 0xa7, 0x19,
	0x5f, 0x26, 0xf3, 0xd5, 0x57, 0x2c, 0x9a, 0xbf, 0x0c, 0xf8, 0x7f, 0x1d, 0x26, 0x32, 0xf3, 0x0f,
	0x33, 0x3f, 0x78, 0x0a, 0x39, 0xa3, 0xe1, 0x4f, 0xf6, 0x67, 0xcb, 0x88, 0xed, 0xfc, 0xec, 0x20,
	0xb1, 0x40, 0x08, 0x5c, 0x53, 0xe9, 0xf3, 0xad, 0x9f, 0x6c, 0x37, 0xc3, 0xde, 0xe6, 0xd8, 0xc3,
	0x52, 0xde, 0x6c, 0x65, 0x06, 0xe9, 0x40, 0xfb, 0x6c, 0xa3, 0x5e, 0xba, 0x39, 0xf6, 0xb1, 0x9c,
	0x47, 0x5b, 0x63, 0x25, 0x8f, 0x03, 0x8d, 0x55, 0x72, 0x0b, 0xf8, 0x17, 0x2d, 0x47, 0x6b, 0x2d,
	0xaf, 0xfd, 0xd3, 0xa9, 0xf5, 0xfc, 0x01, 0x54, 0xdf, 0xe9, 0xea, 0x02, 0xfb, 0x0a, 0xe1, 0x02,
	0xf5, 0x4d, 0x1b, 0x17, 0xf8, 0x41, 0x61, 0x33, 0x3f, 0x89, 0x5a, 0x7a, 0x7f, 0x2b, 0x17, 0x9d,
	0x0e, 0xe8, 0xe6, 0x68, 0xe1, 0x75, 0x2e, 0x3a, 0x1d, 0xa8, 0xf9, 0x16, 0xb6, 0x2f, 0xb5, 0xaf,
	0x14, 0x2f, 0xd5, 0x56, 0x7a, 0x43, 0x10, 0x9a, 0x67, 0x9d, 0x4f, 0x1d, 0x24, 0xe4, 0x06, 0x5a,
	0xff, 0x88, 0xd5, 0xc3, 0x4e, 0x3e, 0xb4, 0x76, 0xf0, 0x36, 0x1f, 0x5a, 0x5b, 0x3d, 0xfc, 0x8f,
	0xb4, 0xa1, 0xb1, 0xe2, 0x69, 0x16, 0xc7, 0x22, 0x91, 0x6c, 0x8b, 0x81, 0x39, 0x01, 0x58, 0x88,
	0x67, 0x96, 0x50, 0xe9, 0x4b, 0xfd, 0x27, 0x57, 0xfc, 0x07, 0x17, 0xcf, 0x1c, 0x0b, 0xea, 0xc3,
	0xcb, 0x38, 0x0f, 0xf9, 0x1e, 0x8b, 0xaa, 0x41, 0xee, 0x6e, 0x87, 0x25, 0x02, 0x50, 0x5d, 0xf8,
	0x59, 0xca, 0xb6, 0x68, 0x90, 0x26, 0xd4, 0x3f, 0x27, 0xa1, 0x0c, 0x03, 0xff, 0x80, 0x65, 0xf3,
	0x23, 0xbc, 0xc9, 0x17, 0xe4, 0xb5, 0x5e, 0x82, 0xab, 0x1e, 0xd1, 0xe5, 0xd0, 0x7b, 0xed, 0x36,
	0x5d, 0xba, 0x0b, 0x2c, 0x2a, 0xf4, 0xc6, 0x74, 0xbc, 0xc4, 0xd2, 0xa7, 0xf7, 0xdf, 0xdf, 0xed,
	0x43, 0xf9, 0x94, 0x3d, 0xde, 0x07, 0x22, 0xea, 0x46, 0x61, 0x90, 0x88, 0x54, 0xec, 0x64, 0x37,
	0x12, 0xc1, 0x9d, 0x7e, 0x2d, 0xdd, 0x24, 0x0e, 0xba, 0xa7, 0xe7, 0xf3, 0x58, 0xd5, 0xd2, 0xff,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0c, 0xed, 0x12, 0x56, 0x03, 0x00, 0x00,
}
