// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_common_computecommon.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserType int32

const (
	UserType_ROOT UserType = 0
	UserType_USER UserType = 1
)

var UserType_name = map[int32]string{
	0: "ROOT",
	1: "USER",
}

var UserType_value = map[string]int32{
	"ROOT": 0,
	"USER": 1,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{0}
}

type ProcessorType int32

const (
	ProcessorType_None    ProcessorType = 0
	ProcessorType_Intel   ProcessorType = 1
	ProcessorType_Intel64 ProcessorType = 2
	ProcessorType_AMD     ProcessorType = 3
	ProcessorType_AMD64   ProcessorType = 4
	ProcessorType_ARM     ProcessorType = 5
	ProcessorType_ARM64   ProcessorType = 6
)

var ProcessorType_name = map[int32]string{
	0: "None",
	1: "Intel",
	2: "Intel64",
	3: "AMD",
	4: "AMD64",
	5: "ARM",
	6: "ARM64",
}

var ProcessorType_value = map[string]int32{
	"None":    0,
	"Intel":   1,
	"Intel64": 2,
	"AMD":     3,
	"AMD64":   4,
	"ARM":     5,
	"ARM64":   6,
}

func (x ProcessorType) String() string {
	return proto.EnumName(ProcessorType_name, int32(x))
}

func (ProcessorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{1}
}

type OperatingSystemBootstrapEngine int32

const (
	OperatingSystemBootstrapEngine_CLOUD_INIT           OperatingSystemBootstrapEngine = 0
	OperatingSystemBootstrapEngine_WINDOWS_ANSWER_FILES OperatingSystemBootstrapEngine = 1
)

var OperatingSystemBootstrapEngine_name = map[int32]string{
	0: "CLOUD_INIT",
	1: "WINDOWS_ANSWER_FILES",
}

var OperatingSystemBootstrapEngine_value = map[string]int32{
	"CLOUD_INIT":           0,
	"WINDOWS_ANSWER_FILES": 1,
}

func (x OperatingSystemBootstrapEngine) String() string {
	return proto.EnumName(OperatingSystemBootstrapEngine_name, int32(x))
}

func (OperatingSystemBootstrapEngine) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{2}
}

type OperatingSystemType int32

const (
	OperatingSystemType_WINDOWS OperatingSystemType = 0
	OperatingSystemType_LINUX   OperatingSystemType = 1
)

var OperatingSystemType_name = map[int32]string{
	0: "WINDOWS",
	1: "LINUX",
}

var OperatingSystemType_value = map[string]int32{
	"WINDOWS": 0,
	"LINUX":   1,
}

func (x OperatingSystemType) String() string {
	return proto.EnumName(OperatingSystemType_name, int32(x))
}

func (OperatingSystemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{3}
}

type VirtualMachineSizeType int32

const (
	VirtualMachineSizeType_Default               VirtualMachineSizeType = 0
	VirtualMachineSizeType_Standard_A2_v2        VirtualMachineSizeType = 2
	VirtualMachineSizeType_Standard_A4_v2        VirtualMachineSizeType = 3
	VirtualMachineSizeType_Standard_D2s_v3       VirtualMachineSizeType = 4
	VirtualMachineSizeType_Standard_D4s_v3       VirtualMachineSizeType = 5
	VirtualMachineSizeType_Standard_D8s_v3       VirtualMachineSizeType = 6
	VirtualMachineSizeType_Standard_D16s_v3      VirtualMachineSizeType = 7
	VirtualMachineSizeType_Standard_D32s_v3      VirtualMachineSizeType = 8
	VirtualMachineSizeType_Standard_DS2_v2       VirtualMachineSizeType = 9
	VirtualMachineSizeType_Standard_DS3_v2       VirtualMachineSizeType = 10
	VirtualMachineSizeType_Standard_DS4_v2       VirtualMachineSizeType = 11
	VirtualMachineSizeType_Standard_DS5_v2       VirtualMachineSizeType = 12
	VirtualMachineSizeType_Standard_DS13_v2      VirtualMachineSizeType = 13
	VirtualMachineSizeType_Standard_K8S_v1       VirtualMachineSizeType = 14
	VirtualMachineSizeType_Standard_K8S2_v1      VirtualMachineSizeType = 15
	VirtualMachineSizeType_Standard_K8S3_v1      VirtualMachineSizeType = 16
	VirtualMachineSizeType_Standard_K8S4_v1      VirtualMachineSizeType = 17
	VirtualMachineSizeType_Standard_NK6          VirtualMachineSizeType = 18
	VirtualMachineSizeType_Standard_NK12         VirtualMachineSizeType = 19
	VirtualMachineSizeType_Standard_NV6          VirtualMachineSizeType = 20
	VirtualMachineSizeType_Standard_NV12         VirtualMachineSizeType = 21
	VirtualMachineSizeType_Standard_K8S5_v1      VirtualMachineSizeType = 22
	VirtualMachineSizeType_Standard_DS2_v2_HPN   VirtualMachineSizeType = 23
	VirtualMachineSizeType_Standard_DS3_v2_HPN   VirtualMachineSizeType = 24
	VirtualMachineSizeType_Standard_DS4_v2_HPN   VirtualMachineSizeType = 25
	VirtualMachineSizeType_Standard_F2s_HPN      VirtualMachineSizeType = 26
	VirtualMachineSizeType_Standard_F4s_HPN      VirtualMachineSizeType = 27
	VirtualMachineSizeType_Standard_F8s_HPN      VirtualMachineSizeType = 28
	VirtualMachineSizeType_Standard_F16s_HPN     VirtualMachineSizeType = 29
	VirtualMachineSizeType_Standard_NC4_A2       VirtualMachineSizeType = 30
	VirtualMachineSizeType_Standard_NC8_A2       VirtualMachineSizeType = 31
	VirtualMachineSizeType_Standard_NC16_A2      VirtualMachineSizeType = 32
	VirtualMachineSizeType_Standard_NC32_A2      VirtualMachineSizeType = 33
	VirtualMachineSizeType_Standard_NC4_A30      VirtualMachineSizeType = 34
	VirtualMachineSizeType_Standard_NC8_A30      VirtualMachineSizeType = 35
	VirtualMachineSizeType_Standard_NC16_A30     VirtualMachineSizeType = 36
	VirtualMachineSizeType_Standard_NC32_A30     VirtualMachineSizeType = 37
	VirtualMachineSizeType_Standard_NC4_A100_40  VirtualMachineSizeType = 38
	VirtualMachineSizeType_Standard_NC8_A100_40  VirtualMachineSizeType = 39
	VirtualMachineSizeType_Standard_NC16_A100_40 VirtualMachineSizeType = 40
	VirtualMachineSizeType_Standard_NC32_A100_40 VirtualMachineSizeType = 41
	VirtualMachineSizeType_Standard_NC4_A100_80  VirtualMachineSizeType = 42
	VirtualMachineSizeType_Standard_NC8_A100_80  VirtualMachineSizeType = 43
	VirtualMachineSizeType_Standard_NC16_A100_80 VirtualMachineSizeType = 44
	VirtualMachineSizeType_Standard_NC32_A100_80 VirtualMachineSizeType = 45
	VirtualMachineSizeType_Standard_NC4_A16      VirtualMachineSizeType = 46
	VirtualMachineSizeType_Standard_NC8_A16      VirtualMachineSizeType = 47
	VirtualMachineSizeType_Standard_NC16_A16     VirtualMachineSizeType = 48
	VirtualMachineSizeType_Standard_NC32_A16     VirtualMachineSizeType = 49
	VirtualMachineSizeType_Standard_NC24_H100    VirtualMachineSizeType = 50
	VirtualMachineSizeType_Standard_NC48_H100    VirtualMachineSizeType = 51
	VirtualMachineSizeType_Standard_NC80_H100    VirtualMachineSizeType = 52
	VirtualMachineSizeType_Standard_NC96_H100    VirtualMachineSizeType = 53
	VirtualMachineSizeType_Custom_A2             VirtualMachineSizeType = 95
	VirtualMachineSizeType_Custom_NK             VirtualMachineSizeType = 96
	VirtualMachineSizeType_Custom_Gpupv          VirtualMachineSizeType = 97
	VirtualMachineSizeType_Custom                VirtualMachineSizeType = 98
	VirtualMachineSizeType_Unsupported           VirtualMachineSizeType = 99
)

var VirtualMachineSizeType_name = map[int32]string{
	0:  "Default",
	2:  "Standard_A2_v2",
	3:  "Standard_A4_v2",
	4:  "Standard_D2s_v3",
	5:  "Standard_D4s_v3",
	6:  "Standard_D8s_v3",
	7:  "Standard_D16s_v3",
	8:  "Standard_D32s_v3",
	9:  "Standard_DS2_v2",
	10: "Standard_DS3_v2",
	11: "Standard_DS4_v2",
	12: "Standard_DS5_v2",
	13: "Standard_DS13_v2",
	14: "Standard_K8S_v1",
	15: "Standard_K8S2_v1",
	16: "Standard_K8S3_v1",
	17: "Standard_K8S4_v1",
	18: "Standard_NK6",
	19: "Standard_NK12",
	20: "Standard_NV6",
	21: "Standard_NV12",
	22: "Standard_K8S5_v1",
	23: "Standard_DS2_v2_HPN",
	24: "Standard_DS3_v2_HPN",
	25: "Standard_DS4_v2_HPN",
	26: "Standard_F2s_HPN",
	27: "Standard_F4s_HPN",
	28: "Standard_F8s_HPN",
	29: "Standard_F16s_HPN",
	30: "Standard_NC4_A2",
	31: "Standard_NC8_A2",
	32: "Standard_NC16_A2",
	33: "Standard_NC32_A2",
	34: "Standard_NC4_A30",
	35: "Standard_NC8_A30",
	36: "Standard_NC16_A30",
	37: "Standard_NC32_A30",
	38: "Standard_NC4_A100_40",
	39: "Standard_NC8_A100_40",
	40: "Standard_NC16_A100_40",
	41: "Standard_NC32_A100_40",
	42: "Standard_NC4_A100_80",
	43: "Standard_NC8_A100_80",
	44: "Standard_NC16_A100_80",
	45: "Standard_NC32_A100_80",
	46: "Standard_NC4_A16",
	47: "Standard_NC8_A16",
	48: "Standard_NC16_A16",
	49: "Standard_NC32_A16",
	50: "Standard_NC24_H100",
	51: "Standard_NC48_H100",
	52: "Standard_NC80_H100",
	53: "Standard_NC96_H100",
	95: "Custom_A2",
	96: "Custom_NK",
	97: "Custom_Gpupv",
	98: "Custom",
	99: "Unsupported",
}

var VirtualMachineSizeType_value = map[string]int32{
	"Default":               0,
	"Standard_A2_v2":        2,
	"Standard_A4_v2":        3,
	"Standard_D2s_v3":       4,
	"Standard_D4s_v3":       5,
	"Standard_D8s_v3":       6,
	"Standard_D16s_v3":      7,
	"Standard_D32s_v3":      8,
	"Standard_DS2_v2":       9,
	"Standard_DS3_v2":       10,
	"Standard_DS4_v2":       11,
	"Standard_DS5_v2":       12,
	"Standard_DS13_v2":      13,
	"Standard_K8S_v1":       14,
	"Standard_K8S2_v1":      15,
	"Standard_K8S3_v1":      16,
	"Standard_K8S4_v1":      17,
	"Standard_NK6":          18,
	"Standard_NK12":         19,
	"Standard_NV6":          20,
	"Standard_NV12":         21,
	"Standard_K8S5_v1":      22,
	"Standard_DS2_v2_HPN":   23,
	"Standard_DS3_v2_HPN":   24,
	"Standard_DS4_v2_HPN":   25,
	"Standard_F2s_HPN":      26,
	"Standard_F4s_HPN":      27,
	"Standard_F8s_HPN":      28,
	"Standard_F16s_HPN":     29,
	"Standard_NC4_A2":       30,
	"Standard_NC8_A2":       31,
	"Standard_NC16_A2":      32,
	"Standard_NC32_A2":      33,
	"Standard_NC4_A30":      34,
	"Standard_NC8_A30":      35,
	"Standard_NC16_A30":     36,
	"Standard_NC32_A30":     37,
	"Standard_NC4_A100_40":  38,
	"Standard_NC8_A100_40":  39,
	"Standard_NC16_A100_40": 40,
	"Standard_NC32_A100_40": 41,
	"Standard_NC4_A100_80":  42,
	"Standard_NC8_A100_80":  43,
	"Standard_NC16_A100_80": 44,
	"Standard_NC32_A100_80": 45,
	"Standard_NC4_A16":      46,
	"Standard_NC8_A16":      47,
	"Standard_NC16_A16":     48,
	"Standard_NC32_A16":     49,
	"Standard_NC24_H100":    50,
	"Standard_NC48_H100":    51,
	"Standard_NC80_H100":    52,
	"Standard_NC96_H100":    53,
	"Custom_A2":             95,
	"Custom_NK":             96,
	"Custom_Gpupv":          97,
	"Custom":                98,
	"Unsupported":           99,
}

func (x VirtualMachineSizeType) String() string {
	return proto.EnumName(VirtualMachineSizeType_name, int32(x))
}

func (VirtualMachineSizeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{4}
}

type WinRMProtocolType int32

const (
	WinRMProtocolType_HTTP  WinRMProtocolType = 0
	WinRMProtocolType_HTTPS WinRMProtocolType = 1
)

var WinRMProtocolType_name = map[int32]string{
	0: "HTTP",
	1: "HTTPS",
}

var WinRMProtocolType_value = map[string]int32{
	"HTTP":  0,
	"HTTPS": 1,
}

func (x WinRMProtocolType) String() string {
	return proto.EnumName(WinRMProtocolType_name, int32(x))
}

func (WinRMProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{5}
}

type AssignmentType int32

const (
	AssignmentType_GpuDDA     AssignmentType = 0
	AssignmentType_GpuP       AssignmentType = 1
	AssignmentType_GpuPV      AssignmentType = 2
	AssignmentType_GpuDefault AssignmentType = 3
)

var AssignmentType_name = map[int32]string{
	0: "GpuDDA",
	1: "GpuP",
	2: "GpuPV",
	3: "GpuDefault",
}

var AssignmentType_value = map[string]int32{
	"GpuDDA":     0,
	"GpuP":       1,
	"GpuPV":      2,
	"GpuDefault": 3,
}

func (x AssignmentType) String() string {
	return proto.EnumName(AssignmentType_name, int32(x))
}

func (AssignmentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{6}
}

type PowerState int32

const (
	PowerState_Unknown  PowerState = 0
	PowerState_Running  PowerState = 1
	PowerState_Off      PowerState = 2
	PowerState_Paused   PowerState = 3
	PowerState_Critical PowerState = 4
	PowerState_Saved    PowerState = 5
)

var PowerState_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Off",
	3: "Paused",
	4: "Critical",
	5: "Saved",
}

var PowerState_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Off":      2,
	"Paused":   3,
	"Critical": 4,
	"Saved":    5,
}

func (x PowerState) String() string {
	return proto.EnumName(PowerState_name, int32(x))
}

func (PowerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{7}
}

type VirtualMachineOperation int32

const (
	VirtualMachineOperation_START              VirtualMachineOperation = 0
	VirtualMachineOperation_STOP               VirtualMachineOperation = 1
	VirtualMachineOperation_RESET              VirtualMachineOperation = 2
	VirtualMachineOperation_REPAIR_GUEST_AGENT VirtualMachineOperation = 3
	VirtualMachineOperation_PAUSE              VirtualMachineOperation = 4
	VirtualMachineOperation_SAVE               VirtualMachineOperation = 5
)

var VirtualMachineOperation_name = map[int32]string{
	0: "START",
	1: "STOP",
	2: "RESET",
	3: "REPAIR_GUEST_AGENT",
	4: "PAUSE",
	5: "SAVE",
}

var VirtualMachineOperation_value = map[string]int32{
	"START":              0,
	"STOP":               1,
	"RESET":              2,
	"REPAIR_GUEST_AGENT": 3,
	"PAUSE":              4,
	"SAVE":               5,
}

func (x VirtualMachineOperation) String() string {
	return proto.EnumName(VirtualMachineOperation_name, int32(x))
}

func (VirtualMachineOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{8}
}

type VirtualMachineRunCommandExecutionState int32

const (
	VirtualMachineRunCommandExecutionState_ExecutionState_UNKNOWN   VirtualMachineRunCommandExecutionState = 0
	VirtualMachineRunCommandExecutionState_ExecutionState_FAILED    VirtualMachineRunCommandExecutionState = 1
	VirtualMachineRunCommandExecutionState_ExecutionState_SUCCEEDED VirtualMachineRunCommandExecutionState = 2
	VirtualMachineRunCommandExecutionState_ExecutionState_PENDING   VirtualMachineRunCommandExecutionState = 3
	VirtualMachineRunCommandExecutionState_ExecutionState_REBOOTING VirtualMachineRunCommandExecutionState = 4
)

var VirtualMachineRunCommandExecutionState_name = map[int32]string{
	0: "ExecutionState_UNKNOWN",
	1: "ExecutionState_FAILED",
	2: "ExecutionState_SUCCEEDED",
	3: "ExecutionState_PENDING",
	4: "ExecutionState_REBOOTING",
}

var VirtualMachineRunCommandExecutionState_value = map[string]int32{
	"ExecutionState_UNKNOWN":   0,
	"ExecutionState_FAILED":    1,
	"ExecutionState_SUCCEEDED": 2,
	"ExecutionState_PENDING":   3,
	"ExecutionState_REBOOTING": 4,
}

func (x VirtualMachineRunCommandExecutionState) String() string {
	return proto.EnumName(VirtualMachineRunCommandExecutionState_name, int32(x))
}

func (VirtualMachineRunCommandExecutionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{9}
}

type ConfidentialVMHardwareType int32

const (
	ConfidentialVMHardwareType_HardwareTypeNone   ConfidentialVMHardwareType = 0
	ConfidentialVMHardwareType_HardwareTypeSEVSNP ConfidentialVMHardwareType = 1
)

var ConfidentialVMHardwareType_name = map[int32]string{
	0: "HardwareTypeNone",
	1: "HardwareTypeSEVSNP",
}

var ConfidentialVMHardwareType_value = map[string]int32{
	"HardwareTypeNone":   0,
	"HardwareTypeSEVSNP": 1,
}

func (x ConfidentialVMHardwareType) String() string {
	return proto.EnumName(ConfidentialVMHardwareType_name, int32(x))
}

func (ConfidentialVMHardwareType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{10}
}

type Architecture int32

const (
	Architecture_x86                Architecture = 0
	Architecture_MIPS               Architecture = 1
	Architecture_Alpha              Architecture = 2
	Architecture_PowerPC            Architecture = 3
	Architecture_ARM_Architecture   Architecture = 5
	Architecture_ia64               Architecture = 6
	Architecture_x64                Architecture = 9
	Architecture_ARM64_Architecture Architecture = 12
)

var Architecture_name = map[int32]string{
	0:  "x86",
	1:  "MIPS",
	2:  "Alpha",
	3:  "PowerPC",
	5:  "ARM_Architecture",
	6:  "ia64",
	9:  "x64",
	12: "ARM64_Architecture",
}

var Architecture_value = map[string]int32{
	"x86":                0,
	"MIPS":               1,
	"Alpha":              2,
	"PowerPC":            3,
	"ARM_Architecture":   5,
	"ia64":               6,
	"x64":                9,
	"ARM64_Architecture": 12,
}

func (x Architecture) String() string {
	return proto.EnumName(Architecture_name, int32(x))
}

func (Architecture) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{11}
}

type SecurityType int32

const (
	SecurityType_NOTCONFIGURED  SecurityType = 0
	SecurityType_TRUSTEDLAUNCH  SecurityType = 1
	SecurityType_CONFIDENTIALVM SecurityType = 2
)

var SecurityType_name = map[int32]string{
	0: "NOTCONFIGURED",
	1: "TRUSTEDLAUNCH",
	2: "CONFIDENTIALVM",
}

var SecurityType_value = map[string]int32{
	"NOTCONFIGURED":  0,
	"TRUSTEDLAUNCH":  1,
	"CONFIDENTIALVM": 2,
}

func (x SecurityType) String() string {
	return proto.EnumName(SecurityType_name, int32(x))
}

func (SecurityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{12}
}

type SecurityEncryptionTypes int32

const (
	SecurityEncryptionTypes_SecurityEncryptionNone SecurityEncryptionTypes = 0
	SecurityEncryptionTypes_NonPersistedTPM        SecurityEncryptionTypes = 1
)

var SecurityEncryptionTypes_name = map[int32]string{
	0: "SecurityEncryptionNone",
	1: "NonPersistedTPM",
}

var SecurityEncryptionTypes_value = map[string]int32{
	"SecurityEncryptionNone": 0,
	"NonPersistedTPM":        1,
}

func (x SecurityEncryptionTypes) String() string {
	return proto.EnumName(SecurityEncryptionTypes_name, int32(x))
}

func (SecurityEncryptionTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{13}
}

type InstanceViewStatus_StatusLevelType int32

const (
	InstanceViewStatus_Unknown InstanceViewStatus_StatusLevelType = 0
	InstanceViewStatus_Info    InstanceViewStatus_StatusLevelType = 1
	InstanceViewStatus_Warning InstanceViewStatus_StatusLevelType = 2
	InstanceViewStatus_Error   InstanceViewStatus_StatusLevelType = 3
)

var InstanceViewStatus_StatusLevelType_name = map[int32]string{
	0: "Unknown",
	1: "Info",
	2: "Warning",
	3: "Error",
}

var InstanceViewStatus_StatusLevelType_value = map[string]int32{
	"Unknown": 0,
	"Info":    1,
	"Warning": 2,
	"Error":   3,
}

func (x InstanceViewStatus_StatusLevelType) String() string {
	return proto.EnumName(InstanceViewStatus_StatusLevelType_name, int32(x))
}

func (InstanceViewStatus_StatusLevelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{9, 0}
}

type WinRMListener struct {
	Protocol             WinRMProtocolType `protobuf:"varint,1,opt,name=Protocol,proto3,enum=moc.WinRMProtocolType" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WinRMListener) Reset()         { *m = WinRMListener{} }
func (m *WinRMListener) String() string { return proto.CompactTextString(m) }
func (*WinRMListener) ProtoMessage()    {}
func (*WinRMListener) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{0}
}

func (m *WinRMListener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinRMListener.Unmarshal(m, b)
}
func (m *WinRMListener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinRMListener.Marshal(b, m, deterministic)
}
func (m *WinRMListener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinRMListener.Merge(m, src)
}
func (m *WinRMListener) XXX_Size() int {
	return xxx_messageInfo_WinRMListener.Size(m)
}
func (m *WinRMListener) XXX_DiscardUnknown() {
	xxx_messageInfo_WinRMListener.DiscardUnknown(m)
}

var xxx_messageInfo_WinRMListener proto.InternalMessageInfo

func (m *WinRMListener) GetProtocol() WinRMProtocolType {
	if m != nil {
		return m.Protocol
	}
	return WinRMProtocolType_HTTP
}

type WinRMConfiguration struct {
	Listeners            []*WinRMListener `protobuf:"bytes,1,rep,name=Listeners,proto3" json:"Listeners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WinRMConfiguration) Reset()         { *m = WinRMConfiguration{} }
func (m *WinRMConfiguration) String() string { return proto.CompactTextString(m) }
func (*WinRMConfiguration) ProtoMessage()    {}
func (*WinRMConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{1}
}

func (m *WinRMConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinRMConfiguration.Unmarshal(m, b)
}
func (m *WinRMConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinRMConfiguration.Marshal(b, m, deterministic)
}
func (m *WinRMConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinRMConfiguration.Merge(m, src)
}
func (m *WinRMConfiguration) XXX_Size() int {
	return xxx_messageInfo_WinRMConfiguration.Size(m)
}
func (m *WinRMConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_WinRMConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_WinRMConfiguration proto.InternalMessageInfo

func (m *WinRMConfiguration) GetListeners() []*WinRMListener {
	if m != nil {
		return m.Listeners
	}
	return nil
}

type VirtualMachineGPU struct {
	Assignment           AssignmentType `protobuf:"varint,1,opt,name=assignment,proto3,enum=moc.AssignmentType" json:"assignment,omitempty"`
	PartitionSizeMB      uint64         `protobuf:"varint,2,opt,name=partitionSizeMB,proto3" json:"partitionSizeMB,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VirtualMachineGPU) Reset()         { *m = VirtualMachineGPU{} }
func (m *VirtualMachineGPU) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineGPU) ProtoMessage()    {}
func (*VirtualMachineGPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{2}
}

func (m *VirtualMachineGPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineGPU.Unmarshal(m, b)
}
func (m *VirtualMachineGPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineGPU.Marshal(b, m, deterministic)
}
func (m *VirtualMachineGPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineGPU.Merge(m, src)
}
func (m *VirtualMachineGPU) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineGPU.Size(m)
}
func (m *VirtualMachineGPU) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineGPU.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineGPU proto.InternalMessageInfo

func (m *VirtualMachineGPU) GetAssignment() AssignmentType {
	if m != nil {
		return m.Assignment
	}
	return AssignmentType_GpuDDA
}

func (m *VirtualMachineGPU) GetPartitionSizeMB() uint64 {
	if m != nil {
		return m.PartitionSizeMB
	}
	return 0
}

func (m *VirtualMachineGPU) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VirtualMachineCustomSize struct {
	CpuCount             int32    `protobuf:"varint,1,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	MemoryMB             int32    `protobuf:"varint,2,opt,name=memoryMB,proto3" json:"memoryMB,omitempty"`
	GpuCount             int32    `protobuf:"varint,3,opt,name=gpuCount,proto3" json:"gpuCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualMachineCustomSize) Reset()         { *m = VirtualMachineCustomSize{} }
func (m *VirtualMachineCustomSize) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineCustomSize) ProtoMessage()    {}
func (*VirtualMachineCustomSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{3}
}

func (m *VirtualMachineCustomSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineCustomSize.Unmarshal(m, b)
}
func (m *VirtualMachineCustomSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineCustomSize.Marshal(b, m, deterministic)
}
func (m *VirtualMachineCustomSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineCustomSize.Merge(m, src)
}
func (m *VirtualMachineCustomSize) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineCustomSize.Size(m)
}
func (m *VirtualMachineCustomSize) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineCustomSize.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineCustomSize proto.InternalMessageInfo

func (m *VirtualMachineCustomSize) GetCpuCount() int32 {
	if m != nil {
		return m.CpuCount
	}
	return 0
}

func (m *VirtualMachineCustomSize) GetMemoryMB() int32 {
	if m != nil {
		return m.MemoryMB
	}
	return 0
}

func (m *VirtualMachineCustomSize) GetGpuCount() int32 {
	if m != nil {
		return m.GpuCount
	}
	return 0
}

type DynamicMemoryConfiguration struct {
	MaximumMemoryMB      uint64   `protobuf:"varint,1,opt,name=maximumMemoryMB,proto3" json:"maximumMemoryMB,omitempty"`
	MinimumMemoryMB      uint64   `protobuf:"varint,2,opt,name=minimumMemoryMB,proto3" json:"minimumMemoryMB,omitempty"`
	TargetMemoryBuffer   uint32   `protobuf:"varint,3,opt,name=targetMemoryBuffer,proto3" json:"targetMemoryBuffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamicMemoryConfiguration) Reset()         { *m = DynamicMemoryConfiguration{} }
func (m *DynamicMemoryConfiguration) String() string { return proto.CompactTextString(m) }
func (*DynamicMemoryConfiguration) ProtoMessage()    {}
func (*DynamicMemoryConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{4}
}

func (m *DynamicMemoryConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicMemoryConfiguration.Unmarshal(m, b)
}
func (m *DynamicMemoryConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicMemoryConfiguration.Marshal(b, m, deterministic)
}
func (m *DynamicMemoryConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicMemoryConfiguration.Merge(m, src)
}
func (m *DynamicMemoryConfiguration) XXX_Size() int {
	return xxx_messageInfo_DynamicMemoryConfiguration.Size(m)
}
func (m *DynamicMemoryConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicMemoryConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicMemoryConfiguration proto.InternalMessageInfo

func (m *DynamicMemoryConfiguration) GetMaximumMemoryMB() uint64 {
	if m != nil {
		return m.MaximumMemoryMB
	}
	return 0
}

func (m *DynamicMemoryConfiguration) GetMinimumMemoryMB() uint64 {
	if m != nil {
		return m.MinimumMemoryMB
	}
	return 0
}

func (m *DynamicMemoryConfiguration) GetTargetMemoryBuffer() uint32 {
	if m != nil {
		return m.TargetMemoryBuffer
	}
	return 0
}

type VirtualMachineRunCommandInputParameter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualMachineRunCommandInputParameter) Reset() {
	*m = VirtualMachineRunCommandInputParameter{}
}
func (m *VirtualMachineRunCommandInputParameter) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandInputParameter) ProtoMessage()    {}
func (*VirtualMachineRunCommandInputParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{5}
}

func (m *VirtualMachineRunCommandInputParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandInputParameter.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandInputParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandInputParameter.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandInputParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandInputParameter.Merge(m, src)
}
func (m *VirtualMachineRunCommandInputParameter) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandInputParameter.Size(m)
}
func (m *VirtualMachineRunCommandInputParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandInputParameter.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandInputParameter proto.InternalMessageInfo

func (m *VirtualMachineRunCommandInputParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachineRunCommandInputParameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type VirtualMachineRunCommandScriptSource struct {
	Script               string   `protobuf:"bytes,1,opt,name=Script,proto3" json:"Script,omitempty"`
	ScriptURI            string   `protobuf:"bytes,2,opt,name=ScriptURI,proto3" json:"ScriptURI,omitempty"`
	CommandID            string   `protobuf:"bytes,3,opt,name=CommandID,proto3" json:"CommandID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualMachineRunCommandScriptSource) Reset()         { *m = VirtualMachineRunCommandScriptSource{} }
func (m *VirtualMachineRunCommandScriptSource) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandScriptSource) ProtoMessage()    {}
func (*VirtualMachineRunCommandScriptSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{6}
}

func (m *VirtualMachineRunCommandScriptSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandScriptSource.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandScriptSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandScriptSource.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandScriptSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandScriptSource.Merge(m, src)
}
func (m *VirtualMachineRunCommandScriptSource) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandScriptSource.Size(m)
}
func (m *VirtualMachineRunCommandScriptSource) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandScriptSource.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandScriptSource proto.InternalMessageInfo

func (m *VirtualMachineRunCommandScriptSource) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *VirtualMachineRunCommandScriptSource) GetScriptURI() string {
	if m != nil {
		return m.ScriptURI
	}
	return ""
}

func (m *VirtualMachineRunCommandScriptSource) GetCommandID() string {
	if m != nil {
		return m.CommandID
	}
	return ""
}

type VirtualMachineRunCommandInstanceView struct {
	ExecutionState       VirtualMachineRunCommandExecutionState `protobuf:"varint,1,opt,name=ExecutionState,proto3,enum=moc.VirtualMachineRunCommandExecutionState" json:"ExecutionState,omitempty"`
	ExitCode             int32                                  `protobuf:"varint,2,opt,name=ExitCode,proto3" json:"ExitCode,omitempty"`
	Output               string                                 `protobuf:"bytes,3,opt,name=Output,proto3" json:"Output,omitempty"`
	Error                string                                 `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *VirtualMachineRunCommandInstanceView) Reset()         { *m = VirtualMachineRunCommandInstanceView{} }
func (m *VirtualMachineRunCommandInstanceView) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandInstanceView) ProtoMessage()    {}
func (*VirtualMachineRunCommandInstanceView) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{7}
}

func (m *VirtualMachineRunCommandInstanceView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandInstanceView.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandInstanceView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandInstanceView.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandInstanceView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandInstanceView.Merge(m, src)
}
func (m *VirtualMachineRunCommandInstanceView) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandInstanceView.Size(m)
}
func (m *VirtualMachineRunCommandInstanceView) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandInstanceView.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandInstanceView proto.InternalMessageInfo

func (m *VirtualMachineRunCommandInstanceView) GetExecutionState() VirtualMachineRunCommandExecutionState {
	if m != nil {
		return m.ExecutionState
	}
	return VirtualMachineRunCommandExecutionState_ExecutionState_UNKNOWN
}

func (m *VirtualMachineRunCommandInstanceView) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *VirtualMachineRunCommandInstanceView) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *VirtualMachineRunCommandInstanceView) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// describes the the capabilities of this node in terms of what type of VM can be created
// In the future when CVM comes, another bool will be added to check hardware capability.
type VirtualMachineCapabilities struct {
	IsolatedVmCapable                bool                       `protobuf:"varint,1,opt,name=IsolatedVmCapable,proto3" json:"IsolatedVmCapable,omitempty"`
	ConfidentialVMHardwareCapability ConfidentialVMHardwareType `protobuf:"varint,2,opt,name=ConfidentialVMHardwareCapability,proto3,enum=moc.ConfidentialVMHardwareType" json:"ConfidentialVMHardwareCapability,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                   `json:"-"`
	XXX_unrecognized                 []byte                     `json:"-"`
	XXX_sizecache                    int32                      `json:"-"`
}

func (m *VirtualMachineCapabilities) Reset()         { *m = VirtualMachineCapabilities{} }
func (m *VirtualMachineCapabilities) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineCapabilities) ProtoMessage()    {}
func (*VirtualMachineCapabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{8}
}

func (m *VirtualMachineCapabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineCapabilities.Unmarshal(m, b)
}
func (m *VirtualMachineCapabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineCapabilities.Marshal(b, m, deterministic)
}
func (m *VirtualMachineCapabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineCapabilities.Merge(m, src)
}
func (m *VirtualMachineCapabilities) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineCapabilities.Size(m)
}
func (m *VirtualMachineCapabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineCapabilities.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineCapabilities proto.InternalMessageInfo

func (m *VirtualMachineCapabilities) GetIsolatedVmCapable() bool {
	if m != nil {
		return m.IsolatedVmCapable
	}
	return false
}

func (m *VirtualMachineCapabilities) GetConfidentialVMHardwareCapability() ConfidentialVMHardwareType {
	if m != nil {
		return m.ConfidentialVMHardwareCapability
	}
	return ConfidentialVMHardwareType_HardwareTypeNone
}

type InstanceViewStatus struct {
	Code                 string                             `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Level                InstanceViewStatus_StatusLevelType `protobuf:"varint,2,opt,name=level,proto3,enum=moc.InstanceViewStatus_StatusLevelType" json:"level,omitempty"`
	DisplayStatus        string                             `protobuf:"bytes,3,opt,name=displayStatus,proto3" json:"displayStatus,omitempty"`
	Message              string                             `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Time                 string                             `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *InstanceViewStatus) Reset()         { *m = InstanceViewStatus{} }
func (m *InstanceViewStatus) String() string { return proto.CompactTextString(m) }
func (*InstanceViewStatus) ProtoMessage()    {}
func (*InstanceViewStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{9}
}

func (m *InstanceViewStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceViewStatus.Unmarshal(m, b)
}
func (m *InstanceViewStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceViewStatus.Marshal(b, m, deterministic)
}
func (m *InstanceViewStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceViewStatus.Merge(m, src)
}
func (m *InstanceViewStatus) XXX_Size() int {
	return xxx_messageInfo_InstanceViewStatus.Size(m)
}
func (m *InstanceViewStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceViewStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceViewStatus proto.InternalMessageInfo

func (m *InstanceViewStatus) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InstanceViewStatus) GetLevel() InstanceViewStatus_StatusLevelType {
	if m != nil {
		return m.Level
	}
	return InstanceViewStatus_Unknown
}

func (m *InstanceViewStatus) GetDisplayStatus() string {
	if m != nil {
		return m.DisplayStatus
	}
	return ""
}

func (m *InstanceViewStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InstanceViewStatus) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type VirtualMachineAgentInstanceView struct {
	VmAgentVersion       string                `protobuf:"bytes,1,opt,name=vmAgentVersion,proto3" json:"vmAgentVersion,omitempty"`
	Statuses             []*InstanceViewStatus `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VirtualMachineAgentInstanceView) Reset()         { *m = VirtualMachineAgentInstanceView{} }
func (m *VirtualMachineAgentInstanceView) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineAgentInstanceView) ProtoMessage()    {}
func (*VirtualMachineAgentInstanceView) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{10}
}

func (m *VirtualMachineAgentInstanceView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineAgentInstanceView.Unmarshal(m, b)
}
func (m *VirtualMachineAgentInstanceView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineAgentInstanceView.Marshal(b, m, deterministic)
}
func (m *VirtualMachineAgentInstanceView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineAgentInstanceView.Merge(m, src)
}
func (m *VirtualMachineAgentInstanceView) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineAgentInstanceView.Size(m)
}
func (m *VirtualMachineAgentInstanceView) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineAgentInstanceView.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineAgentInstanceView proto.InternalMessageInfo

func (m *VirtualMachineAgentInstanceView) GetVmAgentVersion() string {
	if m != nil {
		return m.VmAgentVersion
	}
	return ""
}

func (m *VirtualMachineAgentInstanceView) GetStatuses() []*InstanceViewStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type GuestAgentConfiguration struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuestAgentConfiguration) Reset()         { *m = GuestAgentConfiguration{} }
func (m *GuestAgentConfiguration) String() string { return proto.CompactTextString(m) }
func (*GuestAgentConfiguration) ProtoMessage()    {}
func (*GuestAgentConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{11}
}

func (m *GuestAgentConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuestAgentConfiguration.Unmarshal(m, b)
}
func (m *GuestAgentConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuestAgentConfiguration.Marshal(b, m, deterministic)
}
func (m *GuestAgentConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuestAgentConfiguration.Merge(m, src)
}
func (m *GuestAgentConfiguration) XXX_Size() int {
	return xxx_messageInfo_GuestAgentConfiguration.Size(m)
}
func (m *GuestAgentConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GuestAgentConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GuestAgentConfiguration proto.InternalMessageInfo

func (m *GuestAgentConfiguration) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type VMDiskSecurityProfile struct {
	SecurityEncryptionType SecurityEncryptionTypes `protobuf:"varint,1,opt,name=securityEncryptionType,proto3,enum=moc.SecurityEncryptionTypes" json:"securityEncryptionType,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *VMDiskSecurityProfile) Reset()         { *m = VMDiskSecurityProfile{} }
func (m *VMDiskSecurityProfile) String() string { return proto.CompactTextString(m) }
func (*VMDiskSecurityProfile) ProtoMessage()    {}
func (*VMDiskSecurityProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{12}
}

func (m *VMDiskSecurityProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMDiskSecurityProfile.Unmarshal(m, b)
}
func (m *VMDiskSecurityProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMDiskSecurityProfile.Marshal(b, m, deterministic)
}
func (m *VMDiskSecurityProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMDiskSecurityProfile.Merge(m, src)
}
func (m *VMDiskSecurityProfile) XXX_Size() int {
	return xxx_messageInfo_VMDiskSecurityProfile.Size(m)
}
func (m *VMDiskSecurityProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_VMDiskSecurityProfile.DiscardUnknown(m)
}

var xxx_messageInfo_VMDiskSecurityProfile proto.InternalMessageInfo

func (m *VMDiskSecurityProfile) GetSecurityEncryptionType() SecurityEncryptionTypes {
	if m != nil {
		return m.SecurityEncryptionType
	}
	return SecurityEncryptionTypes_SecurityEncryptionNone
}

type VirtualMachineManagedDiskParameters struct {
	SecurityProfile      *VMDiskSecurityProfile `protobuf:"bytes,1,opt,name=securityProfile,proto3" json:"securityProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VirtualMachineManagedDiskParameters) Reset()         { *m = VirtualMachineManagedDiskParameters{} }
func (m *VirtualMachineManagedDiskParameters) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineManagedDiskParameters) ProtoMessage()    {}
func (*VirtualMachineManagedDiskParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{13}
}

func (m *VirtualMachineManagedDiskParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineManagedDiskParameters.Unmarshal(m, b)
}
func (m *VirtualMachineManagedDiskParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineManagedDiskParameters.Marshal(b, m, deterministic)
}
func (m *VirtualMachineManagedDiskParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineManagedDiskParameters.Merge(m, src)
}
func (m *VirtualMachineManagedDiskParameters) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineManagedDiskParameters.Size(m)
}
func (m *VirtualMachineManagedDiskParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineManagedDiskParameters.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineManagedDiskParameters proto.InternalMessageInfo

func (m *VirtualMachineManagedDiskParameters) GetSecurityProfile() *VMDiskSecurityProfile {
	if m != nil {
		return m.SecurityProfile
	}
	return nil
}

type ProxyConfiguration struct {
	HttpProxy            string   `protobuf:"bytes,1,opt,name=httpProxy,proto3" json:"httpProxy,omitempty"`
	HttpsProxy           string   `protobuf:"bytes,2,opt,name=httpsProxy,proto3" json:"httpsProxy,omitempty"`
	NoProxy              []string `protobuf:"bytes,3,rep,name=noProxy,proto3" json:"noProxy,omitempty"`
	TrustedCa            string   `protobuf:"bytes,4,opt,name=trustedCa,proto3" json:"trustedCa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfiguration) Reset()         { *m = ProxyConfiguration{} }
func (m *ProxyConfiguration) String() string { return proto.CompactTextString(m) }
func (*ProxyConfiguration) ProtoMessage()    {}
func (*ProxyConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d1a061f6c82445b, []int{14}
}

func (m *ProxyConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfiguration.Unmarshal(m, b)
}
func (m *ProxyConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfiguration.Marshal(b, m, deterministic)
}
func (m *ProxyConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfiguration.Merge(m, src)
}
func (m *ProxyConfiguration) XXX_Size() int {
	return xxx_messageInfo_ProxyConfiguration.Size(m)
}
func (m *ProxyConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfiguration proto.InternalMessageInfo

func (m *ProxyConfiguration) GetHttpProxy() string {
	if m != nil {
		return m.HttpProxy
	}
	return ""
}

func (m *ProxyConfiguration) GetHttpsProxy() string {
	if m != nil {
		return m.HttpsProxy
	}
	return ""
}

func (m *ProxyConfiguration) GetNoProxy() []string {
	if m != nil {
		return m.NoProxy
	}
	return nil
}

func (m *ProxyConfiguration) GetTrustedCa() string {
	if m != nil {
		return m.TrustedCa
	}
	return ""
}

var E_Sensitivecompute = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "moc.sensitivecompute",
	Tag:           "varint,50002,opt,name=sensitivecompute",
	Filename:      "moc_common_computecommon.proto",
}

var E_Sensitivejson = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "moc.sensitivejson",
	Tag:           "varint,50003,opt,name=sensitivejson",
	Filename:      "moc_common_computecommon.proto",
}

func init() {
	proto.RegisterEnum("moc.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("moc.ProcessorType", ProcessorType_name, ProcessorType_value)
	proto.RegisterEnum("moc.OperatingSystemBootstrapEngine", OperatingSystemBootstrapEngine_name, OperatingSystemBootstrapEngine_value)
	proto.RegisterEnum("moc.OperatingSystemType", OperatingSystemType_name, OperatingSystemType_value)
	proto.RegisterEnum("moc.VirtualMachineSizeType", VirtualMachineSizeType_name, VirtualMachineSizeType_value)
	proto.RegisterEnum("moc.WinRMProtocolType", WinRMProtocolType_name, WinRMProtocolType_value)
	proto.RegisterEnum("moc.AssignmentType", AssignmentType_name, AssignmentType_value)
	proto.RegisterEnum("moc.PowerState", PowerState_name, PowerState_value)
	proto.RegisterEnum("moc.VirtualMachineOperation", VirtualMachineOperation_name, VirtualMachineOperation_value)
	proto.RegisterEnum("moc.VirtualMachineRunCommandExecutionState", VirtualMachineRunCommandExecutionState_name, VirtualMachineRunCommandExecutionState_value)
	proto.RegisterEnum("moc.ConfidentialVMHardwareType", ConfidentialVMHardwareType_name, ConfidentialVMHardwareType_value)
	proto.RegisterEnum("moc.Architecture", Architecture_name, Architecture_value)
	proto.RegisterEnum("moc.SecurityType", SecurityType_name, SecurityType_value)
	proto.RegisterEnum("moc.SecurityEncryptionTypes", SecurityEncryptionTypes_name, SecurityEncryptionTypes_value)
	proto.RegisterEnum("moc.InstanceViewStatus_StatusLevelType", InstanceViewStatus_StatusLevelType_name, InstanceViewStatus_StatusLevelType_value)
	proto.RegisterType((*WinRMListener)(nil), "moc.WinRMListener")
	proto.RegisterType((*WinRMConfiguration)(nil), "moc.WinRMConfiguration")
	proto.RegisterType((*VirtualMachineGPU)(nil), "moc.VirtualMachineGPU")
	proto.RegisterType((*VirtualMachineCustomSize)(nil), "moc.VirtualMachineCustomSize")
	proto.RegisterType((*DynamicMemoryConfiguration)(nil), "moc.DynamicMemoryConfiguration")
	proto.RegisterType((*VirtualMachineRunCommandInputParameter)(nil), "moc.VirtualMachineRunCommandInputParameter")
	proto.RegisterType((*VirtualMachineRunCommandScriptSource)(nil), "moc.VirtualMachineRunCommandScriptSource")
	proto.RegisterType((*VirtualMachineRunCommandInstanceView)(nil), "moc.VirtualMachineRunCommandInstanceView")
	proto.RegisterType((*VirtualMachineCapabilities)(nil), "moc.VirtualMachineCapabilities")
	proto.RegisterType((*InstanceViewStatus)(nil), "moc.InstanceViewStatus")
	proto.RegisterType((*VirtualMachineAgentInstanceView)(nil), "moc.VirtualMachineAgentInstanceView")
	proto.RegisterType((*GuestAgentConfiguration)(nil), "moc.GuestAgentConfiguration")
	proto.RegisterType((*VMDiskSecurityProfile)(nil), "moc.VMDiskSecurityProfile")
	proto.RegisterType((*VirtualMachineManagedDiskParameters)(nil), "moc.VirtualMachineManagedDiskParameters")
	proto.RegisterType((*ProxyConfiguration)(nil), "moc.ProxyConfiguration")
	proto.RegisterExtension(E_Sensitivecompute)
	proto.RegisterExtension(E_Sensitivejson)
}

func init() { proto.RegisterFile("moc_common_computecommon.proto", fileDescriptor_7d1a061f6c82445b) }

var fileDescriptor_7d1a061f6c82445b = []byte{
	// 1991 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x98, 0x4b, 0x73, 0xdb, 0xc6,
	0x1d, 0xc0, 0x0d, 0x3e, 0xf4, 0xf8, 0xeb, 0xb5, 0x5a, 0xd9, 0x12, 0xa3, 0x3a, 0xb6, 0x4a, 0x3b,
	0x8e, 0xca, 0x24, 0x12, 0x5f, 0xe1, 0x70, 0x32, 0xd3, 0x99, 0x52, 0x24, 0x24, 0xd3, 0x12, 0x41,
	0x0e, 0x40, 0x52, 0x69, 0x2f, 0x2c, 0x0c, 0x2e, 0x69, 0xd4, 0xc4, 0x2e, 0x06, 0x58, 0xc8, 0x52,
	0x0e, 0x9d, 0x9e, 0x72, 0xee, 0xb1, 0x87, 0x1e, 0x7a, 0xec, 0x17, 0xe8, 0xe4, 0x13, 0xf4, 0x0b,
	0xb4, 0x9f, 0xa7, 0x33, 0x9d, 0x5d, 0x80, 0x94, 0x00, 0x49, 0xc9, 0x89, 0xbb, 0xbf, 0xff, 0x13,
	0xff, 0xfd, 0x63, 0x77, 0x09, 0x78, 0xe1, 0x30, 0x6b, 0x64, 0x31, 0xc7, 0x61, 0x54, 0xfc, 0xb8,
	0x01, 0x27, 0xe1, 0xec, 0xc8, 0xf5, 0x18, 0x67, 0x38, 0xed, 0x30, 0x6b, 0xff, 0x60, 0xca, 0xd8,
	0x74, 0x46, 0x8e, 0x25, 0x7a, 0x1f, 0x4c, 0x8e, 0xc7, 0xc4, 0xb7, 0x3c, 0xdb, 0xe5, 0xcc, 0x0b,
	0xd5, 0xf2, 0x4d, 0xd8, 0xb8, 0xb4, 0xa9, 0xde, 0xb9, 0xb0, 0x7d, 0x4e, 0x28, 0xf1, 0x70, 0x19,
	0x56, 0x7a, 0x42, 0x62, 0xb1, 0x59, 0x4e, 0x39, 0x50, 0x0e, 0x37, 0xcb, 0xbb, 0x47, 0x0e, 0xb3,
	0x8e, 0xa4, 0xd6, 0x5c, 0xd2, 0xbf, 0x71, 0x89, 0xbe, 0xd0, 0xcb, 0x9f, 0x02, 0x96, 0xe2, 0x26,
	0xa3, 0x13, 0x7b, 0x1a, 0x78, 0x26, 0xb7, 0x19, 0xc5, 0x45, 0x58, 0x9d, 0x7b, 0xf5, 0x73, 0xca,
	0x41, 0xfa, 0x70, 0xad, 0x8c, 0x6f, 0x5d, 0xcd, 0x45, 0xfa, 0xad, 0x52, 0xfe, 0x47, 0x05, 0xb6,
	0x87, 0xb6, 0xc7, 0x03, 0x73, 0xd6, 0x31, 0xad, 0x0f, 0x36, 0x25, 0x67, 0xbd, 0x01, 0xae, 0x00,
	0x98, 0xbe, 0x6f, 0x4f, 0xa9, 0x43, 0x28, 0x8f, 0x72, 0xda, 0x91, 0x8e, 0x1a, 0x0b, 0x2c, 0x13,
	0xba, 0xa3, 0x86, 0x0f, 0x61, 0xcb, 0x35, 0x3d, 0x6e, 0x8b, 0x4c, 0x0c, 0xfb, 0x07, 0xd2, 0x39,
	0xc9, 0xa5, 0x0e, 0x94, 0xc3, 0x8c, 0x9e, 0xc4, 0x18, 0x43, 0x86, 0x9a, 0x0e, 0xc9, 0xa5, 0x0f,
	0x94, 0xc3, 0x55, 0x5d, 0x8e, 0xf3, 0x1c, 0x72, 0xf1, 0x3c, 0x9a, 0x81, 0xcf, 0x99, 0x23, 0x2c,
	0xf0, 0x3e, 0xac, 0x58, 0x6e, 0xd0, 0x64, 0x41, 0x94, 0x4c, 0x56, 0x5f, 0xcc, 0x85, 0xcc, 0x21,
	0x0e, 0xf3, 0x6e, 0xa2, 0x70, 0x59, 0x7d, 0x31, 0x17, 0xb2, 0xe9, 0xdc, 0x2e, 0x1d, 0xca, 0xe6,
	0xf3, 0x77, 0x99, 0x95, 0x0c, 0xca, 0xe6, 0xff, 0xa1, 0xc0, 0x7e, 0xeb, 0x86, 0x9a, 0x8e, 0x6d,
	0x75, 0xa4, 0x55, 0xbc, 0x9e, 0x87, 0xb0, 0xe5, 0x98, 0xd7, 0xb6, 0x13, 0x38, 0x9d, 0x79, 0x0c,
	0x25, 0x7c, 0xa4, 0x04, 0x96, 0x9a, 0x36, 0x8d, 0x69, 0x46, 0x0f, 0x9f, 0xc0, 0xf8, 0x08, 0x30,
	0x37, 0xbd, 0x29, 0xe1, 0x21, 0x39, 0x09, 0x26, 0x13, 0xe2, 0xc9, 0xf4, 0x36, 0xf4, 0x07, 0x24,
	0xf9, 0xef, 0xe1, 0x4d, 0xbc, 0x30, 0x7a, 0x40, 0x9b, 0xcc, 0x71, 0x4c, 0x3a, 0x6e, 0x53, 0x37,
	0xe0, 0x3d, 0xd3, 0x33, 0x1d, 0xc2, 0x89, 0x27, 0xca, 0xaa, 0x89, 0xb2, 0x2a, 0x61, 0x59, 0xc5,
	0x18, 0xef, 0x43, 0x76, 0x68, 0xce, 0x02, 0x22, 0xb3, 0x59, 0x3d, 0xc9, 0xfc, 0xed, 0x5f, 0x39,
	0x45, 0x0f, 0x51, 0xfe, 0x2f, 0x0a, 0xbc, 0x7e, 0xcc, 0xb5, 0x21, 0x7b, 0xd6, 0x60, 0x81, 0x67,
	0x11, 0xfc, 0x1c, 0x96, 0xc2, 0x79, 0xe8, 0xfa, 0x24, 0xf3, 0x57, 0xe1, 0x25, 0x62, 0xf8, 0x39,
	0xac, 0x86, 0xa3, 0x81, 0xde, 0x0e, 0xc3, 0xe8, 0xb7, 0x40, 0x48, 0xe7, 0xd9, 0xb6, 0xa2, 0x05,
	0xbf, 0x05, 0xf9, 0x7f, 0xff, 0x4c, 0x0a, 0x6d, 0xea, 0x73, 0x93, 0x5a, 0x64, 0x68, 0x93, 0x4f,
	0xd8, 0x80, 0x4d, 0xf5, 0x9a, 0x58, 0x81, 0xec, 0x22, 0x6e, 0x72, 0x12, 0x75, 0xe5, 0x57, 0xb2,
	0x2b, 0x1f, 0x73, 0x11, 0x37, 0xd1, 0x13, 0x2e, 0x44, 0x7f, 0xa8, 0xd7, 0x36, 0x6f, 0xb2, 0x31,
	0x99, 0xf7, 0xce, 0x7c, 0x8e, 0x77, 0x61, 0xa9, 0x1b, 0x70, 0x37, 0xe0, 0x51, 0xd2, 0xd1, 0x0c,
	0x3f, 0x85, 0xac, 0xea, 0x79, 0xcc, 0xcb, 0x65, 0x24, 0x0e, 0x27, 0xf9, 0x9f, 0x14, 0xd8, 0x4f,
	0xb4, 0xaf, 0xe9, 0x9a, 0xef, 0xed, 0x99, 0xcd, 0x6d, 0xe2, 0xe3, 0xaf, 0x61, 0xbb, 0xed, 0xb3,
	0x99, 0xc9, 0xc9, 0x78, 0xe8, 0x48, 0xc9, 0x2c, 0x7c, 0x80, 0x15, 0xfd, 0xbe, 0x00, 0x7f, 0x84,
	0x03, 0xd9, 0x86, 0x63, 0x42, 0xb9, 0x6d, 0xce, 0x86, 0x9d, 0xb7, 0xa6, 0x37, 0xfe, 0x64, 0x7a,
	0xb7, 0x3e, 0x6f, 0x64, 0xba, 0x9b, 0xe5, 0x97, 0xf2, 0xe9, 0x1f, 0x56, 0x96, 0xef, 0xe7, 0x2f,
	0x3a, 0xca, 0xff, 0x4f, 0x01, 0x7c, 0xb7, 0xd2, 0xa2, 0x32, 0x81, 0x2f, 0x7a, 0xc9, 0x12, 0x65,
	0x89, 0x7a, 0x49, 0x8c, 0xf1, 0x6f, 0x21, 0x3b, 0x23, 0x57, 0x64, 0x16, 0x05, 0xff, 0x52, 0x06,
	0xbf, 0x6f, 0x7b, 0x14, 0xfe, 0x5c, 0x08, 0x55, 0x99, 0x44, 0x68, 0x85, 0x5f, 0xc3, 0xc6, 0xd8,
	0xf6, 0xdd, 0x99, 0x79, 0x13, 0x2a, 0x44, 0x85, 0x8d, 0x43, 0x9c, 0x83, 0x65, 0x87, 0xf8, 0xbe,
	0x39, 0x25, 0x51, 0x85, 0xe7, 0x53, 0x91, 0x12, 0xb7, 0x1d, 0x92, 0xcb, 0x86, 0x29, 0x89, 0x71,
	0xfe, 0x77, 0xb0, 0x95, 0x88, 0x86, 0xd7, 0x60, 0x79, 0x40, 0x3f, 0x52, 0xf6, 0x89, 0xa2, 0x27,
	0x78, 0x05, 0x32, 0x6d, 0x3a, 0x61, 0x48, 0x11, 0xf8, 0xd2, 0xf4, 0xa8, 0x4d, 0xa7, 0x28, 0x85,
	0x57, 0xa3, 0x45, 0x44, 0xe9, 0xfc, 0x9f, 0xe1, 0x65, 0x7c, 0xe1, 0x1a, 0x53, 0x42, 0x79, 0xac,
	0xf7, 0xde, 0xc0, 0xe6, 0x95, 0x23, 0xf1, 0x90, 0x78, 0xbe, 0xcd, 0x68, 0x54, 0x95, 0x04, 0xc5,
	0x15, 0x58, 0xf1, 0x65, 0x32, 0xc4, 0xcf, 0xa5, 0xe4, 0xe6, 0xbb, 0xf7, 0x48, 0x89, 0xf4, 0x85,
	0x62, 0xbe, 0x02, 0x7b, 0x67, 0x01, 0xf1, 0xb9, 0xf4, 0x14, 0xdf, 0x7d, 0x72, 0xb0, 0x4c, 0xa8,
	0xe8, 0x88, 0x71, 0xd4, 0x2b, 0xf3, 0x69, 0xde, 0x81, 0x67, 0xc3, 0x4e, 0xcb, 0xf6, 0x3f, 0x1a,
	0xc4, 0x0a, 0x3c, 0x9b, 0xdf, 0xf4, 0x3c, 0x36, 0xb1, 0x67, 0x04, 0xf7, 0x61, 0xd7, 0x8f, 0x90,
	0x4a, 0x2d, 0xef, 0xc6, 0x15, 0x8e, 0x44, 0x59, 0xa2, 0xd7, 0xe5, 0xb9, 0x4c, 0xc8, 0x78, 0x50,
	0xc5, 0xd7, 0x1f, 0xb1, 0xcd, 0x7f, 0x84, 0x57, 0xf1, 0x1a, 0x75, 0x4c, 0x6a, 0x4e, 0xc9, 0x58,
	0x64, 0xb0, 0xd8, 0x7e, 0x7c, 0xdc, 0x82, 0x2d, 0x3f, 0x9e, 0x8f, 0x8c, 0xba, 0x56, 0xde, 0x0f,
	0x5f, 0xd2, 0x87, 0x32, 0xd6, 0x93, 0x26, 0xf9, 0xbf, 0x2b, 0x80, 0x7b, 0x1e, 0xbb, 0x4e, 0x6c,
	0xc5, 0x79, 0x58, 0xfd, 0xc0, 0xb9, 0x2b, 0x25, 0xb1, 0x6d, 0xe8, 0x16, 0xe3, 0xd7, 0x00, 0x62,
	0xe2, 0x87, 0x4a, 0xa9, 0x3b, 0x4a, 0x77, 0xb8, 0x28, 0x2b, 0x65, 0xa1, 0x4a, 0xfa, 0x20, 0x2d,
	0x3a, 0x2c, 0x9a, 0x8a, 0x18, 0xdc, 0x0b, 0x7c, 0x4e, 0xc6, 0x4d, 0x33, 0xec, 0xbe, 0x79, 0x8c,
	0x05, 0x2e, 0xbc, 0x80, 0x95, 0x81, 0x4f, 0x3c, 0xd9, 0x6a, 0x2b, 0x90, 0xd1, 0xbb, 0xdd, 0x7e,
	0xd8, 0x67, 0x03, 0x43, 0xd5, 0x91, 0x52, 0xf8, 0x3d, 0x6c, 0xf4, 0x3c, 0x66, 0x11, 0xdf, 0x67,
	0x0b, 0x25, 0x8d, 0x51, 0x82, 0x9e, 0x88, 0xae, 0x6b, 0x53, 0x4e, 0x66, 0x61, 0x37, 0xca, 0x61,
	0xad, 0x8a, 0x52, 0x78, 0x19, 0xd2, 0x8d, 0x4e, 0x0b, 0xa5, 0x85, 0x42, 0xa3, 0xd3, 0xaa, 0x55,
	0x51, 0x46, 0x32, 0xbd, 0x83, 0xb2, 0x92, 0xe9, 0x9d, 0x5a, 0x15, 0x2d, 0x15, 0xde, 0xc1, 0x8b,
	0xae, 0x4b, 0x44, 0x3d, 0xe8, 0xd4, 0xb8, 0xf1, 0x39, 0x71, 0x4e, 0x18, 0xe3, 0x3e, 0xf7, 0x4c,
	0x57, 0xa5, 0x53, 0x9b, 0x12, 0xbc, 0x09, 0xd0, 0xbc, 0xe8, 0x0e, 0x5a, 0xa3, 0xb6, 0xd6, 0x16,
	0x69, 0xe5, 0xe0, 0xe9, 0x65, 0x5b, 0x6b, 0x75, 0x2f, 0x8d, 0x51, 0x43, 0x33, 0x2e, 0x55, 0x7d,
	0x74, 0xda, 0xbe, 0x50, 0x0d, 0xa4, 0x14, 0xbe, 0x81, 0x9d, 0x84, 0xaf, 0xf9, 0xcb, 0x13, 0x19,
	0x84, 0xf9, 0x5e, 0xb4, 0xb5, 0xc1, 0xf7, 0x48, 0x29, 0xfc, 0x73, 0x15, 0x76, 0xe3, 0x2d, 0x20,
	0x0e, 0xe6, 0xb9, 0x49, 0x8b, 0x4c, 0xcc, 0x60, 0xc6, 0xd1, 0x13, 0x8c, 0x61, 0xd3, 0xe0, 0x26,
	0x1d, 0x9b, 0xde, 0x78, 0xd4, 0x28, 0x8f, 0xae, 0xca, 0x28, 0x15, 0x67, 0x55, 0xc1, 0xd2, 0x78,
	0x47, 0xbe, 0xb7, 0x21, 0x6b, 0x95, 0xfd, 0xd1, 0x55, 0x05, 0x65, 0xe2, 0xb0, 0x2a, 0x61, 0x36,
	0x0e, 0xeb, 0x12, 0x2e, 0xe1, 0xa7, 0x80, 0x6e, 0x61, 0xa9, 0x26, 0xe9, 0x72, 0x9c, 0x56, 0x42,
	0xaf, 0x2b, 0x71, 0x07, 0x86, 0xcc, 0x69, 0x35, 0x01, 0x2b, 0x02, 0x42, 0x02, 0xca, 0x4c, 0xd7,
	0x12, 0xf0, 0x5b, 0x01, 0xd7, 0xe3, 0x91, 0x8c, 0x92, 0xb4, 0xdf, 0x88, 0xa9, 0x9e, 0xd7, 0x8d,
	0xd1, 0x55, 0x09, 0x6d, 0xc6, 0x54, 0xcf, 0xeb, 0x22, 0x7e, 0x09, 0x6d, 0x25, 0x69, 0x45, 0x50,
	0x94, 0xa4, 0x55, 0x41, 0xb7, 0x31, 0x82, 0xf5, 0x05, 0xd5, 0xce, 0x6b, 0x08, 0xe3, 0x6d, 0xd8,
	0xb8, 0x43, 0x4a, 0x65, 0xb4, 0x13, 0x57, 0x1a, 0xd6, 0xd0, 0xd3, 0xb8, 0xd2, 0xb0, 0x54, 0x46,
	0xcf, 0x92, 0xfe, 0xbf, 0x15, 0xfe, 0x77, 0xf1, 0x1e, 0xec, 0x24, 0x0a, 0x34, 0x7a, 0xdb, 0xd3,
	0xd0, 0x5e, 0x42, 0x50, 0x99, 0x0b, 0x72, 0x09, 0x41, 0x75, 0x2e, 0xf8, 0x2c, 0x16, 0xe0, 0xb4,
	0xec, 0x4b, 0xba, 0x1f, 0xa7, 0xd5, 0x90, 0xfe, 0x2a, 0x4e, 0xeb, 0x21, 0x7d, 0x8e, 0x9f, 0xc1,
	0xf6, 0x2d, 0x15, 0x2b, 0x2b, 0xf0, 0xe7, 0xb1, 0xd2, 0x6a, 0xcd, 0xea, 0xa8, 0x51, 0x46, 0x2f,
	0x12, 0xb0, 0x2e, 0xe0, 0xcb, 0x98, 0x5b, 0xad, 0x59, 0xaa, 0x09, 0x7a, 0x90, 0xa0, 0x95, 0xb2,
	0xa0, 0xbf, 0x4e, 0xd0, 0xea, 0xa8, 0x51, 0x29, 0xa2, 0x7c, 0x82, 0xd6, 0x25, 0x7d, 0x15, 0x4b,
	0x2c, 0xf4, 0x5b, 0x29, 0xa2, 0xd7, 0x09, 0x2c, 0x1c, 0x57, 0x8a, 0xe8, 0x0b, 0xf1, 0xe2, 0xc5,
	0x3d, 0x97, 0x8a, 0xc5, 0x51, 0xb5, 0x88, 0xde, 0x24, 0x24, 0xf5, 0x85, 0xe4, 0x4b, 0xfc, 0x19,
	0x3c, 0x4b, 0x44, 0x88, 0x44, 0x87, 0x09, 0x91, 0x88, 0x12, 0x89, 0x7e, 0xf3, 0x70, 0xa4, 0x7a,
	0x11, 0x15, 0x1e, 0x8e, 0x54, 0x2f, 0xa2, 0xaf, 0x1e, 0x89, 0x54, 0x2f, 0xa2, 0xaf, 0x1f, 0x89,
	0x54, 0x2f, 0xa2, 0x6f, 0xee, 0x57, 0xab, 0x54, 0x43, 0x47, 0xf7, 0xab, 0x55, 0xaa, 0xa1, 0xe3,
	0x07, 0xaa, 0x55, 0xaa, 0xa1, 0xe2, 0x03, 0xd5, 0x2a, 0xd5, 0x50, 0x09, 0x6f, 0xc0, 0x6a, 0x78,
	0xdb, 0x17, 0xcb, 0x32, 0xba, 0x33, 0xd5, 0xce, 0xd1, 0x1f, 0x45, 0x6b, 0x47, 0xd3, 0x33, 0x37,
	0x70, 0xaf, 0x90, 0x89, 0x01, 0x96, 0x42, 0x82, 0xde, 0xe3, 0x2d, 0x58, 0x1b, 0x50, 0x3f, 0x70,
	0x5d, 0xe6, 0x71, 0x32, 0x46, 0x56, 0xe1, 0x10, 0xb6, 0xef, 0xfd, 0x71, 0x12, 0x9b, 0xf0, 0xdb,
	0x7e, 0xbf, 0x17, 0x6e, 0x6a, 0x62, 0x24, 0xf6, 0xc0, 0x06, 0x6c, 0xc6, 0xff, 0xce, 0x08, 0xc7,
	0x67, 0x6e, 0xd0, 0x6a, 0x35, 0xc2, 0x2d, 0xfd, 0xcc, 0x0d, 0x7a, 0x48, 0x11, 0x26, 0x62, 0x34,
	0x44, 0x29, 0xb1, 0xc1, 0x0a, 0x85, 0x68, 0xbf, 0x4b, 0x17, 0xfa, 0x00, 0x3d, 0xf6, 0x89, 0x78,
	0xe1, 0x7d, 0x32, 0x76, 0xf5, 0x58, 0x83, 0x65, 0x3d, 0xa0, 0xf2, 0xc2, 0xa1, 0x88, 0xed, 0xbc,
	0x3b, 0x99, 0xa0, 0x94, 0x88, 0xd0, 0x33, 0x03, 0x9f, 0x8c, 0x51, 0x1a, 0xaf, 0xc3, 0x4a, 0xd3,
	0xb3, 0xb9, 0x6d, 0x99, 0x33, 0x94, 0x11, 0x51, 0x0c, 0xf3, 0x8a, 0x8c, 0x51, 0xb6, 0x30, 0x81,
	0xbd, 0xf8, 0x66, 0x1b, 0x6d, 0xd5, 0x8c, 0x4a, 0xad, 0x7e, 0x43, 0x8f, 0xce, 0x1c, 0xa3, 0xdf,
	0x8d, 0x12, 0xd4, 0x55, 0x43, 0xed, 0xa3, 0x14, 0xde, 0x05, 0xac, 0xab, 0xbd, 0x46, 0x5b, 0x1f,
	0x9d, 0x0d, 0x54, 0xa3, 0x3f, 0x6a, 0x9c, 0xa9, 0x5a, 0x3f, 0x3c, 0x5a, 0x7a, 0x8d, 0x81, 0xa1,
	0xa2, 0x8c, 0xb4, 0x6b, 0x0c, 0x55, 0x94, 0x2d, 0xfc, 0xa4, 0x3c, 0xfe, 0xdf, 0xe2, 0xde, 0x55,
	0x79, 0x37, 0x4e, 0x46, 0x03, 0xed, 0x5c, 0xeb, 0x5e, 0x6a, 0xe8, 0x89, 0xe8, 0x99, 0x84, 0xec,
	0xb4, 0xd1, 0xbe, 0x50, 0x5b, 0x48, 0xc1, 0xcf, 0x21, 0x97, 0x10, 0x19, 0x83, 0x66, 0x53, 0x55,
	0x5b, 0x6a, 0x0b, 0xa5, 0x1e, 0x70, 0xda, 0x53, 0xb5, 0x56, 0x5b, 0x3b, 0x43, 0xe9, 0x07, 0x2c,
	0x75, 0xf5, 0xa4, 0xdb, 0xed, 0x0b, 0x69, 0xa6, 0xf0, 0x0e, 0xf6, 0x1f, 0xbf, 0xf5, 0x8a, 0x9e,
	0xbc, 0x3b, 0x8f, 0x8e, 0xdf, 0x5d, 0xc0, 0x77, 0xa9, 0xa1, 0x0e, 0x0d, 0xad, 0x87, 0x94, 0xc2,
	0x0f, 0xb0, 0xde, 0xf0, 0xac, 0x0f, 0x36, 0x27, 0x16, 0x0f, 0x3c, 0x22, 0xd6, 0xea, 0xba, 0x5e,
	0x0b, 0x0b, 0xdc, 0x69, 0x8b, 0x4e, 0x91, 0x87, 0xf0, 0xcc, 0xfd, 0x60, 0xa2, 0x94, 0x58, 0x56,
	0xb9, 0xe2, 0xbd, 0x26, 0x4a, 0x8b, 0x40, 0x0d, 0xbd, 0x33, 0xba, 0x6b, 0x8e, 0xb2, 0xc2, 0xce,
	0x36, 0xc5, 0x89, 0x2d, 0x5d, 0xd5, 0xaa, 0x68, 0x55, 0xc4, 0x96, 0xa7, 0x78, 0x5c, 0x75, 0xbd,
	0xf0, 0x16, 0xd6, 0xe7, 0x17, 0x22, 0x99, 0xf9, 0x36, 0x6c, 0x68, 0xdd, 0x7e, 0xb3, 0xab, 0x9d,
	0xb6, 0xcf, 0x06, 0xba, 0xda, 0x42, 0x4f, 0x04, 0xea, 0xeb, 0x03, 0xa3, 0xaf, 0xb6, 0x2e, 0x1a,
	0x03, 0xad, 0xf9, 0x16, 0x29, 0xe2, 0x44, 0x95, 0x2a, 0x2d, 0x55, 0xeb, 0xb7, 0x1b, 0x17, 0xc3,
	0x0e, 0x4a, 0x15, 0xde, 0xc1, 0xde, 0x23, 0xd7, 0x3a, 0x51, 0xe6, 0xfb, 0xa2, 0xa8, 0x28, 0x3b,
	0xb0, 0xa5, 0x31, 0xda, 0x13, 0x37, 0x58, 0x71, 0xc1, 0xe9, 0xf7, 0x3a, 0x48, 0xf9, 0xee, 0x1c,
	0x90, 0x4f, 0xa8, 0x6f, 0x73, 0xfb, 0x8a, 0x44, 0x1f, 0x3a, 0xf0, 0xe7, 0x47, 0xe1, 0x87, 0x8d,
	0xa3, 0xf9, 0x87, 0x8d, 0xa3, 0x53, 0x9b, 0xcc, 0xc6, 0x5d, 0xe9, 0xcc, 0xcf, 0xfd, 0xe7, 0xc7,
	0xb4, 0xbc, 0xa2, 0xde, 0x33, 0xfc, 0x4e, 0x85, 0x8d, 0x05, 0xfb, 0x93, 0xcf, 0xe8, 0x2f, 0x79,
	0xfa, 0x6f, 0xe4, 0x29, 0x6e, 0x75, 0xf2, 0xc5, 0x1f, 0x5e, 0x4d, 0x6d, 0xfe, 0x21, 0x78, 0x7f,
	0x64, 0x31, 0xe7, 0xd8, 0xb1, 0x2d, 0x8f, 0xf9, 0x6c, 0xc2, 0x8f, 0x1d, 0x66, 0x1d, 0x7b, 0xae,
	0x75, 0x1c, 0x7e, 0x89, 0x79, 0xbf, 0x24, 0x9d, 0x56, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x32,
	0xec, 0x01, 0x2b, 0xac, 0x11, 0x00, 0x00,
}
