// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_cloudagent_loadbalancer.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadBalancerRequest struct {
	LoadBalancers        []*LoadBalancer  `protobuf:"bytes,1,rep,name=LoadBalancers,proto3" json:"LoadBalancers,omitempty"`
	OperationType        common.Operation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoadBalancerRequest) Reset()         { *m = LoadBalancerRequest{} }
func (m *LoadBalancerRequest) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerRequest) ProtoMessage()    {}
func (*LoadBalancerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{0}
}

func (m *LoadBalancerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerRequest.Unmarshal(m, b)
}
func (m *LoadBalancerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerRequest.Marshal(b, m, deterministic)
}
func (m *LoadBalancerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerRequest.Merge(m, src)
}
func (m *LoadBalancerRequest) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerRequest.Size(m)
}
func (m *LoadBalancerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerRequest proto.InternalMessageInfo

func (m *LoadBalancerRequest) GetLoadBalancers() []*LoadBalancer {
	if m != nil {
		return m.LoadBalancers
	}
	return nil
}

func (m *LoadBalancerRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type LoadBalancerResponse struct {
	LoadBalancers        []*LoadBalancer     `protobuf:"bytes,1,rep,name=LoadBalancers,proto3" json:"LoadBalancers,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoadBalancerResponse) Reset()         { *m = LoadBalancerResponse{} }
func (m *LoadBalancerResponse) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerResponse) ProtoMessage()    {}
func (*LoadBalancerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{1}
}

func (m *LoadBalancerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerResponse.Unmarshal(m, b)
}
func (m *LoadBalancerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerResponse.Marshal(b, m, deterministic)
}
func (m *LoadBalancerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerResponse.Merge(m, src)
}
func (m *LoadBalancerResponse) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerResponse.Size(m)
}
func (m *LoadBalancerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerResponse proto.InternalMessageInfo

func (m *LoadBalancerResponse) GetLoadBalancers() []*LoadBalancer {
	if m != nil {
		return m.LoadBalancers
	}
	return nil
}

func (m *LoadBalancerResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *LoadBalancerResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoadBalancerPrecheckRequest struct {
	LoadBalancers        []*LoadBalancer `protobuf:"bytes,1,rep,name=LoadBalancers,proto3" json:"LoadBalancers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoadBalancerPrecheckRequest) Reset()         { *m = LoadBalancerPrecheckRequest{} }
func (m *LoadBalancerPrecheckRequest) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerPrecheckRequest) ProtoMessage()    {}
func (*LoadBalancerPrecheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{2}
}

func (m *LoadBalancerPrecheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerPrecheckRequest.Unmarshal(m, b)
}
func (m *LoadBalancerPrecheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerPrecheckRequest.Marshal(b, m, deterministic)
}
func (m *LoadBalancerPrecheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerPrecheckRequest.Merge(m, src)
}
func (m *LoadBalancerPrecheckRequest) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerPrecheckRequest.Size(m)
}
func (m *LoadBalancerPrecheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerPrecheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerPrecheckRequest proto.InternalMessageInfo

func (m *LoadBalancerPrecheckRequest) GetLoadBalancers() []*LoadBalancer {
	if m != nil {
		return m.LoadBalancers
	}
	return nil
}

type LoadBalancerPrecheckResponse struct {
	// The precheck result: true if the precheck criteria is passed; otherwise, false
	Result *wrappers.BoolValue `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	// The error message if the precheck is not passed; otherwise, empty string
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadBalancerPrecheckResponse) Reset()         { *m = LoadBalancerPrecheckResponse{} }
func (m *LoadBalancerPrecheckResponse) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerPrecheckResponse) ProtoMessage()    {}
func (*LoadBalancerPrecheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{3}
}

func (m *LoadBalancerPrecheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerPrecheckResponse.Unmarshal(m, b)
}
func (m *LoadBalancerPrecheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerPrecheckResponse.Marshal(b, m, deterministic)
}
func (m *LoadBalancerPrecheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerPrecheckResponse.Merge(m, src)
}
func (m *LoadBalancerPrecheckResponse) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerPrecheckResponse.Size(m)
}
func (m *LoadBalancerPrecheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerPrecheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerPrecheckResponse proto.InternalMessageInfo

func (m *LoadBalancerPrecheckResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *LoadBalancerPrecheckResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoadbalancerInboundNatRule struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FrontendPort         uint32          `protobuf:"varint,2,opt,name=frontendPort,proto3" json:"frontendPort,omitempty"`
	BackendPort          uint32          `protobuf:"varint,3,opt,name=backendPort,proto3" json:"backendPort,omitempty"`
	Protocol             common.Protocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=moc.Protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoadbalancerInboundNatRule) Reset()         { *m = LoadbalancerInboundNatRule{} }
func (m *LoadbalancerInboundNatRule) String() string { return proto.CompactTextString(m) }
func (*LoadbalancerInboundNatRule) ProtoMessage()    {}
func (*LoadbalancerInboundNatRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{4}
}

func (m *LoadbalancerInboundNatRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadbalancerInboundNatRule.Unmarshal(m, b)
}
func (m *LoadbalancerInboundNatRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadbalancerInboundNatRule.Marshal(b, m, deterministic)
}
func (m *LoadbalancerInboundNatRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadbalancerInboundNatRule.Merge(m, src)
}
func (m *LoadbalancerInboundNatRule) XXX_Size() int {
	return xxx_messageInfo_LoadbalancerInboundNatRule.Size(m)
}
func (m *LoadbalancerInboundNatRule) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadbalancerInboundNatRule.DiscardUnknown(m)
}

var xxx_messageInfo_LoadbalancerInboundNatRule proto.InternalMessageInfo

func (m *LoadbalancerInboundNatRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoadbalancerInboundNatRule) GetFrontendPort() uint32 {
	if m != nil {
		return m.FrontendPort
	}
	return 0
}

func (m *LoadbalancerInboundNatRule) GetBackendPort() uint32 {
	if m != nil {
		return m.BackendPort
	}
	return 0
}

func (m *LoadbalancerInboundNatRule) GetProtocol() common.Protocol {
	if m != nil {
		return m.Protocol
	}
	return common.Protocol_All
}

type LoadbalancerOutboundNatRule struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FrontendPort         uint32          `protobuf:"varint,2,opt,name=frontendPort,proto3" json:"frontendPort,omitempty"`
	BackendPort          uint32          `protobuf:"varint,3,opt,name=backendPort,proto3" json:"backendPort,omitempty"`
	Protocol             common.Protocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=moc.Protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoadbalancerOutboundNatRule) Reset()         { *m = LoadbalancerOutboundNatRule{} }
func (m *LoadbalancerOutboundNatRule) String() string { return proto.CompactTextString(m) }
func (*LoadbalancerOutboundNatRule) ProtoMessage()    {}
func (*LoadbalancerOutboundNatRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{5}
}

func (m *LoadbalancerOutboundNatRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadbalancerOutboundNatRule.Unmarshal(m, b)
}
func (m *LoadbalancerOutboundNatRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadbalancerOutboundNatRule.Marshal(b, m, deterministic)
}
func (m *LoadbalancerOutboundNatRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadbalancerOutboundNatRule.Merge(m, src)
}
func (m *LoadbalancerOutboundNatRule) XXX_Size() int {
	return xxx_messageInfo_LoadbalancerOutboundNatRule.Size(m)
}
func (m *LoadbalancerOutboundNatRule) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadbalancerOutboundNatRule.DiscardUnknown(m)
}

var xxx_messageInfo_LoadbalancerOutboundNatRule proto.InternalMessageInfo

func (m *LoadbalancerOutboundNatRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoadbalancerOutboundNatRule) GetFrontendPort() uint32 {
	if m != nil {
		return m.FrontendPort
	}
	return 0
}

func (m *LoadbalancerOutboundNatRule) GetBackendPort() uint32 {
	if m != nil {
		return m.BackendPort
	}
	return 0
}

func (m *LoadbalancerOutboundNatRule) GetProtocol() common.Protocol {
	if m != nil {
		return m.Protocol
	}
	return common.Protocol_All
}

type LoadBalancingRule struct {
	FrontendPort         uint32                 `protobuf:"varint,1,opt,name=frontendPort,proto3" json:"frontendPort,omitempty"`
	BackendPort          uint32                 `protobuf:"varint,2,opt,name=backendPort,proto3" json:"backendPort,omitempty"`
	Protocol             common.Protocol        `protobuf:"varint,3,opt,name=protocol,proto3,enum=moc.Protocol" json:"protocol,omitempty"`
	ProbeRef             *common.ProbeReference `protobuf:"bytes,4,opt,name=probeRef,proto3" json:"probeRef,omitempty"`
	Name                 string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LoadBalancingRule) Reset()         { *m = LoadBalancingRule{} }
func (m *LoadBalancingRule) String() string { return proto.CompactTextString(m) }
func (*LoadBalancingRule) ProtoMessage()    {}
func (*LoadBalancingRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{6}
}

func (m *LoadBalancingRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancingRule.Unmarshal(m, b)
}
func (m *LoadBalancingRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancingRule.Marshal(b, m, deterministic)
}
func (m *LoadBalancingRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancingRule.Merge(m, src)
}
func (m *LoadBalancingRule) XXX_Size() int {
	return xxx_messageInfo_LoadBalancingRule.Size(m)
}
func (m *LoadBalancingRule) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancingRule.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancingRule proto.InternalMessageInfo

func (m *LoadBalancingRule) GetFrontendPort() uint32 {
	if m != nil {
		return m.FrontendPort
	}
	return 0
}

func (m *LoadBalancingRule) GetBackendPort() uint32 {
	if m != nil {
		return m.BackendPort
	}
	return 0
}

func (m *LoadBalancingRule) GetProtocol() common.Protocol {
	if m != nil {
		return m.Protocol
	}
	return common.Protocol_All
}

func (m *LoadBalancingRule) GetProbeRef() *common.ProbeReference {
	if m != nil {
		return m.ProbeRef
	}
	return nil
}

func (m *LoadBalancingRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Probe struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IntervalInSeconds    uint32               `protobuf:"varint,2,opt,name=intervalInSeconds,proto3" json:"intervalInSeconds,omitempty"`
	NumberOfProbes       uint32               `protobuf:"varint,3,opt,name=numberOfProbes,proto3" json:"numberOfProbes,omitempty"`
	Protocol             common.Protocol      `protobuf:"varint,4,opt,name=protocol,proto3,enum=moc.Protocol" json:"protocol,omitempty"`
	Port                 uint32               `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Loadbalancingrules   []*LoadBalancingRule `protobuf:"bytes,6,rep,name=loadbalancingrules,proto3" json:"loadbalancingrules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Probe) Reset()         { *m = Probe{} }
func (m *Probe) String() string { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()    {}
func (*Probe) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{7}
}

func (m *Probe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Probe.Unmarshal(m, b)
}
func (m *Probe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Probe.Marshal(b, m, deterministic)
}
func (m *Probe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Probe.Merge(m, src)
}
func (m *Probe) XXX_Size() int {
	return xxx_messageInfo_Probe.Size(m)
}
func (m *Probe) XXX_DiscardUnknown() {
	xxx_messageInfo_Probe.DiscardUnknown(m)
}

var xxx_messageInfo_Probe proto.InternalMessageInfo

func (m *Probe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Probe) GetIntervalInSeconds() uint32 {
	if m != nil {
		return m.IntervalInSeconds
	}
	return 0
}

func (m *Probe) GetNumberOfProbes() uint32 {
	if m != nil {
		return m.NumberOfProbes
	}
	return 0
}

func (m *Probe) GetProtocol() common.Protocol {
	if m != nil {
		return m.Protocol
	}
	return common.Protocol_All
}

func (m *Probe) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Probe) GetLoadbalancingrules() []*LoadBalancingRule {
	if m != nil {
		return m.Loadbalancingrules
	}
	return nil
}

type FrontEndIpConfiguration struct {
	Name                 string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrivateIPAddress     string                           `protobuf:"bytes,2,opt,name=privateIPAddress,proto3" json:"privateIPAddress,omitempty"`
	AllocationMethod     common.IPAllocationMethod        `protobuf:"varint,3,opt,name=allocationMethod,proto3,enum=moc.IPAllocationMethod" json:"allocationMethod,omitempty"`
	SubnetRef            *common.SubnetReference          `protobuf:"bytes,4,opt,name=subnetRef,proto3" json:"subnetRef,omitempty"`
	PublicIPAddress      *common.PublicIPAddressReference `protobuf:"bytes,5,opt,name=publicIPAddress,proto3" json:"publicIPAddress,omitempty"`
	InboundNatRules      []*LoadbalancerInboundNatRule    `protobuf:"bytes,6,rep,name=inboundNatRules,proto3" json:"inboundNatRules,omitempty"`
	OutboundNatRules     []*LoadbalancerOutboundNatRule   `protobuf:"bytes,7,rep,name=outboundNatRules,proto3" json:"outboundNatRules,omitempty"`
	Loadbalancingrules   []*LoadBalancingRule             `protobuf:"bytes,8,rep,name=loadbalancingrules,proto3" json:"loadbalancingrules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *FrontEndIpConfiguration) Reset()         { *m = FrontEndIpConfiguration{} }
func (m *FrontEndIpConfiguration) String() string { return proto.CompactTextString(m) }
func (*FrontEndIpConfiguration) ProtoMessage()    {}
func (*FrontEndIpConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{8}
}

func (m *FrontEndIpConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEndIpConfiguration.Unmarshal(m, b)
}
func (m *FrontEndIpConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEndIpConfiguration.Marshal(b, m, deterministic)
}
func (m *FrontEndIpConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEndIpConfiguration.Merge(m, src)
}
func (m *FrontEndIpConfiguration) XXX_Size() int {
	return xxx_messageInfo_FrontEndIpConfiguration.Size(m)
}
func (m *FrontEndIpConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEndIpConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEndIpConfiguration proto.InternalMessageInfo

func (m *FrontEndIpConfiguration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FrontEndIpConfiguration) GetPrivateIPAddress() string {
	if m != nil {
		return m.PrivateIPAddress
	}
	return ""
}

func (m *FrontEndIpConfiguration) GetAllocationMethod() common.IPAllocationMethod {
	if m != nil {
		return m.AllocationMethod
	}
	return common.IPAllocationMethod_Invalid
}

func (m *FrontEndIpConfiguration) GetSubnetRef() *common.SubnetReference {
	if m != nil {
		return m.SubnetRef
	}
	return nil
}

func (m *FrontEndIpConfiguration) GetPublicIPAddress() *common.PublicIPAddressReference {
	if m != nil {
		return m.PublicIPAddress
	}
	return nil
}

func (m *FrontEndIpConfiguration) GetInboundNatRules() []*LoadbalancerInboundNatRule {
	if m != nil {
		return m.InboundNatRules
	}
	return nil
}

func (m *FrontEndIpConfiguration) GetOutboundNatRules() []*LoadbalancerOutboundNatRule {
	if m != nil {
		return m.OutboundNatRules
	}
	return nil
}

func (m *FrontEndIpConfiguration) GetLoadbalancingrules() []*LoadBalancingRule {
	if m != nil {
		return m.Loadbalancingrules
	}
	return nil
}

type LoadBalancer struct {
	Name                     string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                       string                         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FrontendIP               string                         `protobuf:"bytes,3,opt,name=frontendIP,proto3" json:"frontendIP,omitempty"`
	Backendpoolnames         []string                       `protobuf:"bytes,4,rep,name=backendpoolnames,proto3" json:"backendpoolnames,omitempty"`
	Networkid                string                         `protobuf:"bytes,5,opt,name=networkid,proto3" json:"networkid,omitempty"`
	Loadbalancingrules       []*LoadBalancingRule           `protobuf:"bytes,6,rep,name=loadbalancingrules,proto3" json:"loadbalancingrules,omitempty"`
	Nodefqdn                 string                         `protobuf:"bytes,7,opt,name=nodefqdn,proto3" json:"nodefqdn,omitempty"`
	GroupName                string                         `protobuf:"bytes,8,opt,name=groupName,proto3" json:"groupName,omitempty"`
	LocationName             string                         `protobuf:"bytes,9,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Status                   *common.Status                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Tags                     *common.Tags                   `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"`
	ReplicationCount         uint32                         `protobuf:"varint,12,opt,name=replicationCount,proto3" json:"replicationCount,omitempty"`
	InboundNatRules          []*LoadbalancerInboundNatRule  `protobuf:"bytes,13,rep,name=inboundNatRules,proto3" json:"inboundNatRules,omitempty"`
	OutboundNatRules         []*LoadbalancerOutboundNatRule `protobuf:"bytes,14,rep,name=outboundNatRules,proto3" json:"outboundNatRules,omitempty"`
	FrontendIpConfigurations []*FrontEndIpConfiguration     `protobuf:"bytes,15,rep,name=frontendIpConfigurations,proto3" json:"frontendIpConfigurations,omitempty"`
	Probes                   []*Probe                       `protobuf:"bytes,16,rep,name=probes,proto3" json:"probes,omitempty"`
	UseSDN                   string                         `protobuf:"bytes,17,opt,name=useSDN,proto3" json:"useSDN,omitempty"`
	ApiVersion               string                         `protobuf:"bytes,18,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                       `json:"-"`
	XXX_unrecognized         []byte                         `json:"-"`
	XXX_sizecache            int32                          `json:"-"`
}

func (m *LoadBalancer) Reset()         { *m = LoadBalancer{} }
func (m *LoadBalancer) String() string { return proto.CompactTextString(m) }
func (*LoadBalancer) ProtoMessage()    {}
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return fileDescriptor_7464476b31ac10f8, []int{9}
}

func (m *LoadBalancer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancer.Unmarshal(m, b)
}
func (m *LoadBalancer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancer.Marshal(b, m, deterministic)
}
func (m *LoadBalancer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancer.Merge(m, src)
}
func (m *LoadBalancer) XXX_Size() int {
	return xxx_messageInfo_LoadBalancer.Size(m)
}
func (m *LoadBalancer) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancer.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancer proto.InternalMessageInfo

func (m *LoadBalancer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoadBalancer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LoadBalancer) GetFrontendIP() string {
	if m != nil {
		return m.FrontendIP
	}
	return ""
}

func (m *LoadBalancer) GetBackendpoolnames() []string {
	if m != nil {
		return m.Backendpoolnames
	}
	return nil
}

func (m *LoadBalancer) GetNetworkid() string {
	if m != nil {
		return m.Networkid
	}
	return ""
}

func (m *LoadBalancer) GetLoadbalancingrules() []*LoadBalancingRule {
	if m != nil {
		return m.Loadbalancingrules
	}
	return nil
}

func (m *LoadBalancer) GetNodefqdn() string {
	if m != nil {
		return m.Nodefqdn
	}
	return ""
}

func (m *LoadBalancer) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *LoadBalancer) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *LoadBalancer) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoadBalancer) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *LoadBalancer) GetReplicationCount() uint32 {
	if m != nil {
		return m.ReplicationCount
	}
	return 0
}

func (m *LoadBalancer) GetInboundNatRules() []*LoadbalancerInboundNatRule {
	if m != nil {
		return m.InboundNatRules
	}
	return nil
}

func (m *LoadBalancer) GetOutboundNatRules() []*LoadbalancerOutboundNatRule {
	if m != nil {
		return m.OutboundNatRules
	}
	return nil
}

func (m *LoadBalancer) GetFrontendIpConfigurations() []*FrontEndIpConfiguration {
	if m != nil {
		return m.FrontendIpConfigurations
	}
	return nil
}

func (m *LoadBalancer) GetProbes() []*Probe {
	if m != nil {
		return m.Probes
	}
	return nil
}

func (m *LoadBalancer) GetUseSDN() string {
	if m != nil {
		return m.UseSDN
	}
	return ""
}

func (m *LoadBalancer) GetApiVersion() string {
	if m != nil {
		return m.ApiVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadBalancerRequest)(nil), "moc.cloudagent.network.LoadBalancerRequest")
	proto.RegisterType((*LoadBalancerResponse)(nil), "moc.cloudagent.network.LoadBalancerResponse")
	proto.RegisterType((*LoadBalancerPrecheckRequest)(nil), "moc.cloudagent.network.LoadBalancerPrecheckRequest")
	proto.RegisterType((*LoadBalancerPrecheckResponse)(nil), "moc.cloudagent.network.LoadBalancerPrecheckResponse")
	proto.RegisterType((*LoadbalancerInboundNatRule)(nil), "moc.cloudagent.network.LoadbalancerInboundNatRule")
	proto.RegisterType((*LoadbalancerOutboundNatRule)(nil), "moc.cloudagent.network.LoadbalancerOutboundNatRule")
	proto.RegisterType((*LoadBalancingRule)(nil), "moc.cloudagent.network.LoadBalancingRule")
	proto.RegisterType((*Probe)(nil), "moc.cloudagent.network.Probe")
	proto.RegisterType((*FrontEndIpConfiguration)(nil), "moc.cloudagent.network.FrontEndIpConfiguration")
	proto.RegisterType((*LoadBalancer)(nil), "moc.cloudagent.network.LoadBalancer")
}

func init() { proto.RegisterFile("moc_cloudagent_loadbalancer.proto", fileDescriptor_7464476b31ac10f8) }

var fileDescriptor_7464476b31ac10f8 = []byte{
	// 1005 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x9e, 0x1c, 0xc7, 0xb5, 0x8f, 0x63, 0x27, 0x61, 0x83, 0x46, 0xf0, 0x9a, 0xc0, 0xf3, 0x8a,
	0x21, 0xdd, 0x0a, 0x0b, 0x73, 0xba, 0x07, 0x48, 0xb2, 0x6e, 0xf0, 0xd0, 0x25, 0x06, 0x53, 0x14,
	0xd8, 0x30, 0x20, 0xd0, 0x0f, 0xad, 0x08, 0x96, 0x49, 0x95, 0xa4, 0x12, 0xec, 0x0d, 0x06, 0xec,
	0x01, 0x76, 0xbd, 0x5d, 0xef, 0xb6, 0x0f, 0xb1, 0x77, 0xd9, 0xdd, 0x5e, 0x60, 0x10, 0x45, 0x59,
	0x92, 0x7f, 0xd2, 0x04, 0x48, 0x80, 0x5e, 0xd9, 0xfa, 0xce, 0x39, 0x1f, 0x3f, 0x7d, 0x3c, 0x3c,
	0x22, 0x7c, 0x36, 0x65, 0xee, 0x85, 0x1b, 0xb2, 0xd8, 0xb3, 0x7d, 0x42, 0xe5, 0x45, 0xc8, 0x6c,
	0xcf, 0xb1, 0x43, 0x9b, 0xba, 0x84, 0xf7, 0x23, 0xce, 0x24, 0x43, 0x4f, 0xa6, 0xcc, 0xed, 0xe7,
	0x29, 0x7d, 0x4a, 0xe4, 0x35, 0xe3, 0x93, 0xce, 0xbe, 0xcf, 0x98, 0x1f, 0x12, 0x4b, 0x65, 0x39,
	0xf1, 0xd8, 0xba, 0xe6, 0x76, 0x14, 0x11, 0x2e, 0xd2, 0xba, 0xce, 0xae, 0xa2, 0x66, 0xd3, 0x29,
	0xa3, 0xfa, 0x47, 0x07, 0xf6, 0x0b, 0x01, 0x4d, 0x56, 0x8c, 0xf7, 0xfe, 0x30, 0xe0, 0xf1, 0x6b,
	0x66, 0x7b, 0xc7, 0x5a, 0x07, 0x26, 0xef, 0x62, 0x22, 0x24, 0xfa, 0x01, 0x5a, 0x45, 0x58, 0x98,
	0x46, 0x77, 0xed, 0xa0, 0x39, 0x78, 0xd6, 0x5f, 0x2e, 0xb0, 0x5f, 0xe2, 0x28, 0x97, 0xa2, 0x97,
	0xd0, 0x3a, 0x8b, 0x08, 0xb7, 0x65, 0xc0, 0xe8, 0x9b, 0x5f, 0x23, 0x62, 0x56, 0xba, 0xc6, 0x41,
	0x7b, 0xd0, 0x56, 0x5c, 0xb3, 0x08, 0x2e, 0x27, 0xf5, 0xfe, 0x36, 0x60, 0xa7, 0xac, 0x4c, 0x44,
	0x8c, 0x0a, 0x72, 0xaf, 0xd2, 0x06, 0x50, 0xc3, 0x44, 0xc4, 0xa1, 0x54, 0x9a, 0x9a, 0x83, 0x4e,
	0x3f, 0x35, 0xba, 0x9f, 0x19, 0xdd, 0x3f, 0x66, 0x2c, 0x7c, 0x6b, 0x87, 0x31, 0xc1, 0x3a, 0x13,
	0xed, 0xc0, 0xfa, 0x2b, 0xce, 0x19, 0x37, 0xd7, 0xba, 0xc6, 0x41, 0x03, 0xa7, 0x0f, 0xbd, 0x00,
	0x3e, 0x2d, 0x52, 0x8f, 0x38, 0x71, 0x2f, 0x89, 0x3b, 0x79, 0x00, 0x3f, 0x7b, 0x97, 0xf0, 0x74,
	0xf9, 0x52, 0xda, 0xa0, 0xfc, 0xa5, 0x8c, 0xbb, 0xbf, 0x54, 0xa5, 0xf8, 0x52, 0x7f, 0x1a, 0xd0,
	0x79, 0x5d, 0xe8, 0xd2, 0x21, 0x75, 0x58, 0x4c, 0xbd, 0x53, 0x5b, 0xe2, 0x38, 0x24, 0x08, 0x41,
	0x95, 0xda, 0x53, 0xa2, 0x96, 0x69, 0x60, 0xf5, 0x1f, 0xf5, 0x60, 0x63, 0xcc, 0x19, 0x95, 0x84,
	0x7a, 0x23, 0xc6, 0x53, 0x5f, 0x5b, 0xb8, 0x84, 0xa1, 0x2e, 0x34, 0x1d, 0xdb, 0x9d, 0x64, 0x29,
	0x6b, 0x2a, 0xa5, 0x08, 0xa1, 0xe7, 0x50, 0x57, 0x62, 0x5d, 0x16, 0x9a, 0x55, 0xd5, 0x2d, 0x2d,
	0xe5, 0xd4, 0x48, 0x83, 0x78, 0x16, 0xee, 0xfd, 0x65, 0xa4, 0xce, 0x67, 0x1a, 0xcf, 0x62, 0xf9,
	0xf1, 0x89, 0xfc, 0xc7, 0x80, 0xed, 0x7c, 0xcf, 0x02, 0xea, 0x2b, 0x69, 0xf3, 0x32, 0x8c, 0x0f,
	0xcb, 0xa8, 0xdc, 0x2c, 0x63, 0xed, 0x46, 0x19, 0xc8, 0x52, 0xa9, 0x0e, 0xc1, 0x64, 0xac, 0x14,
	0x37, 0x07, 0x8f, 0xb3, 0x54, 0x05, 0x12, 0x4e, 0xa8, 0x4b, 0xf0, 0x2c, 0x69, 0x66, 0xde, 0x7a,
	0x6e, 0x5e, 0xef, 0xf7, 0x0a, 0xac, 0xab, 0x82, 0xa5, 0xd6, 0xbe, 0x80, 0xed, 0x80, 0x4a, 0xc2,
	0xaf, 0xec, 0x70, 0x48, 0xcf, 0x89, 0xcb, 0xa8, 0x27, 0xb4, 0xea, 0xc5, 0x00, 0xfa, 0x02, 0xda,
	0x34, 0x9e, 0x3a, 0x84, 0x9f, 0x8d, 0x15, 0xa5, 0xd0, 0x3e, 0xcf, 0xa1, 0x77, 0xb0, 0x3a, 0x11,
	0x15, 0x25, 0x4e, 0xad, 0x2b, 0x22, 0xf5, 0x1f, 0xfd, 0x04, 0x28, 0x1f, 0xb6, 0x01, 0xf5, 0x79,
	0x1c, 0x12, 0x61, 0xd6, 0xd4, 0x11, 0x7c, 0xfe, 0xe1, 0x23, 0xa8, 0xf7, 0x0b, 0x2f, 0x21, 0xe9,
	0xbd, 0xaf, 0xc2, 0xee, 0x77, 0xc9, 0x86, 0xbd, 0xa2, 0xde, 0x30, 0x3a, 0x61, 0x74, 0x1c, 0xf8,
	0x71, 0x3a, 0xc6, 0x96, 0xfa, 0xf3, 0x25, 0x6c, 0x45, 0x3c, 0xb8, 0xb2, 0x25, 0x19, 0x8e, 0x8e,
	0x3c, 0x8f, 0x13, 0x21, 0xf4, 0x99, 0x5b, 0xc0, 0xd1, 0x09, 0x6c, 0xd9, 0x61, 0xc8, 0x5c, 0xc5,
	0xf6, 0x23, 0x91, 0x97, 0xcc, 0xd3, 0x3b, 0xbc, 0xab, 0x44, 0x0f, 0x47, 0x47, 0x73, 0x61, 0xbc,
	0x50, 0x80, 0x06, 0xd0, 0x10, 0xb1, 0x43, 0x89, 0xcc, 0x37, 0x7d, 0x47, 0x55, 0x9f, 0x67, 0xa8,
	0xde, 0xf5, 0x3c, 0x0d, 0x7d, 0x0f, 0x9b, 0x51, 0xec, 0x84, 0x81, 0x9b, 0x6b, 0x5c, 0x57, 0x95,
	0x7b, 0xa9, 0xeb, 0xe5, 0x58, 0x4e, 0x31, 0x5f, 0x85, 0x7e, 0x81, 0xcd, 0xa0, 0x34, 0x33, 0x32,
	0xd7, 0x07, 0x37, 0xb9, 0xbe, 0x7c, 0xdc, 0xe0, 0x79, 0x2a, 0x74, 0x01, 0x5b, 0xac, 0x7c, 0xda,
	0x85, 0xf9, 0x48, 0xd1, 0x1f, 0xde, 0x86, 0x7e, 0x6e, 0x52, 0xe0, 0x05, 0xb2, 0x15, 0x7d, 0x53,
	0xbf, 0x8f, 0xbe, 0xf9, 0xb7, 0x06, 0x1b, 0xc5, 0x29, 0xbe, 0xb4, 0x59, 0xda, 0x50, 0x09, 0x3c,
	0xdd, 0x1e, 0x95, 0xc0, 0x43, 0xcf, 0x00, 0xb2, 0xe1, 0x30, 0x1c, 0xa5, 0xdf, 0x9f, 0xe3, 0xea,
	0x6f, 0xef, 0x4d, 0x03, 0x17, 0xf0, 0xa4, 0xc5, 0xf4, 0x7c, 0x88, 0x18, 0x0b, 0x13, 0x22, 0x61,
	0x56, 0xbb, 0x6b, 0x49, 0x8b, 0xcd, 0xe3, 0xe8, 0x29, 0x34, 0xb4, 0xee, 0xc0, 0xd3, 0xa7, 0x3c,
	0x07, 0x1e, 0xf0, 0xdc, 0xa0, 0x2e, 0xd4, 0x29, 0xf3, 0xc8, 0xf8, 0x9d, 0x47, 0xcd, 0x47, 0x85,
	0x17, 0x99, 0xa1, 0x89, 0x34, 0x9f, 0xb3, 0x38, 0x3a, 0x4d, 0x5c, 0xa9, 0xa7, 0xd2, 0x66, 0x40,
	0x32, 0x3b, 0xb3, 0x46, 0x57, 0x09, 0x0d, 0x95, 0x50, 0xc2, 0xd0, 0xe7, 0x50, 0x13, 0xd2, 0x96,
	0xb1, 0x30, 0x41, 0x75, 0x6f, 0x33, 0xed, 0x7b, 0x05, 0x61, 0x1d, 0x42, 0x7b, 0x50, 0x95, 0xb6,
	0x2f, 0xcc, 0xa6, 0x4a, 0x69, 0xa8, 0x94, 0x37, 0xb6, 0x2f, 0xb0, 0x82, 0x13, 0x33, 0x39, 0x89,
	0xc2, 0x20, 0xa5, 0x3d, 0x61, 0x31, 0x95, 0xe6, 0x86, 0x1a, 0x2d, 0x0b, 0xf8, 0xb2, 0x6e, 0x6f,
	0x3d, 0x6c, 0xb7, 0xb7, 0xef, 0xb3, 0xdb, 0x27, 0x60, 0xce, 0xba, 0xa8, 0x3c, 0xc9, 0x84, 0xb9,
	0xa9, 0x16, 0xb2, 0x56, 0x2d, 0xb4, 0x62, 0x02, 0xe2, 0x95, 0x84, 0xe8, 0x1b, 0xa8, 0x45, 0xe9,
	0xc4, 0xdf, 0x52, 0xd4, 0x7b, 0xab, 0xa8, 0xd3, 0x6f, 0x93, 0x4e, 0x46, 0x4f, 0xa0, 0x16, 0x0b,
	0x72, 0xfe, 0xed, 0xa9, 0xb9, 0xad, 0x36, 0x5c, 0x3f, 0xa1, 0x7d, 0x00, 0x3b, 0x0a, 0xde, 0x12,
	0x2e, 0x02, 0x46, 0x4d, 0xa4, 0x62, 0x05, 0x64, 0xf0, 0x5f, 0xe9, 0x03, 0x4c, 0xf8, 0x51, 0xb2,
	0x06, 0x22, 0x50, 0x1b, 0xd2, 0x2b, 0x36, 0x21, 0xe8, 0xab, 0x5b, 0x5d, 0xc4, 0xd2, 0xcb, 0x5c,
	0xe7, 0xc5, 0xed, 0x92, 0xd3, 0xeb, 0x58, 0xef, 0x13, 0x74, 0x0d, 0xf5, 0xec, 0x92, 0x86, 0x0e,
	0x6f, 0x53, 0x3b, 0x77, 0x7b, 0xec, 0xbc, 0xbc, 0x5b, 0x51, 0xb6, 0xf0, 0xf1, 0xd7, 0x3f, 0x5b,
	0x7e, 0x20, 0x2f, 0x63, 0xa7, 0xef, 0xb2, 0xa9, 0x35, 0x0d, 0x5c, 0xce, 0x04, 0x1b, 0x4b, 0x6b,
	0xca, 0x5c, 0x8b, 0x47, 0xae, 0x95, 0x33, 0x5a, 0x9a, 0xd1, 0xa9, 0xa9, 0x0f, 0xe9, 0xe1, 0xff,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0xc7, 0xef, 0x38, 0xad, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoadBalancerAgentClient is the client API for LoadBalancerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoadBalancerAgentClient interface {
	Invoke(ctx context.Context, in *LoadBalancerRequest, opts ...grpc.CallOption) (*LoadBalancerResponse, error)
	// Prechecks whether the system is able to create specified load balancers (but does not actually create them).
	Precheck(ctx context.Context, in *LoadBalancerPrecheckRequest, opts ...grpc.CallOption) (*LoadBalancerPrecheckResponse, error)
}

type loadBalancerAgentClient struct {
	cc *grpc.ClientConn
}

func NewLoadBalancerAgentClient(cc *grpc.ClientConn) LoadBalancerAgentClient {
	return &loadBalancerAgentClient{cc}
}

func (c *loadBalancerAgentClient) Invoke(ctx context.Context, in *LoadBalancerRequest, opts ...grpc.CallOption) (*LoadBalancerResponse, error) {
	out := new(LoadBalancerResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.network.LoadBalancerAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadBalancerAgentClient) Precheck(ctx context.Context, in *LoadBalancerPrecheckRequest, opts ...grpc.CallOption) (*LoadBalancerPrecheckResponse, error) {
	out := new(LoadBalancerPrecheckResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.network.LoadBalancerAgent/Precheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadBalancerAgentServer is the server API for LoadBalancerAgent service.
type LoadBalancerAgentServer interface {
	Invoke(context.Context, *LoadBalancerRequest) (*LoadBalancerResponse, error)
	// Prechecks whether the system is able to create specified load balancers (but does not actually create them).
	Precheck(context.Context, *LoadBalancerPrecheckRequest) (*LoadBalancerPrecheckResponse, error)
}

// UnimplementedLoadBalancerAgentServer can be embedded to have forward compatible implementations.
type UnimplementedLoadBalancerAgentServer struct {
}

func (*UnimplementedLoadBalancerAgentServer) Invoke(ctx context.Context, req *LoadBalancerRequest) (*LoadBalancerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedLoadBalancerAgentServer) Precheck(ctx context.Context, req *LoadBalancerPrecheckRequest) (*LoadBalancerPrecheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Precheck not implemented")
}

func RegisterLoadBalancerAgentServer(s *grpc.Server, srv LoadBalancerAgentServer) {
	s.RegisterService(&_LoadBalancerAgent_serviceDesc, srv)
}

func _LoadBalancerAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadBalancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadBalancerAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.network.LoadBalancerAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadBalancerAgentServer).Invoke(ctx, req.(*LoadBalancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadBalancerAgent_Precheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadBalancerPrecheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadBalancerAgentServer).Precheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.network.LoadBalancerAgent/Precheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadBalancerAgentServer).Precheck(ctx, req.(*LoadBalancerPrecheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoadBalancerAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.cloudagent.network.LoadBalancerAgent",
	HandlerType: (*LoadBalancerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _LoadBalancerAgent_Invoke_Handler,
		},
		{
			MethodName: "Precheck",
			Handler:    _LoadBalancerAgent_Precheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_cloudagent_loadbalancer.proto",
}
