// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_nodeagent_virtualmachine.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VirtualMachineRequest struct {
	VirtualMachineSystems []*VirtualMachine `protobuf:"bytes,1,rep,name=VirtualMachineSystems,proto3" json:"VirtualMachineSystems,omitempty"`
	OperationType         common.Operation  `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *VirtualMachineRequest) Reset()         { *m = VirtualMachineRequest{} }
func (m *VirtualMachineRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRequest) ProtoMessage()    {}
func (*VirtualMachineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{0}
}

func (m *VirtualMachineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRequest.Unmarshal(m, b)
}
func (m *VirtualMachineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRequest.Merge(m, src)
}
func (m *VirtualMachineRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRequest.Size(m)
}
func (m *VirtualMachineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRequest proto.InternalMessageInfo

func (m *VirtualMachineRequest) GetVirtualMachineSystems() []*VirtualMachine {
	if m != nil {
		return m.VirtualMachineSystems
	}
	return nil
}

func (m *VirtualMachineRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type VirtualMachineResponse struct {
	VirtualMachineSystems []*VirtualMachine   `protobuf:"bytes,1,rep,name=VirtualMachineSystems,proto3" json:"VirtualMachineSystems,omitempty"`
	Result                *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                 string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}            `json:"-"`
	XXX_unrecognized      []byte              `json:"-"`
	XXX_sizecache         int32               `json:"-"`
}

func (m *VirtualMachineResponse) Reset()         { *m = VirtualMachineResponse{} }
func (m *VirtualMachineResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineResponse) ProtoMessage()    {}
func (*VirtualMachineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{1}
}

func (m *VirtualMachineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineResponse.Unmarshal(m, b)
}
func (m *VirtualMachineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineResponse.Merge(m, src)
}
func (m *VirtualMachineResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineResponse.Size(m)
}
func (m *VirtualMachineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineResponse proto.InternalMessageInfo

func (m *VirtualMachineResponse) GetVirtualMachineSystems() []*VirtualMachine {
	if m != nil {
		return m.VirtualMachineSystems
	}
	return nil
}

func (m *VirtualMachineResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *VirtualMachineResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SSHPublicKey struct {
	Keydata              string   `protobuf:"bytes,1,opt,name=keydata,proto3" json:"keydata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSHPublicKey) Reset()         { *m = SSHPublicKey{} }
func (m *SSHPublicKey) String() string { return proto.CompactTextString(m) }
func (*SSHPublicKey) ProtoMessage()    {}
func (*SSHPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{2}
}

func (m *SSHPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSHPublicKey.Unmarshal(m, b)
}
func (m *SSHPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSHPublicKey.Marshal(b, m, deterministic)
}
func (m *SSHPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSHPublicKey.Merge(m, src)
}
func (m *SSHPublicKey) XXX_Size() int {
	return xxx_messageInfo_SSHPublicKey.Size(m)
}
func (m *SSHPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SSHPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_SSHPublicKey proto.InternalMessageInfo

func (m *SSHPublicKey) GetKeydata() string {
	if m != nil {
		return m.Keydata
	}
	return ""
}

type Disk struct {
	// reference to the virtual hard disk managed by storage
	Diskname             string   `protobuf:"bytes,1,opt,name=diskname,proto3" json:"diskname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disk) Reset()         { *m = Disk{} }
func (m *Disk) String() string { return proto.CompactTextString(m) }
func (*Disk) ProtoMessage()    {}
func (*Disk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{3}
}

func (m *Disk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disk.Unmarshal(m, b)
}
func (m *Disk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disk.Marshal(b, m, deterministic)
}
func (m *Disk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disk.Merge(m, src)
}
func (m *Disk) XXX_Size() int {
	return xxx_messageInfo_Disk.Size(m)
}
func (m *Disk) XXX_DiscardUnknown() {
	xxx_messageInfo_Disk.DiscardUnknown(m)
}

var xxx_messageInfo_Disk proto.InternalMessageInfo

func (m *Disk) GetDiskname() string {
	if m != nil {
		return m.Diskname
	}
	return ""
}

type StorageConfiguration struct {
	Osdisk                *Disk    `protobuf:"bytes,1,opt,name=osdisk,proto3" json:"osdisk,omitempty"`
	Datadisks             []*Disk  `protobuf:"bytes,2,rep,name=datadisks,proto3" json:"datadisks,omitempty"`
	VmConfigContainerName string   `protobuf:"bytes,3,opt,name=vmConfigContainerName,proto3" json:"vmConfigContainerName,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *StorageConfiguration) Reset()         { *m = StorageConfiguration{} }
func (m *StorageConfiguration) String() string { return proto.CompactTextString(m) }
func (*StorageConfiguration) ProtoMessage()    {}
func (*StorageConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{4}
}

func (m *StorageConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageConfiguration.Unmarshal(m, b)
}
func (m *StorageConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageConfiguration.Marshal(b, m, deterministic)
}
func (m *StorageConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageConfiguration.Merge(m, src)
}
func (m *StorageConfiguration) XXX_Size() int {
	return xxx_messageInfo_StorageConfiguration.Size(m)
}
func (m *StorageConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_StorageConfiguration proto.InternalMessageInfo

func (m *StorageConfiguration) GetOsdisk() *Disk {
	if m != nil {
		return m.Osdisk
	}
	return nil
}

func (m *StorageConfiguration) GetDatadisks() []*Disk {
	if m != nil {
		return m.Datadisks
	}
	return nil
}

func (m *StorageConfiguration) GetVmConfigContainerName() string {
	if m != nil {
		return m.VmConfigContainerName
	}
	return ""
}

type NetworkInterface struct {
	// reference to network interface managed by network
	NetworkInterfaceName string   `protobuf:"bytes,1,opt,name=networkInterfaceName,proto3" json:"networkInterfaceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInterface) Reset()         { *m = NetworkInterface{} }
func (m *NetworkInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface) ProtoMessage()    {}
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{5}
}

func (m *NetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface.Unmarshal(m, b)
}
func (m *NetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface.Marshal(b, m, deterministic)
}
func (m *NetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface.Merge(m, src)
}
func (m *NetworkInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface.Size(m)
}
func (m *NetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface proto.InternalMessageInfo

func (m *NetworkInterface) GetNetworkInterfaceName() string {
	if m != nil {
		return m.NetworkInterfaceName
	}
	return ""
}

type NetworkConfiguration struct {
	Interfaces           []*NetworkInterface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NetworkConfiguration) Reset()         { *m = NetworkConfiguration{} }
func (m *NetworkConfiguration) String() string { return proto.CompactTextString(m) }
func (*NetworkConfiguration) ProtoMessage()    {}
func (*NetworkConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{6}
}

func (m *NetworkConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkConfiguration.Unmarshal(m, b)
}
func (m *NetworkConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkConfiguration.Marshal(b, m, deterministic)
}
func (m *NetworkConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkConfiguration.Merge(m, src)
}
func (m *NetworkConfiguration) XXX_Size() int {
	return xxx_messageInfo_NetworkConfiguration.Size(m)
}
func (m *NetworkConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkConfiguration proto.InternalMessageInfo

func (m *NetworkConfiguration) GetInterfaces() []*NetworkInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

type UserConfiguration struct {
	Username             string          `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string          `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Usertype             common.UserType `protobuf:"varint,3,opt,name=usertype,proto3,enum=moc.UserType" json:"usertype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserConfiguration) Reset()         { *m = UserConfiguration{} }
func (m *UserConfiguration) String() string { return proto.CompactTextString(m) }
func (*UserConfiguration) ProtoMessage()    {}
func (*UserConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{7}
}

func (m *UserConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserConfiguration.Unmarshal(m, b)
}
func (m *UserConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserConfiguration.Marshal(b, m, deterministic)
}
func (m *UserConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserConfiguration.Merge(m, src)
}
func (m *UserConfiguration) XXX_Size() int {
	return xxx_messageInfo_UserConfiguration.Size(m)
}
func (m *UserConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_UserConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_UserConfiguration proto.InternalMessageInfo

func (m *UserConfiguration) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserConfiguration) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserConfiguration) GetUsertype() common.UserType {
	if m != nil {
		return m.Usertype
	}
	return common.UserType_ROOT
}

type RDPConfiguration struct {
	DisableRDP           bool     `protobuf:"varint,1,opt,name=disableRDP,proto3" json:"disableRDP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RDPConfiguration) Reset()         { *m = RDPConfiguration{} }
func (m *RDPConfiguration) String() string { return proto.CompactTextString(m) }
func (*RDPConfiguration) ProtoMessage()    {}
func (*RDPConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{8}
}

func (m *RDPConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RDPConfiguration.Unmarshal(m, b)
}
func (m *RDPConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RDPConfiguration.Marshal(b, m, deterministic)
}
func (m *RDPConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RDPConfiguration.Merge(m, src)
}
func (m *RDPConfiguration) XXX_Size() int {
	return xxx_messageInfo_RDPConfiguration.Size(m)
}
func (m *RDPConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_RDPConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_RDPConfiguration proto.InternalMessageInfo

func (m *RDPConfiguration) GetDisableRDP() bool {
	if m != nil {
		return m.DisableRDP
	}
	return false
}

type LinuxConfiguration struct {
	DisablePasswordAuthentication bool     `protobuf:"varint,1,opt,name=disablePasswordAuthentication,proto3" json:"disablePasswordAuthentication,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *LinuxConfiguration) Reset()         { *m = LinuxConfiguration{} }
func (m *LinuxConfiguration) String() string { return proto.CompactTextString(m) }
func (*LinuxConfiguration) ProtoMessage()    {}
func (*LinuxConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{9}
}

func (m *LinuxConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinuxConfiguration.Unmarshal(m, b)
}
func (m *LinuxConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinuxConfiguration.Marshal(b, m, deterministic)
}
func (m *LinuxConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinuxConfiguration.Merge(m, src)
}
func (m *LinuxConfiguration) XXX_Size() int {
	return xxx_messageInfo_LinuxConfiguration.Size(m)
}
func (m *LinuxConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_LinuxConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_LinuxConfiguration proto.InternalMessageInfo

func (m *LinuxConfiguration) GetDisablePasswordAuthentication() bool {
	if m != nil {
		return m.DisablePasswordAuthentication
	}
	return false
}

type WindowsConfiguration struct {
	EnableAutomaticUpdates bool                       `protobuf:"varint,1,opt,name=enableAutomaticUpdates,proto3" json:"enableAutomaticUpdates,omitempty"`
	TimeZone               string                     `protobuf:"bytes,2,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	RDPConfiguration       *RDPConfiguration          `protobuf:"bytes,3,opt,name=RDPConfiguration,proto3" json:"RDPConfiguration,omitempty"`
	WinRMConfiguration     *common.WinRMConfiguration `protobuf:"bytes,4,opt,name=WinRMConfiguration,proto3" json:"WinRMConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                   `json:"-"`
	XXX_unrecognized       []byte                     `json:"-"`
	XXX_sizecache          int32                      `json:"-"`
}

func (m *WindowsConfiguration) Reset()         { *m = WindowsConfiguration{} }
func (m *WindowsConfiguration) String() string { return proto.CompactTextString(m) }
func (*WindowsConfiguration) ProtoMessage()    {}
func (*WindowsConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{10}
}

func (m *WindowsConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowsConfiguration.Unmarshal(m, b)
}
func (m *WindowsConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowsConfiguration.Marshal(b, m, deterministic)
}
func (m *WindowsConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowsConfiguration.Merge(m, src)
}
func (m *WindowsConfiguration) XXX_Size() int {
	return xxx_messageInfo_WindowsConfiguration.Size(m)
}
func (m *WindowsConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowsConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_WindowsConfiguration proto.InternalMessageInfo

func (m *WindowsConfiguration) GetEnableAutomaticUpdates() bool {
	if m != nil {
		return m.EnableAutomaticUpdates
	}
	return false
}

func (m *WindowsConfiguration) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *WindowsConfiguration) GetRDPConfiguration() *RDPConfiguration {
	if m != nil {
		return m.RDPConfiguration
	}
	return nil
}

func (m *WindowsConfiguration) GetWinRMConfiguration() *common.WinRMConfiguration {
	if m != nil {
		return m.WinRMConfiguration
	}
	return nil
}

type OperatingSystemConfiguration struct {
	ComputerName  string                     `protobuf:"bytes,1,opt,name=computerName,proto3" json:"computerName,omitempty"`
	Administrator *UserConfiguration         `protobuf:"bytes,2,opt,name=administrator,proto3" json:"administrator,omitempty"`
	Users         []*UserConfiguration       `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	CustomData    string                     `protobuf:"bytes,4,opt,name=customData,proto3" json:"customData,omitempty"`
	Publickeys    []*SSHPublicKey            `protobuf:"bytes,5,rep,name=publickeys,proto3" json:"publickeys,omitempty"`
	Ostype        common.OperatingSystemType `protobuf:"varint,6,opt,name=ostype,proto3,enum=moc.OperatingSystemType" json:"ostype,omitempty"`
	// bootstrap engine can be cloud-init, Windows answer files, ...
	OsBootstrapEngine    common.OperatingSystemBootstrapEngine `protobuf:"varint,7,opt,name=osBootstrapEngine,proto3,enum=moc.OperatingSystemBootstrapEngine" json:"osBootstrapEngine,omitempty"`
	LinuxConfiguration   *LinuxConfiguration                   `protobuf:"bytes,8,opt,name=linuxConfiguration,proto3" json:"linuxConfiguration,omitempty"`
	WindowsConfiguration *WindowsConfiguration                 `protobuf:"bytes,9,opt,name=windowsConfiguration,proto3" json:"windowsConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *OperatingSystemConfiguration) Reset()         { *m = OperatingSystemConfiguration{} }
func (m *OperatingSystemConfiguration) String() string { return proto.CompactTextString(m) }
func (*OperatingSystemConfiguration) ProtoMessage()    {}
func (*OperatingSystemConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{11}
}

func (m *OperatingSystemConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatingSystemConfiguration.Unmarshal(m, b)
}
func (m *OperatingSystemConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatingSystemConfiguration.Marshal(b, m, deterministic)
}
func (m *OperatingSystemConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatingSystemConfiguration.Merge(m, src)
}
func (m *OperatingSystemConfiguration) XXX_Size() int {
	return xxx_messageInfo_OperatingSystemConfiguration.Size(m)
}
func (m *OperatingSystemConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatingSystemConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_OperatingSystemConfiguration proto.InternalMessageInfo

func (m *OperatingSystemConfiguration) GetComputerName() string {
	if m != nil {
		return m.ComputerName
	}
	return ""
}

func (m *OperatingSystemConfiguration) GetAdministrator() *UserConfiguration {
	if m != nil {
		return m.Administrator
	}
	return nil
}

func (m *OperatingSystemConfiguration) GetUsers() []*UserConfiguration {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *OperatingSystemConfiguration) GetCustomData() string {
	if m != nil {
		return m.CustomData
	}
	return ""
}

func (m *OperatingSystemConfiguration) GetPublickeys() []*SSHPublicKey {
	if m != nil {
		return m.Publickeys
	}
	return nil
}

func (m *OperatingSystemConfiguration) GetOstype() common.OperatingSystemType {
	if m != nil {
		return m.Ostype
	}
	return common.OperatingSystemType_WINDOWS
}

func (m *OperatingSystemConfiguration) GetOsBootstrapEngine() common.OperatingSystemBootstrapEngine {
	if m != nil {
		return m.OsBootstrapEngine
	}
	return common.OperatingSystemBootstrapEngine_CLOUD_INIT
}

func (m *OperatingSystemConfiguration) GetLinuxConfiguration() *LinuxConfiguration {
	if m != nil {
		return m.LinuxConfiguration
	}
	return nil
}

func (m *OperatingSystemConfiguration) GetWindowsConfiguration() *WindowsConfiguration {
	if m != nil {
		return m.WindowsConfiguration
	}
	return nil
}

type HardwareConfiguration struct {
	VMSize                     common.VirtualMachineSizeType      `protobuf:"varint,1,opt,name=VMSize,proto3,enum=moc.VirtualMachineSizeType" json:"VMSize,omitempty"`
	CustomSize                 *common.VirtualMachineCustomSize   `protobuf:"bytes,2,opt,name=customSize,proto3" json:"customSize,omitempty"`
	DynamicMemoryConfiguration *common.DynamicMemoryConfiguration `protobuf:"bytes,3,opt,name=dynamicMemoryConfiguration,proto3" json:"dynamicMemoryConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                           `json:"-"`
	XXX_unrecognized           []byte                             `json:"-"`
	XXX_sizecache              int32                              `json:"-"`
}

func (m *HardwareConfiguration) Reset()         { *m = HardwareConfiguration{} }
func (m *HardwareConfiguration) String() string { return proto.CompactTextString(m) }
func (*HardwareConfiguration) ProtoMessage()    {}
func (*HardwareConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{12}
}

func (m *HardwareConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareConfiguration.Unmarshal(m, b)
}
func (m *HardwareConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareConfiguration.Marshal(b, m, deterministic)
}
func (m *HardwareConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareConfiguration.Merge(m, src)
}
func (m *HardwareConfiguration) XXX_Size() int {
	return xxx_messageInfo_HardwareConfiguration.Size(m)
}
func (m *HardwareConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareConfiguration proto.InternalMessageInfo

func (m *HardwareConfiguration) GetVMSize() common.VirtualMachineSizeType {
	if m != nil {
		return m.VMSize
	}
	return common.VirtualMachineSizeType_Default
}

func (m *HardwareConfiguration) GetCustomSize() *common.VirtualMachineCustomSize {
	if m != nil {
		return m.CustomSize
	}
	return nil
}

func (m *HardwareConfiguration) GetDynamicMemoryConfiguration() *common.DynamicMemoryConfiguration {
	if m != nil {
		return m.DynamicMemoryConfiguration
	}
	return nil
}

type UefiSettings struct {
	SecureBootEnabled    bool     `protobuf:"varint,1,opt,name=secureBootEnabled,proto3" json:"secureBootEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UefiSettings) Reset()         { *m = UefiSettings{} }
func (m *UefiSettings) String() string { return proto.CompactTextString(m) }
func (*UefiSettings) ProtoMessage()    {}
func (*UefiSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{13}
}

func (m *UefiSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UefiSettings.Unmarshal(m, b)
}
func (m *UefiSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UefiSettings.Marshal(b, m, deterministic)
}
func (m *UefiSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UefiSettings.Merge(m, src)
}
func (m *UefiSettings) XXX_Size() int {
	return xxx_messageInfo_UefiSettings.Size(m)
}
func (m *UefiSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_UefiSettings.DiscardUnknown(m)
}

var xxx_messageInfo_UefiSettings proto.InternalMessageInfo

func (m *UefiSettings) GetSecureBootEnabled() bool {
	if m != nil {
		return m.SecureBootEnabled
	}
	return false
}

type SecurityConfiguration struct {
	EnableTPM            bool          `protobuf:"varint,1,opt,name=enableTPM,proto3" json:"enableTPM,omitempty"`
	UefiSettings         *UefiSettings `protobuf:"bytes,2,opt,name=uefiSettings,proto3" json:"uefiSettings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SecurityConfiguration) Reset()         { *m = SecurityConfiguration{} }
func (m *SecurityConfiguration) String() string { return proto.CompactTextString(m) }
func (*SecurityConfiguration) ProtoMessage()    {}
func (*SecurityConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{14}
}

func (m *SecurityConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityConfiguration.Unmarshal(m, b)
}
func (m *SecurityConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityConfiguration.Marshal(b, m, deterministic)
}
func (m *SecurityConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityConfiguration.Merge(m, src)
}
func (m *SecurityConfiguration) XXX_Size() int {
	return xxx_messageInfo_SecurityConfiguration.Size(m)
}
func (m *SecurityConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityConfiguration proto.InternalMessageInfo

func (m *SecurityConfiguration) GetEnableTPM() bool {
	if m != nil {
		return m.EnableTPM
	}
	return false
}

func (m *SecurityConfiguration) GetUefiSettings() *UefiSettings {
	if m != nil {
		return m.UefiSettings
	}
	return nil
}

type VirtualMachine struct {
	Name                    string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                      string                        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Storage                 *StorageConfiguration         `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	Os                      *OperatingSystemConfiguration `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Network                 *NetworkConfiguration         `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Hardware                *HardwareConfiguration        `protobuf:"bytes,6,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Status                  *common.Status                `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DisableHighAvailability bool                          `protobuf:"varint,8,opt,name=disableHighAvailability,proto3" json:"disableHighAvailability,omitempty"`
	AllowedOwnerNodes       []string                      `protobuf:"bytes,9,rep,name=allowedOwnerNodes,proto3" json:"allowedOwnerNodes,omitempty"`
	PowerState              common.PowerState             `protobuf:"varint,10,opt,name=powerState,proto3,enum=moc.PowerState" json:"powerState,omitempty"`
	Security                *SecurityConfiguration        `protobuf:"bytes,11,opt,name=security,proto3" json:"security,omitempty"`
	Entity                  *common.Entity                `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`
	HighAvailabilityState   common.HighAvailabilityState  `protobuf:"varint,13,opt,name=highAvailabilityState,proto3,enum=moc.HighAvailabilityState" json:"highAvailabilityState,omitempty"`
	Tags                    *common.Tags                  `protobuf:"bytes,14,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                      `json:"-"`
	XXX_unrecognized        []byte                        `json:"-"`
	XXX_sizecache           int32                         `json:"-"`
}

func (m *VirtualMachine) Reset()         { *m = VirtualMachine{} }
func (m *VirtualMachine) String() string { return proto.CompactTextString(m) }
func (*VirtualMachine) ProtoMessage()    {}
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{15}
}

func (m *VirtualMachine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachine.Unmarshal(m, b)
}
func (m *VirtualMachine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachine.Marshal(b, m, deterministic)
}
func (m *VirtualMachine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachine.Merge(m, src)
}
func (m *VirtualMachine) XXX_Size() int {
	return xxx_messageInfo_VirtualMachine.Size(m)
}
func (m *VirtualMachine) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachine.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachine proto.InternalMessageInfo

func (m *VirtualMachine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachine) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachine) GetStorage() *StorageConfiguration {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *VirtualMachine) GetOs() *OperatingSystemConfiguration {
	if m != nil {
		return m.Os
	}
	return nil
}

func (m *VirtualMachine) GetNetwork() *NetworkConfiguration {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *VirtualMachine) GetHardware() *HardwareConfiguration {
	if m != nil {
		return m.Hardware
	}
	return nil
}

func (m *VirtualMachine) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VirtualMachine) GetDisableHighAvailability() bool {
	if m != nil {
		return m.DisableHighAvailability
	}
	return false
}

func (m *VirtualMachine) GetAllowedOwnerNodes() []string {
	if m != nil {
		return m.AllowedOwnerNodes
	}
	return nil
}

func (m *VirtualMachine) GetPowerState() common.PowerState {
	if m != nil {
		return m.PowerState
	}
	return common.PowerState_Unknown
}

func (m *VirtualMachine) GetSecurity() *SecurityConfiguration {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *VirtualMachine) GetEntity() *common.Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *VirtualMachine) GetHighAvailabilityState() common.HighAvailabilityState {
	if m != nil {
		return m.HighAvailabilityState
	}
	return common.HighAvailabilityState_UNKNOWN_HA_STATE
}

func (m *VirtualMachine) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type VirtualMachineOperationRequest struct {
	VirtualMachines      []*VirtualMachine              `protobuf:"bytes,1,rep,name=VirtualMachines,proto3" json:"VirtualMachines,omitempty"`
	OperationType        common.VirtualMachineOperation `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.VirtualMachineOperation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *VirtualMachineOperationRequest) Reset()         { *m = VirtualMachineOperationRequest{} }
func (m *VirtualMachineOperationRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineOperationRequest) ProtoMessage()    {}
func (*VirtualMachineOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{16}
}

func (m *VirtualMachineOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineOperationRequest.Unmarshal(m, b)
}
func (m *VirtualMachineOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineOperationRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineOperationRequest.Merge(m, src)
}
func (m *VirtualMachineOperationRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineOperationRequest.Size(m)
}
func (m *VirtualMachineOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineOperationRequest proto.InternalMessageInfo

func (m *VirtualMachineOperationRequest) GetVirtualMachines() []*VirtualMachine {
	if m != nil {
		return m.VirtualMachines
	}
	return nil
}

func (m *VirtualMachineOperationRequest) GetOperationType() common.VirtualMachineOperation {
	if m != nil {
		return m.OperationType
	}
	return common.VirtualMachineOperation_START
}

type VirtualMachineOperationResponse struct {
	VirtualMachines      []*VirtualMachine   `protobuf:"bytes,1,rep,name=VirtualMachines,proto3" json:"VirtualMachines,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VirtualMachineOperationResponse) Reset()         { *m = VirtualMachineOperationResponse{} }
func (m *VirtualMachineOperationResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineOperationResponse) ProtoMessage()    {}
func (*VirtualMachineOperationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{17}
}

func (m *VirtualMachineOperationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineOperationResponse.Unmarshal(m, b)
}
func (m *VirtualMachineOperationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineOperationResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineOperationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineOperationResponse.Merge(m, src)
}
func (m *VirtualMachineOperationResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineOperationResponse.Size(m)
}
func (m *VirtualMachineOperationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineOperationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineOperationResponse proto.InternalMessageInfo

func (m *VirtualMachineOperationResponse) GetVirtualMachines() []*VirtualMachine {
	if m != nil {
		return m.VirtualMachines
	}
	return nil
}

func (m *VirtualMachineOperationResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *VirtualMachineOperationResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type VirtualMachineRunCommandRequest struct {
	VirtualMachine            *VirtualMachine                                  `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	Source                    *common.VirtualMachineRunCommandScriptSource     `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	RunCommandInputParameters []*common.VirtualMachineRunCommandInputParameter `protobuf:"bytes,3,rep,name=RunCommandInputParameters,proto3" json:"RunCommandInputParameters,omitempty"`
	RunAsUser                 string                                           `protobuf:"bytes,4,opt,name=RunAsUser,proto3" json:"RunAsUser,omitempty"`
	RunAsPassword             string                                           `protobuf:"bytes,5,opt,name=RunAsPassword,proto3" json:"RunAsPassword,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                         `json:"-"`
	XXX_unrecognized          []byte                                           `json:"-"`
	XXX_sizecache             int32                                            `json:"-"`
}

func (m *VirtualMachineRunCommandRequest) Reset()         { *m = VirtualMachineRunCommandRequest{} }
func (m *VirtualMachineRunCommandRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandRequest) ProtoMessage()    {}
func (*VirtualMachineRunCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{18}
}

func (m *VirtualMachineRunCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandRequest.Merge(m, src)
}
func (m *VirtualMachineRunCommandRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandRequest.Size(m)
}
func (m *VirtualMachineRunCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandRequest proto.InternalMessageInfo

func (m *VirtualMachineRunCommandRequest) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetSource() *common.VirtualMachineRunCommandScriptSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunCommandInputParameters() []*common.VirtualMachineRunCommandInputParameter {
	if m != nil {
		return m.RunCommandInputParameters
	}
	return nil
}

func (m *VirtualMachineRunCommandRequest) GetRunAsUser() string {
	if m != nil {
		return m.RunAsUser
	}
	return ""
}

func (m *VirtualMachineRunCommandRequest) GetRunAsPassword() string {
	if m != nil {
		return m.RunAsPassword
	}
	return ""
}

type VirtualMachineRunCommandResponse struct {
	VirtualMachine       *VirtualMachine                              `protobuf:"bytes,1,opt,name=VirtualMachine,proto3" json:"VirtualMachine,omitempty"`
	InstanceView         *common.VirtualMachineRunCommandInstanceView `protobuf:"bytes,2,opt,name=InstanceView,proto3" json:"InstanceView,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *VirtualMachineRunCommandResponse) Reset()         { *m = VirtualMachineRunCommandResponse{} }
func (m *VirtualMachineRunCommandResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineRunCommandResponse) ProtoMessage()    {}
func (*VirtualMachineRunCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f3eecb05bcac3b7, []int{19}
}

func (m *VirtualMachineRunCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Unmarshal(m, b)
}
func (m *VirtualMachineRunCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineRunCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineRunCommandResponse.Merge(m, src)
}
func (m *VirtualMachineRunCommandResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineRunCommandResponse.Size(m)
}
func (m *VirtualMachineRunCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineRunCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineRunCommandResponse proto.InternalMessageInfo

func (m *VirtualMachineRunCommandResponse) GetVirtualMachine() *VirtualMachine {
	if m != nil {
		return m.VirtualMachine
	}
	return nil
}

func (m *VirtualMachineRunCommandResponse) GetInstanceView() *common.VirtualMachineRunCommandInstanceView {
	if m != nil {
		return m.InstanceView
	}
	return nil
}

func init() {
	proto.RegisterType((*VirtualMachineRequest)(nil), "moc.nodeagent.compute.VirtualMachineRequest")
	proto.RegisterType((*VirtualMachineResponse)(nil), "moc.nodeagent.compute.VirtualMachineResponse")
	proto.RegisterType((*SSHPublicKey)(nil), "moc.nodeagent.compute.SSHPublicKey")
	proto.RegisterType((*Disk)(nil), "moc.nodeagent.compute.Disk")
	proto.RegisterType((*StorageConfiguration)(nil), "moc.nodeagent.compute.StorageConfiguration")
	proto.RegisterType((*NetworkInterface)(nil), "moc.nodeagent.compute.NetworkInterface")
	proto.RegisterType((*NetworkConfiguration)(nil), "moc.nodeagent.compute.NetworkConfiguration")
	proto.RegisterType((*UserConfiguration)(nil), "moc.nodeagent.compute.UserConfiguration")
	proto.RegisterType((*RDPConfiguration)(nil), "moc.nodeagent.compute.RDPConfiguration")
	proto.RegisterType((*LinuxConfiguration)(nil), "moc.nodeagent.compute.LinuxConfiguration")
	proto.RegisterType((*WindowsConfiguration)(nil), "moc.nodeagent.compute.WindowsConfiguration")
	proto.RegisterType((*OperatingSystemConfiguration)(nil), "moc.nodeagent.compute.OperatingSystemConfiguration")
	proto.RegisterType((*HardwareConfiguration)(nil), "moc.nodeagent.compute.HardwareConfiguration")
	proto.RegisterType((*UefiSettings)(nil), "moc.nodeagent.compute.UefiSettings")
	proto.RegisterType((*SecurityConfiguration)(nil), "moc.nodeagent.compute.SecurityConfiguration")
	proto.RegisterType((*VirtualMachine)(nil), "moc.nodeagent.compute.VirtualMachine")
	proto.RegisterType((*VirtualMachineOperationRequest)(nil), "moc.nodeagent.compute.VirtualMachineOperationRequest")
	proto.RegisterType((*VirtualMachineOperationResponse)(nil), "moc.nodeagent.compute.VirtualMachineOperationResponse")
	proto.RegisterType((*VirtualMachineRunCommandRequest)(nil), "moc.nodeagent.compute.VirtualMachineRunCommandRequest")
	proto.RegisterType((*VirtualMachineRunCommandResponse)(nil), "moc.nodeagent.compute.VirtualMachineRunCommandResponse")
}

func init() {
	proto.RegisterFile("moc_nodeagent_virtualmachine.proto", fileDescriptor_9f3eecb05bcac3b7)
}

var fileDescriptor_9f3eecb05bcac3b7 = []byte{
	// 1537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x6e, 0x1b, 0x37,
	0x16, 0x5e, 0xc9, 0xbf, 0x3a, 0xfe, 0x49, 0xcc, 0xb5, 0x93, 0x89, 0x12, 0x3b, 0xc6, 0x24, 0x8b,
	0x75, 0x90, 0xac, 0x14, 0x28, 0xd9, 0xec, 0x2e, 0xb0, 0xbb, 0x80, 0xff, 0x36, 0x36, 0xb6, 0x76,
	0x54, 0x2a, 0x71, 0xd0, 0xf4, 0xc2, 0xa0, 0x47, 0xb4, 0x4c, 0x58, 0x43, 0x4e, 0x87, 0x1c, 0xab,
	0xca, 0x45, 0x0b, 0xf4, 0x2a, 0xcf, 0xd2, 0xfb, 0xdc, 0x05, 0x68, 0x6f, 0xfa, 0x22, 0xbd, 0x2e,
	0xd0, 0x37, 0x28, 0x0a, 0x72, 0x28, 0x69, 0x66, 0x34, 0x63, 0x38, 0x40, 0x7a, 0x15, 0xeb, 0x9c,
	0xf3, 0x7d, 0xfc, 0x78, 0x78, 0xce, 0x21, 0x27, 0xe0, 0xfa, 0xc2, 0x3b, 0xe6, 0xa2, 0x4d, 0x49,
	0x87, 0x72, 0x75, 0x7c, 0xc1, 0x42, 0x15, 0x91, 0xae, 0x4f, 0xbc, 0x33, 0xc6, 0x69, 0x2d, 0x08,
	0x85, 0x12, 0x68, 0xc5, 0x17, 0x5e, 0x6d, 0x18, 0x53, 0xf3, 0x84, 0x1f, 0x44, 0x8a, 0x56, 0x6f,
	0x77, 0x84, 0xe8, 0x74, 0x69, 0xdd, 0x04, 0x9d, 0x44, 0xa7, 0x75, 0xea, 0x07, 0xaa, 0x1f, 0x63,
	0xaa, 0x6b, 0x59, 0x67, 0x2f, 0x24, 0x41, 0x40, 0x43, 0x69, 0xfd, 0x37, 0xf5, 0xba, 0x9e, 0xf0,
	0x7d, 0xc1, 0xed, 0x3f, 0x03, 0x60, 0xda, 0xa1, 0x57, 0x4a, 0xf9, 0x57, 0x13, 0x7e, 0x2e, 0x14,
	0x3b, 0x65, 0x1e, 0x51, 0x6c, 0xe0, 0x76, 0xbf, 0x2f, 0xc1, 0xca, 0x51, 0xbc, 0x89, 0x83, 0x78,
	0x13, 0x98, 0x7e, 0x15, 0x51, 0xa9, 0xd0, 0x97, 0x59, 0x47, 0xab, 0x2f, 0x15, 0xf5, 0xa5, 0x53,
	0x5a, 0x9f, 0xd8, 0x98, 0x6b, 0xfc, 0xa5, 0x96, 0xbb, 0xcb, 0x5a, 0x86, 0x2c, 0x9f, 0x03, 0x3d,
	0x85, 0x85, 0x17, 0x01, 0x0d, 0x8d, 0x92, 0x97, 0xfd, 0x80, 0x3a, 0xe5, 0xf5, 0xd2, 0xc6, 0x62,
	0x63, 0xd1, 0x90, 0x0e, 0x3d, 0x38, 0x1d, 0xe4, 0xfe, 0x50, 0x82, 0x1b, 0x59, 0xb1, 0x32, 0x10,
	0x5c, 0xd2, 0x3f, 0x56, 0x6d, 0x03, 0xa6, 0x31, 0x95, 0x51, 0x57, 0x19, 0x99, 0x73, 0x8d, 0x6a,
	0x2d, 0x3e, 0xad, 0xda, 0xe0, 0xb4, 0x6a, 0x5b, 0x42, 0x74, 0x8f, 0x48, 0x37, 0xa2, 0xd8, 0x46,
	0xa2, 0x65, 0x98, 0xda, 0x0d, 0x43, 0x11, 0x3a, 0x13, 0xeb, 0xa5, 0x8d, 0x0a, 0x8e, 0x7f, 0xb8,
	0x35, 0x98, 0x6f, 0xb5, 0xf6, 0x9a, 0xd1, 0x49, 0x97, 0x79, 0xff, 0xa7, 0x7d, 0xb4, 0x06, 0x33,
	0xe7, 0xb4, 0xdf, 0x26, 0x8a, 0x38, 0x25, 0x1d, 0xb7, 0x35, 0xf9, 0xee, 0xbd, 0x53, 0xc2, 0x03,
	0xa3, 0xeb, 0xc2, 0xe4, 0x0e, 0x93, 0xe7, 0xa8, 0x0a, 0xb3, 0x6d, 0x26, 0xcf, 0x39, 0xf1, 0x69,
	0x1c, 0x88, 0x87, 0xbf, 0xdd, 0x0f, 0x25, 0x58, 0x6e, 0x29, 0x11, 0x92, 0x0e, 0xdd, 0x16, 0xfc,
	0x94, 0x75, 0xa2, 0x38, 0x65, 0xe8, 0x09, 0x4c, 0x0b, 0xa9, 0xc3, 0x0c, 0x64, 0xae, 0x71, 0xbb,
	0x20, 0x09, 0x7a, 0x05, 0x6c, 0x43, 0xd1, 0xbf, 0xa0, 0xa2, 0x57, 0xd6, 0x7f, 0x4b, 0xa7, 0x6c,
	0x92, 0x77, 0x29, 0x6e, 0x14, 0x8d, 0x9e, 0xc2, 0xca, 0x85, 0x1f, 0x4b, 0xd8, 0x16, 0x5c, 0x11,
	0xc6, 0x69, 0x78, 0xa8, 0x15, 0xc7, 0x29, 0xc8, 0x77, 0xba, 0xff, 0x83, 0xeb, 0x87, 0x54, 0xf5,
	0x44, 0x78, 0xbe, 0xcf, 0x15, 0x0d, 0x4f, 0x89, 0x47, 0x51, 0x03, 0x96, 0x79, 0xc6, 0x76, 0x38,
	0xda, 0x7a, 0xae, 0xcf, 0x3d, 0x86, 0x65, 0xcb, 0x93, 0xce, 0xc2, 0x73, 0x00, 0x36, 0x08, 0x1c,
	0x94, 0xc3, 0x5f, 0x0b, 0x76, 0x94, 0x15, 0x82, 0x13, 0x50, 0xf7, 0xbb, 0x12, 0x2c, 0xbd, 0x92,
	0x34, 0x4c, 0xd3, 0xaf, 0xc3, 0x6c, 0x24, 0x69, 0x38, 0x3a, 0x19, 0x7b, 0x84, 0x43, 0xab, 0x8e,
	0x08, 0x88, 0x94, 0x3d, 0x11, 0xb6, 0x4d, 0xfd, 0x0c, 0x23, 0x06, 0x56, 0xf4, 0x20, 0xe6, 0x50,
	0xba, 0x11, 0x26, 0x4c, 0x23, 0x2c, 0x18, 0x81, 0x7a, 0x35, 0x5d, 0xf8, 0x78, 0xe8, 0x76, 0x1b,
	0x70, 0x1d, 0xef, 0x34, 0xd3, 0x12, 0xd6, 0x00, 0xda, 0x4c, 0x92, 0x93, 0x2e, 0xc5, 0x3b, 0x4d,
	0x23, 0x62, 0x16, 0x27, 0x2c, 0xee, 0x1b, 0x40, 0x9f, 0x31, 0x1e, 0x7d, 0x9d, 0x46, 0xed, 0xc0,
	0xaa, 0x8d, 0x69, 0x5a, 0x1d, 0x9b, 0x91, 0x3a, 0xa3, 0x5c, 0xd9, 0x01, 0x61, 0x89, 0x2e, 0x0f,
	0x72, 0xdf, 0x95, 0x61, 0xf9, 0x35, 0xe3, 0x6d, 0xd1, 0x93, 0x69, 0xfa, 0x67, 0x70, 0x83, 0x72,
	0x0d, 0xdc, 0x8c, 0x94, 0xf0, 0x89, 0x62, 0xde, 0xab, 0xa0, 0x4d, 0x94, 0x39, 0x02, 0xcd, 0x5b,
	0xe0, 0xd5, 0x95, 0xae, 0x98, 0x4f, 0xdf, 0x08, 0x1e, 0x0f, 0x85, 0x0a, 0x1e, 0xfe, 0x46, 0xad,
	0xf1, 0xcd, 0x9b, 0x7c, 0x15, 0x1f, 0x68, 0x36, 0x1c, 0x8f, 0x67, 0xef, 0x39, 0xa0, 0xd7, 0x8c,
	0xe3, 0x83, 0x34, 0xed, 0xa4, 0xa1, 0xbd, 0x69, 0x68, 0xc7, 0xdd, 0x38, 0x07, 0xe2, 0xfe, 0x36,
	0x09, 0x77, 0xec, 0xbc, 0xe2, 0x9d, 0x78, 0x74, 0xa4, 0x57, 0x72, 0x61, 0xde, 0xea, 0x0a, 0x13,
	0xd5, 0x9c, 0xb2, 0xa1, 0x43, 0x58, 0x20, 0x6d, 0x9f, 0x71, 0x26, 0x55, 0x48, 0x94, 0x08, 0xed,
	0xc4, 0xd9, 0x28, 0xd8, 0xdf, 0x58, 0x3d, 0xe2, 0x34, 0x1c, 0xfd, 0x17, 0xa6, 0x74, 0xed, 0x48,
	0x67, 0xc2, 0x14, 0xfe, 0xd5, 0x79, 0x62, 0x18, 0xba, 0x0f, 0xe0, 0x45, 0x52, 0x09, 0x7f, 0x47,
	0xcf, 0xa8, 0xc9, 0x44, 0xf9, 0x26, 0xec, 0x68, 0x1b, 0x20, 0x30, 0x33, 0xed, 0x9c, 0xf6, 0xa5,
	0x33, 0x65, 0x96, 0xba, 0x57, 0xb0, 0x54, 0x72, 0xfe, 0xe1, 0x04, 0x0c, 0x3d, 0xd6, 0xe3, 0xca,
	0xf4, 0xc0, 0xb4, 0xe9, 0x01, 0x27, 0x79, 0x19, 0x0c, 0x32, 0x6a, 0xda, 0xc1, 0xc6, 0xa1, 0xcf,
	0x61, 0x49, 0xc8, 0x2d, 0x21, 0x94, 0xde, 0x6d, 0xb0, 0xcb, 0x3b, 0x8c, 0x53, 0x67, 0xc6, 0x80,
	0xef, 0xe5, 0x81, 0x33, 0xa1, 0x78, 0x1c, 0x8d, 0xbe, 0x00, 0xd4, 0x1d, 0xeb, 0x15, 0x67, 0xd6,
	0x1c, 0xc2, 0x83, 0x82, 0x1d, 0x8d, 0x37, 0x17, 0xce, 0x21, 0x41, 0xc7, 0xb0, 0xdc, 0xcb, 0xe9,
	0x14, 0xa7, 0x62, 0xc8, 0x1f, 0x16, 0x90, 0xe7, 0x35, 0x17, 0xce, 0x25, 0x72, 0x7f, 0x29, 0xc1,
	0xca, 0x1e, 0x09, 0xdb, 0x3d, 0x12, 0x8e, 0xdf, 0x04, 0x47, 0x07, 0x2d, 0xf6, 0x36, 0xae, 0xb9,
	0x45, 0x3b, 0xd1, 0x33, 0x97, 0x1d, 0x7b, 0x4b, 0xe3, 0xec, 0xc6, 0xa1, 0xe8, 0x3f, 0x83, 0xa3,
	0x37, 0xc0, 0xb8, 0x0e, 0x57, 0x73, 0x80, 0xdb, 0xc3, 0x20, 0x9c, 0x00, 0xa0, 0x63, 0xa8, 0xb6,
	0xfb, 0x9c, 0xf8, 0xcc, 0x3b, 0xa0, 0xbe, 0x08, 0xfb, 0x79, 0x6d, 0x7b, 0xd7, 0xd0, 0xed, 0x14,
	0x86, 0xe1, 0x4b, 0x28, 0xdc, 0x7f, 0xc3, 0xfc, 0x2b, 0x7a, 0xca, 0x5a, 0x54, 0xe9, 0x13, 0x96,
	0xe8, 0x11, 0x2c, 0x49, 0xea, 0x45, 0x21, 0xd5, 0x67, 0xba, 0x6b, 0xa6, 0x4b, 0xdb, 0x0e, 0x9b,
	0x71, 0x87, 0xfb, 0x0d, 0xac, 0xb4, 0xb4, 0x91, 0xa9, 0x34, 0x2d, 0xba, 0x03, 0x95, 0x78, 0x34,
	0xbd, 0x6c, 0x1e, 0x58, 0xf8, 0xc8, 0x80, 0x9e, 0xc3, 0x7c, 0x94, 0x58, 0xd4, 0xa6, 0xa5, 0xa8,
	0xd6, 0x93, 0xfa, 0x70, 0x0a, 0xe8, 0xfe, 0x3a, 0x05, 0x8b, 0xe9, 0x3c, 0x22, 0x04, 0x93, 0x89,
	0x0b, 0xde, 0xfc, 0x8d, 0x16, 0xa1, 0xcc, 0xec, 0xb5, 0x81, 0xcb, 0xac, 0x8d, 0x76, 0x61, 0x46,
	0xc6, 0x77, 0xbd, 0x4d, 0x61, 0x51, 0xdd, 0xe4, 0xbd, 0x08, 0xf0, 0x00, 0x8b, 0xb6, 0xa1, 0x2c,
	0xa4, 0x1d, 0x72, 0x4f, 0x0a, 0x18, 0x2e, 0x9b, 0x65, 0xb8, 0x2c, 0xa4, 0xd6, 0x62, 0x6f, 0x62,
	0x67, 0xea, 0x52, 0x2d, 0x79, 0xf7, 0x32, 0x1e, 0x60, 0xd1, 0x1e, 0xcc, 0x9e, 0xd9, 0xaa, 0x35,
	0x9d, 0x3f, 0xd7, 0x78, 0x54, 0xc0, 0x93, 0x5b, 0xdc, 0x78, 0x88, 0x46, 0xf7, 0x60, 0x5a, 0x2a,
	0xa2, 0x22, 0x69, 0x86, 0xc0, 0x5c, 0x63, 0xce, 0xf0, 0xb4, 0x8c, 0x09, 0x5b, 0x17, 0xfa, 0x27,
	0xdc, 0xb4, 0x57, 0xda, 0x1e, 0xeb, 0x9c, 0x6d, 0x5e, 0x10, 0xd6, 0x25, 0x27, 0xac, 0xcb, 0x54,
	0xdf, 0xb4, 0xf9, 0x2c, 0x2e, 0x72, 0xeb, 0x02, 0x23, 0xdd, 0xae, 0xe8, 0xd1, 0xf6, 0x8b, 0x9e,
	0x7e, 0xbd, 0x88, 0x36, 0x95, 0x4e, 0x65, 0x7d, 0x62, 0xa3, 0x82, 0xc7, 0x1d, 0xa8, 0x0e, 0x10,
	0x88, 0x1e, 0x0d, 0xf5, 0xf2, 0xd4, 0x01, 0xd3, 0x77, 0xd7, 0x8c, 0xa0, 0xe6, 0xd0, 0x8c, 0x13,
	0x21, 0x3a, 0x0f, 0xd2, 0x56, 0xa4, 0x33, 0x77, 0x69, 0x1e, 0x72, 0x0b, 0x17, 0x0f, 0xd1, 0x3a,
	0x0f, 0xfa, 0x8a, 0x56, 0x7d, 0x67, 0x3e, 0x91, 0x87, 0x5d, 0x63, 0xc2, 0xd6, 0x85, 0x9a, 0xb0,
	0x72, 0x96, 0xd9, 0x61, 0x2c, 0x75, 0xc1, 0x48, 0xad, 0x1a, 0xcc, 0x5e, 0x5e, 0x04, 0xce, 0x07,
	0xa2, 0x55, 0x98, 0x54, 0xa4, 0x23, 0x9d, 0x45, 0xb3, 0x68, 0xc5, 0x10, 0xbc, 0x24, 0x1d, 0x89,
	0x8d, 0xd9, 0x7d, 0x5f, 0x82, 0xb5, 0x74, 0xc5, 0x8f, 0x1e, 0xfa, 0xf6, 0x9b, 0xe3, 0x05, 0x5c,
	0x4b, 0x47, 0x7c, 0xe4, 0xfb, 0x3d, 0x8b, 0x46, 0x5b, 0xf9, 0xdf, 0x19, 0x77, 0x72, 0xc6, 0x58,
	0xe1, 0x57, 0xc7, 0x87, 0x12, 0xdc, 0x2d, 0xd4, 0x6d, 0x3f, 0x3f, 0x3e, 0xb9, 0xf0, 0x4f, 0xf7,
	0xc9, 0xf1, 0x73, 0x39, 0x2b, 0x1f, 0x47, 0x7c, 0x5b, 0xf8, 0x3e, 0xe1, 0xed, 0x41, 0xde, 0x0f,
	0xb2, 0xb3, 0xc8, 0x7e, 0x31, 0x5c, 0x51, 0x7d, 0x76, 0x90, 0x6d, 0xc2, 0x74, 0x4b, 0x44, 0xa1,
	0x37, 0xb8, 0x35, 0x1e, 0xe4, 0xa4, 0x7b, 0x24, 0xa2, 0xe5, 0x85, 0x2c, 0x50, 0x31, 0x00, 0x5b,
	0x20, 0x62, 0x70, 0x6b, 0x14, 0xb1, 0xcf, 0x83, 0x48, 0x35, 0x49, 0x48, 0x7c, 0xaa, 0x46, 0x6f,
	0x99, 0x87, 0x97, 0xb2, 0xa6, 0x31, 0xb8, 0x98, 0x4d, 0x0f, 0x7c, 0x1c, 0xf1, 0x4d, 0xa9, 0xdf,
	0x40, 0xf1, 0x0b, 0x07, 0x8f, 0x0c, 0xe8, 0x3e, 0x2c, 0x98, 0x1f, 0x83, 0xf7, 0xaf, 0x19, 0x75,
	0x15, 0x9c, 0x36, 0xba, 0x3f, 0x96, 0x60, 0xbd, 0x38, 0xc9, 0xb6, 0x48, 0x3e, 0x71, 0x96, 0x0f,
	0x60, 0x7e, 0x9f, 0x4b, 0x45, 0xb8, 0x47, 0x8f, 0x18, 0xed, 0x5d, 0x29, 0xd7, 0x49, 0x00, 0x4e,
	0xc1, 0x1b, 0x3f, 0x4d, 0xc0, 0x9f, 0xd3, 0xb0, 0x4d, 0xad, 0x06, 0x75, 0x60, 0x7a, 0x9f, 0x5f,
	0x88, 0x73, 0x8a, 0x1e, 0x5d, 0x4d, 0x67, 0x5c, 0x53, 0xd5, 0xbf, 0x5d, 0x31, 0x3a, 0x4e, 0x8e,
	0xfb, 0x27, 0xf4, 0x16, 0x66, 0xe2, 0xc6, 0xa2, 0xe8, 0xef, 0x57, 0xc2, 0x66, 0xc7, 0x47, 0xf5,
	0xd9, 0xc7, 0xc2, 0x86, 0x6b, 0xef, 0xc1, 0xd2, 0xf6, 0x19, 0xf5, 0xce, 0x0f, 0x13, 0xff, 0x43,
	0x82, 0x6e, 0x8c, 0xf5, 0xdc, 0xae, 0x1f, 0xa8, 0x7e, 0xf5, 0x96, 0x59, 0x26, 0x19, 0x9a, 0x60,
	0xfa, 0x16, 0x60, 0x94, 0x6e, 0x74, 0x35, 0x45, 0x63, 0x0d, 0x59, 0xfd, 0xc7, 0x47, 0xe3, 0x06,
	0x02, 0xb6, 0x1e, 0xbf, 0xa9, 0x75, 0x98, 0x3a, 0x8b, 0x4e, 0x34, 0xa8, 0xee, 0x33, 0x2f, 0x14,
	0x52, 0x9c, 0xaa, 0xba, 0x2f, 0xbc, 0x7a, 0x18, 0x78, 0xf5, 0x21, 0x69, 0xdd, 0x92, 0x9e, 0x4c,
	0x9b, 0xfd, 0x3d, 0xf9, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x42, 0x2f, 0x17, 0x68, 0xdc, 0x12, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualMachineAgentClient is the client API for VirtualMachineAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineAgentClient interface {
	Invoke(ctx context.Context, in *VirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachineResponse, error)
	Operate(ctx context.Context, in *VirtualMachineOperationRequest, opts ...grpc.CallOption) (*VirtualMachineOperationResponse, error)
	CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error)
	RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error)
}

type virtualMachineAgentClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineAgentClient(cc *grpc.ClientConn) VirtualMachineAgentClient {
	return &virtualMachineAgentClient{cc}
}

func (c *virtualMachineAgentClient) Invoke(ctx context.Context, in *VirtualMachineRequest, opts ...grpc.CallOption) (*VirtualMachineResponse, error) {
	out := new(VirtualMachineResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.compute.VirtualMachineAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) Operate(ctx context.Context, in *VirtualMachineOperationRequest, opts ...grpc.CallOption) (*VirtualMachineOperationResponse, error) {
	out := new(VirtualMachineOperationResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.compute.VirtualMachineAgent/Operate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) CheckNotification(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*common.NotificationResponse, error) {
	out := new(common.NotificationResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.compute.VirtualMachineAgent/CheckNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualMachineAgentClient) RunCommand(ctx context.Context, in *VirtualMachineRunCommandRequest, opts ...grpc.CallOption) (*VirtualMachineRunCommandResponse, error) {
	out := new(VirtualMachineRunCommandResponse)
	err := c.cc.Invoke(ctx, "/moc.nodeagent.compute.VirtualMachineAgent/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineAgentServer is the server API for VirtualMachineAgent service.
type VirtualMachineAgentServer interface {
	Invoke(context.Context, *VirtualMachineRequest) (*VirtualMachineResponse, error)
	Operate(context.Context, *VirtualMachineOperationRequest) (*VirtualMachineOperationResponse, error)
	CheckNotification(context.Context, *empty.Empty) (*common.NotificationResponse, error)
	RunCommand(context.Context, *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error)
}

// UnimplementedVirtualMachineAgentServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineAgentServer struct {
}

func (*UnimplementedVirtualMachineAgentServer) Invoke(ctx context.Context, req *VirtualMachineRequest) (*VirtualMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) Operate(ctx context.Context, req *VirtualMachineOperationRequest) (*VirtualMachineOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Operate not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) CheckNotification(ctx context.Context, req *empty.Empty) (*common.NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNotification not implemented")
}
func (*UnimplementedVirtualMachineAgentServer) RunCommand(ctx context.Context, req *VirtualMachineRunCommandRequest) (*VirtualMachineRunCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}

func RegisterVirtualMachineAgentServer(s *grpc.Server, srv VirtualMachineAgentServer) {
	s.RegisterService(&_VirtualMachineAgent_serviceDesc, srv)
}

func _VirtualMachineAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.compute.VirtualMachineAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).Invoke(ctx, req.(*VirtualMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_Operate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).Operate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.compute.VirtualMachineAgent/Operate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).Operate(ctx, req.(*VirtualMachineOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_CheckNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).CheckNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.compute.VirtualMachineAgent/CheckNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).CheckNotification(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualMachineAgent_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineRunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.nodeagent.compute.VirtualMachineAgent/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineAgentServer).RunCommand(ctx, req.(*VirtualMachineRunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.nodeagent.compute.VirtualMachineAgent",
	HandlerType: (*VirtualMachineAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _VirtualMachineAgent_Invoke_Handler,
		},
		{
			MethodName: "Operate",
			Handler:    _VirtualMachineAgent_Operate_Handler,
		},
		{
			MethodName: "CheckNotification",
			Handler:    _VirtualMachineAgent_CheckNotification_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _VirtualMachineAgent_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_nodeagent_virtualmachine.proto",
}
