// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moc_cloudagent_virtualmachineimage.proto

package compute

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VirtualMachineImageRequest struct {
	VirtualMachineImages []*VirtualMachineImage `protobuf:"bytes,1,rep,name=VirtualMachineImages,proto3" json:"VirtualMachineImages,omitempty"`
	OperationType        common.Operation       `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VirtualMachineImageRequest) Reset()         { *m = VirtualMachineImageRequest{} }
func (m *VirtualMachineImageRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineImageRequest) ProtoMessage()    {}
func (*VirtualMachineImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ef669fbb27720b1, []int{0}
}

func (m *VirtualMachineImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineImageRequest.Unmarshal(m, b)
}
func (m *VirtualMachineImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineImageRequest.Marshal(b, m, deterministic)
}
func (m *VirtualMachineImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineImageRequest.Merge(m, src)
}
func (m *VirtualMachineImageRequest) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineImageRequest.Size(m)
}
func (m *VirtualMachineImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineImageRequest proto.InternalMessageInfo

func (m *VirtualMachineImageRequest) GetVirtualMachineImages() []*VirtualMachineImage {
	if m != nil {
		return m.VirtualMachineImages
	}
	return nil
}

func (m *VirtualMachineImageRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type VirtualMachineImageResponse struct {
	VirtualMachineImages []*VirtualMachineImage `protobuf:"bytes,1,rep,name=VirtualMachineImages,proto3" json:"VirtualMachineImages,omitempty"`
	Result               *wrappers.BoolValue    `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VirtualMachineImageResponse) Reset()         { *m = VirtualMachineImageResponse{} }
func (m *VirtualMachineImageResponse) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineImageResponse) ProtoMessage()    {}
func (*VirtualMachineImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ef669fbb27720b1, []int{1}
}

func (m *VirtualMachineImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineImageResponse.Unmarshal(m, b)
}
func (m *VirtualMachineImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineImageResponse.Marshal(b, m, deterministic)
}
func (m *VirtualMachineImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineImageResponse.Merge(m, src)
}
func (m *VirtualMachineImageResponse) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineImageResponse.Size(m)
}
func (m *VirtualMachineImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineImageResponse proto.InternalMessageInfo

func (m *VirtualMachineImageResponse) GetVirtualMachineImages() []*VirtualMachineImage {
	if m != nil {
		return m.VirtualMachineImages
	}
	return nil
}

func (m *VirtualMachineImageResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *VirtualMachineImageResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type VirtualMachineImage struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageReference       string                  `protobuf:"bytes,3,opt,name=imageReference,proto3" json:"imageReference,omitempty"`
	Path                 string                  `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Status               *common.Status          `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ContainerName        string                  `protobuf:"bytes,6,opt,name=containerName,proto3" json:"containerName,omitempty"`
	GroupName            string                  `protobuf:"bytes,18,opt,name=groupName,proto3" json:"groupName,omitempty"`
	LocationName         string                  `protobuf:"bytes,19,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Tags                 *common.Tags            `protobuf:"bytes,20,opt,name=tags,proto3" json:"tags,omitempty"`
	HyperVGeneration     common.HyperVGeneration `protobuf:"varint,21,opt,name=hyperVGeneration,proto3,enum=moc.HyperVGeneration" json:"hyperVGeneration,omitempty"`
	DiskFileFormat       common.DiskFileFormat   `protobuf:"varint,22,opt,name=diskFileFormat,proto3,enum=moc.DiskFileFormat" json:"diskFileFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *VirtualMachineImage) Reset()         { *m = VirtualMachineImage{} }
func (m *VirtualMachineImage) String() string { return proto.CompactTextString(m) }
func (*VirtualMachineImage) ProtoMessage()    {}
func (*VirtualMachineImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ef669fbb27720b1, []int{2}
}

func (m *VirtualMachineImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualMachineImage.Unmarshal(m, b)
}
func (m *VirtualMachineImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualMachineImage.Marshal(b, m, deterministic)
}
func (m *VirtualMachineImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualMachineImage.Merge(m, src)
}
func (m *VirtualMachineImage) XXX_Size() int {
	return xxx_messageInfo_VirtualMachineImage.Size(m)
}
func (m *VirtualMachineImage) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualMachineImage.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualMachineImage proto.InternalMessageInfo

func (m *VirtualMachineImage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VirtualMachineImage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VirtualMachineImage) GetImageReference() string {
	if m != nil {
		return m.ImageReference
	}
	return ""
}

func (m *VirtualMachineImage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *VirtualMachineImage) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VirtualMachineImage) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *VirtualMachineImage) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *VirtualMachineImage) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *VirtualMachineImage) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VirtualMachineImage) GetHyperVGeneration() common.HyperVGeneration {
	if m != nil {
		return m.HyperVGeneration
	}
	return common.HyperVGeneration_HyperVGenerationV1
}

func (m *VirtualMachineImage) GetDiskFileFormat() common.DiskFileFormat {
	if m != nil {
		return m.DiskFileFormat
	}
	return common.DiskFileFormat_DiskFileFormatVhd
}

func init() {
	proto.RegisterType((*VirtualMachineImageRequest)(nil), "moc.cloudagent.compute.VirtualMachineImageRequest")
	proto.RegisterType((*VirtualMachineImageResponse)(nil), "moc.cloudagent.compute.VirtualMachineImageResponse")
	proto.RegisterType((*VirtualMachineImage)(nil), "moc.cloudagent.compute.VirtualMachineImage")
}

func init() {
	proto.RegisterFile("moc_cloudagent_virtualmachineimage.proto", fileDescriptor_7ef669fbb27720b1)
}

var fileDescriptor_7ef669fbb27720b1 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x92, 0x46, 0xca, 0x86, 0x46, 0x68, 0x93, 0x16, 0x2b, 0xfc, 0x51, 0x14, 0x10,
	0x8a, 0x84, 0x64, 0x0b, 0x97, 0x1b, 0xa7, 0x56, 0x50, 0xe8, 0x01, 0x90, 0x4c, 0x95, 0x03, 0x97,
	0x68, 0xe3, 0x4c, 0x9c, 0x55, 0xed, 0x9d, 0x65, 0x77, 0x5d, 0xd4, 0xa7, 0xe0, 0x19, 0x78, 0x06,
	0x5e, 0x82, 0xc7, 0x42, 0x1e, 0x1b, 0xa2, 0x04, 0x5f, 0x7a, 0xe8, 0x29, 0x9b, 0x99, 0xdf, 0x7e,
	0xf3, 0x6d, 0xe6, 0x0b, 0x9b, 0xe5, 0x98, 0x2c, 0x92, 0x0c, 0x8b, 0x95, 0x48, 0x41, 0xb9, 0xc5,
	0xb5, 0x34, 0xae, 0x10, 0x59, 0x2e, 0x92, 0x8d, 0x54, 0x20, 0x73, 0x91, 0x42, 0xa0, 0x0d, 0x3a,
	0xe4, 0xc7, 0x39, 0x26, 0xc1, 0x96, 0x0c, 0x12, 0xcc, 0x75, 0xe1, 0x60, 0xfc, 0x34, 0x45, 0x4c,
	0x33, 0x08, 0x89, 0x5a, 0x16, 0xeb, 0xf0, 0xbb, 0x11, 0x5a, 0x83, 0xb1, 0xd5, 0xbd, 0xf1, 0x43,
	0x9a, 0x80, 0x79, 0x8e, 0xaa, 0xfe, 0xa8, 0x1a, 0xd3, 0x5f, 0x1e, 0x1b, 0xcf, 0xab, 0x71, 0x1f,
	0xab, 0x71, 0x17, 0xe5, 0xb8, 0x18, 0xbe, 0x15, 0x60, 0x1d, 0x5f, 0xb0, 0x51, 0x43, 0xd7, 0xfa,
	0xde, 0xa4, 0x3d, 0xeb, 0x47, 0x2f, 0x83, 0x66, 0x3b, 0x41, 0x93, 0x62, 0xa3, 0x10, 0x7f, 0xcd,
	0x0e, 0x3f, 0x6b, 0x30, 0xc2, 0x49, 0x54, 0x97, 0x37, 0x1a, 0xfc, 0xd6, 0xc4, 0x9b, 0x0d, 0xa2,
	0x01, 0x29, 0xff, 0xeb, 0xc4, 0xbb, 0xd0, 0xf4, 0xb7, 0xc7, 0x1e, 0x35, 0xba, 0xb6, 0x1a, 0x95,
	0x85, 0xbb, 0xb7, 0x1d, 0xb1, 0x6e, 0x0c, 0xb6, 0xc8, 0x1c, 0xf9, 0xed, 0x47, 0xe3, 0xa0, 0x5a,
	0x40, 0xf0, 0x77, 0x01, 0xc1, 0x19, 0x62, 0x36, 0x17, 0x59, 0x01, 0x71, 0x4d, 0xf2, 0x11, 0x3b,
	0x78, 0x67, 0x0c, 0x1a, 0xbf, 0x3d, 0xf1, 0x66, 0xbd, 0xb8, 0xfa, 0x32, 0xfd, 0xd9, 0x66, 0xc3,
	0x86, 0x11, 0x9c, 0xb3, 0x8e, 0x12, 0x39, 0xf8, 0x1e, 0xc1, 0x74, 0xe6, 0x03, 0xd6, 0x92, 0x2b,
	0x9a, 0xd8, 0x8b, 0x5b, 0x72, 0xc5, 0x5f, 0xb0, 0x81, 0xac, 0xde, 0xbd, 0x06, 0x03, 0x2a, 0x81,
	0x5a, 0x7a, 0xaf, 0x5a, 0x6a, 0x69, 0xe1, 0x36, 0x7e, 0xa7, 0xd2, 0x2a, 0xcf, 0xfc, 0x19, 0xeb,
	0x5a, 0x27, 0x5c, 0x61, 0xfd, 0x03, 0x7a, 0x41, 0x9f, 0x7e, 0x94, 0x2f, 0x54, 0x8a, 0xeb, 0x16,
	0x7f, 0xce, 0x0e, 0x13, 0x54, 0x4e, 0x48, 0x05, 0xe6, 0x53, 0xe9, 0xa6, 0x4b, 0x0a, 0xbb, 0x45,
	0xfe, 0x98, 0xf5, 0x52, 0x83, 0x85, 0x26, 0x82, 0x13, 0xb1, 0x2d, 0xf0, 0x29, 0xbb, 0x9f, 0x61,
	0x42, 0xbb, 0x23, 0x60, 0x48, 0xc0, 0x4e, 0x8d, 0x3f, 0x61, 0x1d, 0x27, 0x52, 0xeb, 0x8f, 0xc8,
	0x4a, 0x8f, 0xac, 0x5c, 0x8a, 0xd4, 0xc6, 0x54, 0xe6, 0xa7, 0xec, 0xc1, 0xe6, 0x46, 0x83, 0x99,
	0xbf, 0x07, 0x55, 0xc7, 0xc0, 0x3f, 0xa2, 0x9c, 0x1c, 0x11, 0xfa, 0x61, 0xaf, 0x19, 0xff, 0x87,
	0xf3, 0x37, 0x6c, 0xb0, 0x92, 0xf6, 0xea, 0x5c, 0x66, 0x70, 0x8e, 0x26, 0x17, 0xce, 0x3f, 0x26,
	0x81, 0x21, 0x09, 0xbc, 0xdd, 0x69, 0xc5, 0x7b, 0x68, 0xf4, 0xc3, 0x63, 0x7e, 0xc3, 0x8e, 0x4e,
	0xcb, 0xf0, 0x70, 0xcb, 0xba, 0x17, 0xea, 0x1a, 0xaf, 0x80, 0x47, 0xb7, 0xc9, 0x55, 0xf5, 0x07,
	0x1b, 0x9f, 0xdc, 0xea, 0x4e, 0x15, 0xef, 0xe9, 0xbd, 0xb3, 0x57, 0x5f, 0xc3, 0x54, 0xba, 0x4d,
	0xb1, 0x2c, 0xf9, 0x30, 0x97, 0x89, 0x41, 0x8b, 0x6b, 0x17, 0xe6, 0x98, 0x84, 0x46, 0x27, 0xe1,
	0x56, 0x30, 0xac, 0x05, 0x97, 0x5d, 0x8a, 0xe6, 0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01,
	0x7b, 0xd3, 0x4f, 0x6d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VirtualMachineImageAgentClient is the client API for VirtualMachineImageAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtualMachineImageAgentClient interface {
	Invoke(ctx context.Context, in *VirtualMachineImageRequest, opts ...grpc.CallOption) (*VirtualMachineImageResponse, error)
}

type virtualMachineImageAgentClient struct {
	cc *grpc.ClientConn
}

func NewVirtualMachineImageAgentClient(cc *grpc.ClientConn) VirtualMachineImageAgentClient {
	return &virtualMachineImageAgentClient{cc}
}

func (c *virtualMachineImageAgentClient) Invoke(ctx context.Context, in *VirtualMachineImageRequest, opts ...grpc.CallOption) (*VirtualMachineImageResponse, error) {
	out := new(VirtualMachineImageResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.compute.VirtualMachineImageAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineImageAgentServer is the server API for VirtualMachineImageAgent service.
type VirtualMachineImageAgentServer interface {
	Invoke(context.Context, *VirtualMachineImageRequest) (*VirtualMachineImageResponse, error)
}

// UnimplementedVirtualMachineImageAgentServer can be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineImageAgentServer struct {
}

func (*UnimplementedVirtualMachineImageAgentServer) Invoke(ctx context.Context, req *VirtualMachineImageRequest) (*VirtualMachineImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterVirtualMachineImageAgentServer(s *grpc.Server, srv VirtualMachineImageAgentServer) {
	s.RegisterService(&_VirtualMachineImageAgent_serviceDesc, srv)
}

func _VirtualMachineImageAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachineImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineImageAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.compute.VirtualMachineImageAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineImageAgentServer).Invoke(ctx, req.(*VirtualMachineImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtualMachineImageAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.cloudagent.compute.VirtualMachineImageAgent",
	HandlerType: (*VirtualMachineImageAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _VirtualMachineImageAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moc_cloudagent_virtualmachineimage.proto",
}
